Add an Event Log Activity class
ocsf/ocsf-schema pull request #1014
Opened 2024-04-03 20:20 UTC by mikeradka

#### Related Issue: 
#839 Event Log Activity eg 'Audit Log Cleared'

#### Description of changes:

This PR adds a new class for actions pertaining to monitoring of the System Event Log Service.

2024-04-16 16:33 UTC, jasonbreimer commented
What about a "set-log" activity id? I'm looking at the various detections written against event log activities and I see the concept of event log configuration setting modification. An entity can modify settings regarding the event log using wevtutil command set-log.

2024-04-16 16:38 UTC, jasonbreimer commented
Another thought...when looking at clear event log it looks like there are return code status values. This list is oddly limited linked below but I see "success" and "privilege missing". Do we want to capture the successful event or get down to this next layer of capturing a failure by adding some kind of status/return code for each activity id?

https://learn.microsoft.com/en-us/previous-versions/windows/desktop/eventlogprov/cleareventlog-method-in-class-win32-nteventlogfile

2024-04-16 16:40 UTC, mikeradka commented
> Another thought...when looking at clear event log it looks like there are return code status values. This list is oddly limited linked below but I see "success" and "privilege missing". Do we want to capture the successful event or get down to this next layer of capturing a failure by adding some kind of status/return code for each activity id?
> 
> https://learn.microsoft.com/en-us/previous-versions/windows/desktop/eventlogprov/cleareventlog-method-in-class-win32-nteventlogfile

That is a good find! Thanks for the suggestion - will take a look at what is possible, it seems like this may be good context to capture.

2024-04-17 22:30 UTC, mikeradka commented
For some reason this is failing for `unrecognized keys`:

```TESTING: There are no unrecognized keys
   ERROR: Unrecognized key `actor` of `OcsfAttr` at `attributes.activity_id` in events/system/event_log.json
   ERROR: Unrecognized key `log_file` of `OcsfAttr` at `attributes.activity_id` in events/system/event_log.json
   ERROR: Unrecognized key `log_name` of `OcsfAttr` at `attributes.activity_id` in events/system/event_log.json
   ERROR: Unrecognized key `log_provider` of `OcsfAttr` at `attributes.activity_id` in events/system/event_log.json```

2024-04-17 23:29 UTC, mikeradka commented
Created Issue #1047 to address the discrepancy in validation failure output.

2024-04-18 13:21 UTC, mikeradka commented
> What about a "set-log" activity id? I'm looking at the various detections written against event log activities and I see the concept of event log configuration setting modification. An entity can modify settings regarding the event log using wevtutil command set-log.

This is a good suggestion, @jasonbreimer. I took a look at the [Microsoft wevtutil documentation](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil), and it notes:

> Enables you to retrieve information about event logs and publishers. You can also use this command to install and **uninstall event manifests**, to **run queries**, and to **export**, **archive**, and **clear** logs.

The `Archive`, and `Clear` actions are covered, and I've added `Export` to the actions. However, I am not yet certain on how we should approach `uninstall event manifests` and `run queries`. Maybe `Uninstall` and `Query` actions are sufficient, but I would like to get some further inputs.

2024-04-22 16:20 UTC, pagbabian-splunk commented
> > What about a "set-log" activity id? I'm looking at the various detections written against event log activities and I see the concept of event log configuration setting modification. An entity can modify settings regarding the event log using wevtutil command set-log.
> 
> This is a good suggestion, @jasonbreimer. I took a look at the [Microsoft wevtutil documentation](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil), and it notes:
> 
> > Enables you to retrieve information about event logs and publishers. You can also use this command to install and **uninstall event manifests**, to **run queries**, and to **export**, **archive**, and **clear** logs.
> 
> The `Archive`, and `Clear` actions are covered, and I've added `Export` to the actions. However, I am not yet certain on how we should approach `uninstall event manifests` and `run queries`. Maybe `Uninstall` and `Query` actions are sufficient, but I would like to get some further inputs.
> 
> @floydtree, @pagbabian-splunk, @k2niner any thoughts on whether `Uninstall` and `Query` could work as activities for this new class?

If we don't yet know how to address these two activities, we can hold off until we do, and add them later.  Unless @jasonbreimer or others have a use case of course.  I haven't researched it so I don't have any informed suggestion at the moment.

2024-04-23 17:35 UTC, floydtree requested changes

2024-04-23 17:35 UTC, floydtree commented on CHANGELOG.md
> +    19. Added `Event Log Activity` event class. #1014
This will need to be moved to the `Unreleased` section

2024-04-23 18:25 UTC, mikeradka commented on CHANGELOG.md
> +    19. Added `Event Log Activity` event class. #1014
Nice catch @floydtree . I've updated the `CHANGELOG`, please take a look

2024-04-25 14:31 UTC, floydtree approved these changes

2024-04-25 14:31 UTC, floydtree commented on events/system/event_log.json
> +      "description": "The logging provider or logging service <p style='display:inline;color:red'>targeted by</p> the activity.<br />Example: <code>Microsoft-Windows-Security-Auditing</code>, <code>A
Nice idea to highlight specific strings in the desc. Something to incorporate throughout the schema.

2024-04-25 14:32 UTC, mikeradka commented on events/system/event_log.json
> +      "description": "The logging provider or logging service <p style='display:inline;color:red'>targeted by</p> the activity.<br />Example: <code>Microsoft-Windows-Security-Auditing</code>, <code>A
That was all @zschmerber 's suggestion!

2024-04-26 21:37 UTC, rmouritzen-splunk approved these changes

2024-04-29 13:12 UTC, merged