Address gaps in Process Activity and Memory Activity wrt process injection.
ocsf/ocsf-schema pull request #1060
Opened 2024-04-23 16:31 UTC by davemcatcisco

#### Related Issue: 

[#1041: Process Activity and Memory Activity cannot adequately describe common injection-related behaviours](https://github.com/ocsf/ocsf-schema/issues/1041)

#### Description of changes:

* Added entry to `injection_type_id` enum in dictionary.json to cover queueing of an asynchronous procedure call (APC).
* Added entry to `activity_id` enum in events/system/memory.json to cover mapping of shared memory object.

2024-04-23 16:35 UTC, davemcatcisco commented
This PR replaces #1042 which had targetted the now released 1.2.0 branch. Otherwise unchanged.

2024-04-23 16:36 UTC, davemcatcisco commented
@pagbabian-splunk - If you could re-approve this copy of the original PR I would appreciate it. I'd also appreciate your guidance on how best to engage other code owners.

2024-04-23 16:50 UTC, floydtree requested changes

2024-04-23 16:50 UTC, floydtree commented on CHANGELOG.md
> +    10. Added entries to `injection_type_id` enum (`Process Activity`) and `activity_id` enum (`Memory Activity`). #1060
This will need to be in the `Unreleased` section

2024-04-23 16:56 UTC, davemcatcisco commented on CHANGELOG.md
> +    10. Added entries to `injection_type_id` enum (`Process Activity`) and `activity_id` enum (`Memory Activity`). #1060
@floydtree  - Of course, I just put it in the same place as the last PR. Fixed now. Thanks.

2024-04-23 16:57 UTC, floydtree approved these changes

2024-04-24 19:11 UTC, zschmerber approved these changes

2024-04-24 19:44 UTC, mikeradka approved these changes
Looks great

2024-04-24 19:44 UTC, merged

2024-04-25 16:42 UTC, davemcatcisco commented
Thanks, all.