Evidences object update
ocsf/ocsf-schema pull request #1062
Opened 2024-04-24 11:38 UTC by a-fishman

Related Issue: https://github.com/ocsf/ocsf-schema/issues/1000

Description of changes:

Adding account, device, email, url, user to evidences in detection finding.

Signed-off-by: Anton Fishman anton.fishman@hunters.ai

2024-04-30 15:02 UTC, floydtree requested changes

2024-04-30 15:02 UTC, floydtree commented on objects/evidences.json
> +    "user": {
Would be useful to clarify in the description when one should use `actor` vs. using `user`

2024-05-01 10:20 UTC, a-fishman commented on CHANGELOG.md
> +* #### Added account, device, email, url, user to evidences in detection finding.
Fixed

2024-05-01 10:21 UTC, a-fishman commented on objects/evidences.json
>    "constraints": {
Fixed

2024-05-01 10:23 UTC, a-fishman commented on objects/evidences.json
> +    "user": {
Added in user description that it's a target or somehow associated with the activity. 
So if actor - it's a source, user - target or some related user.

2024-05-03 20:01 UTC, pagbabian-splunk approved these changes

2024-05-07 13:49 UTC, floydtree approved these changes

2024-05-08 16:07 UTC, mikeradka approved these changes

2024-05-08 16:07 UTC, merged