External ticket support of ticketing systems like salesforce.
ocsf/ocsf-schema pull request #1067
Opened 2024-04-30 15:01 UTC by PavelJurka

…n url + uid, title optional, linked from incident finding.

#### Related Issue: 

#### Description of changes:

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Have you assigned appropriate labels to the PR?
5. Is your PR title in sync with the description?

2024-05-03 18:35 UTC, mikeradka commented
Two suggestions for this one:

1. We should be very judicious with `required` attributes. For `uid` and `src_url`, we should consider making those `recommended` and applying a constraint to the object so that one of those is `required`.
2. To avoid `external_ticket` being too specific to implementation, we should consider broadening this to just `ticket`. We could also consider adding an enum for `internal` vs `external`.

2024-05-06 11:47 UTC, PavelJurka commented
> Here are two recommendations for consideration:
> 
> 1. Exercise caution when designating attributes as `required`. For `uid` and `src_url`, it may be prudent to classify them as `recommended` and enforce a `constraint` ensuring that at least one is provided within the object.
> 2. To enhance flexibility and minimize implementation specificity, it is advisable to replace `external_ticket` with a more generic term such as `ticket`. Additionally, introducing an enumeration to distinguish between internal and external tickets could further refine this attribute.

thank you!

2024-05-07 15:41 UTC, floydtree requested changes

2024-05-07 15:41 UTC, floydtree commented on dictionary.json
> +    "ticket_type": {
On the similar note of your Digital Signature PR, you can reuse attributes `type` & `type_id` in the new `ticket` object with overridden descriptions and enums, without having to create new fields

2024-05-07 16:15 UTC, PavelJurka commented on dictionary.json
> +    "ticket_type": {
+ description

2024-05-08 16:05 UTC, mikeradka commented on CHANGELOG.md
> +    2.  Added `ticket` to `Incident Findind` object. ticket. #1068
Nit: Typo on `Incident Finding`

2024-05-15 21:50 UTC, pagbabian-splunk submitted a review, later dismissed

2024-05-16 17:31 UTC, mikeradka approved these changes

2024-05-17 16:22 UTC, pagbabian-splunk approved these changes

2024-05-17 19:05 UTC, mikeradka approved these changes

2024-05-17 19:13 UTC, floydtree approved these changes

2024-05-17 19:13 UTC, merged