Feat: [#1069] - added signate state id into the Digital signature to …
ocsf/ocsf-schema pull request #1070
Opened 2024-05-02 12:59 UTC by PavelJurka

…map the current signature state.

#### Related Issue: 
https://github.com/ocsf/ocsf-schema/issues/1069
#### Description of changes:
Map the signature state to signature state id (+signature state as usual)

2024-05-03 18:21 UTC, mikeradka commented
We discussed this a bit offline, and it looks like to avoid adding a new dictionary object, we could accomplish this by simply using the `status_id` and `status` attributes within the `Digitial Signature` object, and overwrite the default enums with the desired enums (`revoked`, `expired`, etc)

2024-05-03 18:25 UTC, floydtree requested changes

2024-05-03 18:25 UTC, floydtree commented on dictionary.json
> +    "signature_state": {
Can use `status` here, instead of a new attribute.

2024-05-03 18:25 UTC, floydtree commented on dictionary.json
> +    "signature_state_id": {
can use `status_id`here, instead of a new attribute. 

Feel free to ping any of the reviewers if you need help with this.

2024-05-03 19:57 UTC, pagbabian-splunk commented on dictionary.json
> +    "signature_state_id": {
We also have a `state_id` and `state` sibling used in a few classes and the `Security State` object.  I'm not sure if we have a solid rationale on when we use a `_state` attribute (there are a few others with their own prefixes) vs. `status_id` / `status` with overrides from the Base class.

If we consider that the defaults for `status_id` are `Success` and `Failure`, then this attribute is more of a result of some kind.  We've also overridden it or added to it in 9 places: e.g. `Detection Finding` completely overrides it, with lifecycle values (New, In Progress, Resolved).

Therefore, the use of `status` has been for results or lifecycle, while `_state` attributes seem to be representing points in time irrespective of lifecycle, or result.  One exception to this is `run_state` which is the lifecycle of a Job.

2024-05-06 12:05 UTC, PavelJurka commented
> We discussed this a bit offline, and it looks like to avoid adding a new dictionary object, we could accomplish this by simply using the `status_id` and `status` attributes within the `Digitial Signature` object, and overwrite the default enums with the desired enums (`revoked`, `expired`, etc)

Thank you, that make sense.

2024-05-07 15:36 UTC, floydtree commented on dictionary.json
> +    "signature_state_id": {
Good point Paul, I don't we have a rationale to distinguish between status and state, but the one you mentioned above sounds good to me. With that in mind, `state_id` & `state` would better suit this use-case than `status_id` & `status`. @PavelJurka can you update the object to use state and state_id instead?

2024-05-08 16:03 UTC, mikeradka approved these changes
This looks good to me

2024-05-09 14:20 UTC, Aniak5 commented on objects/digital_signature.json
> +      },
Do we want to add the `Suspended` and `Pending` states? Or did you want to represent those using `Other`?

2024-05-10 08:50 UTC, PavelJurka commented on objects/digital_signature.json
> +      },
I would keep it simple this way. @mikeradka :)? Thank you

2024-05-15 17:12 UTC, Aniak5 approved these changes
LGTM!

2024-05-15 18:24 UTC, floydtree approved these changes

2024-05-15 21:45 UTC, pagbabian-splunk approved these changes

2024-05-15 21:45 UTC, merged