Feat: [#1109] - extended compliance finding - compliance by adding co…
ocsf/ocsf-schema pull request #1110
Opened 2024-06-11 09:35 UTC by PavelJurka

…mpliance_references and _standards based on kb_article to provide possibility to map KB articles with information relevant to finding.

#### Related Issue: 

#### Description of changes:

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Is your PR title in sync with the description?

2024-06-11 16:16 UTC, irakledibm submitted a review, later dismissed
lgtm

2024-06-18 15:41 UTC, jasonbreimer submitted a review, later dismissed
Looks good.

2024-06-26 21:21 UTC, davemcatcisco approved these changes

2024-06-28 16:20 UTC, davemcatcisco approved these changes

2024-06-28 17:28 UTC, irakledibm approved these changes

2024-06-28 19:16 UTC, floydtree requested changes

2024-06-28 19:16 UTC, floydtree commented on objects/compliance.json
> +    "compliance_standards": {
A quick question, how do you want to distinguish between this new attribute and the existing `standards` attribute?

2024-06-28 19:16 UTC, floydtree commented on objects/compliance.json
> +    "compliance_references": {
Are you specifically looking for a kb_article type object for this one? If not, there's a simple `references` attribute available in the schema. A few samples of the target data will be helpful.

2024-07-01 09:14 UTC, PavelJurka commented on objects/compliance.json
> +    "compliance_standards": {
The standards field is only an array of string - we would like to have i more sophisticated - title, name of a standard, url link, etc. and KB Article works perfectly.

2024-07-01 09:15 UTC, PavelJurka commented on objects/compliance.json
> +    "compliance_references": {
The same as previous - references is only a plain string array - we'd like to have it more sophisticated -> - title, name of a standard, url link, etc. and KB Article works perfectly.

2024-07-02 16:10 UTC, floydtree approved these changes

2024-07-02 16:10 UTC, merged

2024-07-02 16:13 UTC, Aniak5 commented on CHANGELOG.md
> +    10. Added array-typed `compliacne_references` and array-typed `compliance_standards` objects as array of `kb_article` and used in `compliance` object. #1110
This is misspelled and should be `compliance_references`.