Backwards Compatibility Workflow
ocsf/ocsf-schema pull request #1115
Opened 2024-06-19 19:43 UTC by query-jeremy

This PR does *not* change the OCSF. 

Instead, it enhances the pull request workflow:
* The schema validator version can now be configured with a repository variable, allowing repository owners to update the dependency without a PR.
* A new backwards compatibility validation has been added using the [ocsf-validate-compatibility](https://github.com/ocsf/ocsf-validate-compatibility) project.

2024-06-21 23:17 UTC, rmouritzen-splunk commented on .github/workflows/validate-compatibility.yml
> +      run: mix compile & mix release --path dist
```suggestion

    - name: Clean server build
      working-directory: server
      run: mix clean --deps

    - name: Install server dependencies
      working-directory: server
      run: mix deps.get

    - name: Build the server
      working-directory: server
      run: mix compile & mix release --path dist
```

2024-06-21 23:17 UTC, rmouritzen-splunk commented on .github/workflows/validate-compatibility.yml
> +      run: mix compile & mix release --path dist
Try cleaning first in the hope this will clear the build error.

2024-06-24 13:09 UTC, query-jeremy commented on .github/workflows/validate-compatibility.yml
> +        otp-version: '25.3.2'    # Define the OTP version [required]
I had tried Elixir 1.17 and OTP 26 or 27 explicitly. It didn't solve the problem, but I saw a lot of warnings (for instance: `use` is deprecated, use `import`...) so I reverted back... but those warnings are still present :-/

2024-07-31 22:41 UTC, query-jeremy commented
Reviewers: once this is merged, PR's that introduce breaking changes will fail. Hoorah.

However, there's a lot of new code here. I couldn't get the OCSF server to do what I needed in a GitHub action (possibly user error) so I wrote an alternate OCSF compiler, now free to all in the `ocsf-lib-py` repository. It's tested with an automated comparison between its schema export and that of the OCSF server, but it's still new and hasn't had much review. And I will be unavailable the week of August 5th. Feel free to wait for me to be back on August 12th to merge, just in case something goes sideways.

2024-08-12 19:40 UTC, floydtree requested changes

2024-08-12 19:40 UTC, floydtree commented on .github/workflows/validate-compatibility.yml
> +      run: export FORCE_COLOR=1 && python -m ocsf.validate.compatibility ${{ vars.LATEST_STABLE || '1.2.0' }} .
version `1.3.0` instead 1.2.0? Guessing this was pre 1.3.0 release

2024-08-12 22:28 UTC, query-jeremy commented on .github/workflows/validate-compatibility.yml
> +      run: export FORCE_COLOR=1 && python -m ocsf.validate.compatibility ${{ vars.LATEST_STABLE || '1.2.0' }} .
Oh good catch. GitHub repository variables will take precedence so that anyone with permissions (not me) can change the version without a PR, but I'll update this default.

2024-08-12 22:49 UTC, query-jeremy commented on .github/workflows/validate-compatibility.yml
> +      run: export FORCE_COLOR=1 && python -m ocsf.validate.compatibility ${{ vars.LATEST_STABLE || '1.2.0' }} .
Now updated to 1.3.0, and also updated `ocsf-lib` to 0.8 so that is has the 1.3 schema cached.

2024-08-13 16:03 UTC, rmouritzen-splunk approved these changes

2024-08-13 16:10 UTC, floydtree approved these changes

2024-08-13 16:10 UTC, zschmerber approved these changes
Great work!

2024-08-13 16:11 UTC, mikeradka approved these changes

2024-08-13 16:25 UTC, merged