Adding the Startup Application Query event class in the discovery category.
ocsf/ocsf-schema pull request #1119
Opened 2024-06-25 02:22 UTC by maxhotta

The Startup Application Query class captures the results of a discovery on target devices.
This class was refactored from a previous submission, while incorporating feedback from Paul.

#### Description of changes:
Made the Startup Application object more clear by factoring out unrelated items in the type_id list.
The list now describes only the type of application.
A run_mode attribute was added as an array to capture the other items.
Also added a run_state to capture the state of the application at the time the event was logged.

2024-06-26 21:16 UTC, davemcatcisco requested changes
I have a number of concerns about this PR:
1. If scheduled tasks/jobs are a supported startup application type (and they seem to be because `Scheduled` is one of the values in `start_type_id`) then the `file` and `cmd_line` attributes should not be `required` and `recommended` respectively because Windows scheduled tasks don't necessarily have an associated executable file or command line. Also, the `type_id` enum should have an entry for a scheduled task/job.
2. Is there a reason why `run_mode` isn't `run_mode_id` with a corresponding `run_mode` companion attribute?
3. `start_type_id` should cross-reference `start_type` in its `sibling` property.
4. Instead of having attributes like `start_type_id`, `cmd_line`, `file`, `run_state_id`, etc. the `startup_app` object could (should?) reuse existing object types that describe the same properties of the relevent entities. For example, `startup_app` could have a `win_service` attribute that would apply when the `type_id` is `Service`. It could have a `schedule_job` attribute that would apply when the `type_id` is `Scheduled Job`.  This would avoid the `startup_app` object having lots of required attributes that don't make sense for certain values of `type_id`.

2024-07-02 17:43 UTC, maxhotta commented
@davemcatcisco Per further discussion on your point 4, the consensus was to use a 'just one' constraint on the different types that the startup_app could be, and add objects (as you suggest) to model the startup_app type.  I will revise, and post an update with these changes.

2024-07-15 21:22 UTC, maxhotta commented
Incorporated most items, except for adding the win_service object as one of the options for the target startup application.
It is defined in the extension dictionary file and thus trying to find a way to include it.

2024-07-23 15:14 UTC, floydtree requested changes

2024-07-23 15:14 UTC, floydtree commented on objects/startup_app.json
> +    "win/win_service": {
@maxhotta thinking more about this, I was looking at the rendered schema, the json_schema renders it as `win_win_service`, while the ocsf schema in json renders it as `win/win_service`. I think both of these are not ideal, in fact are incorrect. It should be rendered as `win_service` in the schema. 

@pagbabian-splunk  @rickmode thoughts on this? Max wants to add an attribute defined in the windows extension in this class.

2024-07-23 22:10 UTC, maxhotta commented
I've fixed the schema validation issue by 'patching' the startup_app object in windows extensions.  There was an issue in defining the constraints in the patched startup_app object which includes win_service.  To address this, I've defined win_service and its corresponding constraint in the core startup_app object.

2024-07-23 22:16 UTC, rmouritzen-splunk commented on objects/startup_app.json
> +      "win_service"
This is ugly, but as good as anything at the moment. There is a Slack discussion occurring around this kind of thing, as `evidences` tries but fails to do the same kind of thing.

2024-07-24 12:09 UTC, davemcatcisco requested changes

2024-07-24 12:09 UTC, davemcatcisco commented on objects/startup_app.json
> +  "caption": "Startup Application",
I have two issues with "startup_app" and "Startup Application".

- The first issue is with the part before the underscore. I suspect that your intention here is not to cover things that happen on startup but rather things that happen _automatically_. For example, threats often achieve persistence by creating a scheduled task, and a multitude of different triggers can be used to cause the scheduled task to run, e.g. log on, on idle, workstation locked, etc. I think what you are really driving at here then is "autorun" rather than "startup". 

- The second issue is with the part after the underscore. You allow for things like loading drivers, starting daemons/services, etc. These things aren't really "apps" as the term would normally be understood. Also, a scheduled task on Windows can do things other than run an app. It can instantiate a COM class and invoke a method on it. There isn't really any app in this case.

I'm wondering therefore if "autorun_action" and "Autorun Action" might be more appropriate here.

2024-07-29 18:26 UTC, maxhotta commented on objects/startup_app.json
> +      "enum": {
This is an optional field that can be used to capture properties of a running startup app (description updated).  Note that the default list currently is short, but more can be added as needed.

2024-07-29 18:28 UTC, maxhotta commented on objects/startup_app.json
> +        "0": {
The reason I didn't add a "0" (unknown) option is b/c it is an optional field.
If the convention is to always supply a "0" (unknown) field, I can change this.

2024-07-29 18:33 UTC, maxhotta commented on dictionary.json
> +      "description": "The list of normalized identifiers that describe application attributes.",
Added a more descriptive explanation

2024-07-30 16:13 UTC, davemcatcisco commented on objects/startup_app.json
> +        "0": {
It's a good idea to reserve the 0 value of an enumeration to have a special meaning like Unknown, Not Set, Invalid, Null, etc. Reason is that this ensures that a zero-initialised variable of that type can't "accidentally" have a meaningful value. So, yes, I think you should follow the pattern of having a 0 Unkown value here.

2024-08-13 15:56 UTC, pagbabian-splunk commented on objects/startup_app.json
> +    "win/win_service": {
Let's discuss today in the weekly call.  We have been thinking about removing platform extensions but don't have a way to do this in a non-breaking way yet.  Also, this behavior would show up for other extensions too, which isn't good.

2024-08-13 15:59 UTC, pagbabian-splunk commented on objects/startup_app.json
> +      "description": "The list of normalized identifiers that describe application attributes.",
We have two conventions: the dictionary declares the enum (with just the Unknown and Other values) and classes add specific values.  This is usually done with a 'See specific usage' in the description which the compiler recognizes and gives warnings if the enum isn't extended or overridden.  The other convention is to completely define it in the dictionary meaning it must be used as is in all classes that need it.  We don't want anything in between those two.

2024-08-15 01:28 UTC, rmouritzen-splunk commented on extensions/windows/objects/startup_app.json
@maxhotta This is fine. If someone "compiles" the schema without the `windows` extension, this patch won't be invoked. There no further support needed. (We're aren't require any special use of profiles when patching.)

2024-08-15 01:37 UTC, rmouritzen-splunk commented on objects/startup_app.json
> +      "win_service"
Instead of putting `win_service` in the constraints here, put them in the `extensions/windows/objects/startup_app.json`. Patches can't modify constraints (we can't apply a delta to existing constraints), but as with any class or object `extends`, they can add or replace them.

Specifically:
1. Keep `constraints` here, but remove `win_service`.
2. In the `windows` extension patch of `startup_app`, put these `constraints` exactly as above, but with `win_service` included.

2024-08-15 01:40 UTC, rmouritzen-splunk commented on objects/startup_app.json
> +  }
```suggestion
  "constraints": {
    "just_one": [
      "driver",
      "job",
      "process"
    ]
  }
```
As mentioned above, `constraints` with `win_service` removed. (It will be in the patch though.)

2024-08-15 01:46 UTC, rmouritzen-splunk requested changes

2024-08-15 01:46 UTC, rmouritzen-splunk commented on extensions/windows/objects/startup_app.json
> +  }
```suggestion
  },
  "constraints": {
    "just_one": [
      "driver",
      "job",
      "process",
      "win_service"
    ]
  }
```
This will override the `constraints` in `startup_app` and replace them with this one that has `win_service` added.

2024-08-15 01:46 UTC, rmouritzen-splunk commented on objects/startup_app.json
> +  }
```suggestion
  "constraints": {
    "just_one": [
      "driver",
      "job",
      "process"
    ]
  }
```
Remove `win_service` from the `constraints` here in the base `startup_app`. The patch of `startup_app` will add a `constraints` that includes `win_service`. When a schema is compiled without the `windows` extension, this will avoid attempting to use an undefined `win_service` attribute.

2024-08-15 02:19 UTC, maxhotta commented on objects/startup_app.json
> +  }
Thanks @rmouritzen-splunk I'll give that a go.

2024-08-16 18:30 UTC, maxhotta commented on objects/startup_app.json
> +  "caption": "Startup Application",
I’d like to propose that we use Rick’s prior suggestion of “Startup Items”.  It covers the use case that was the intent of the class, and I believe is generic enough to accommodate others.  The original purpose for this event was to address discovery for application components that generally occur on Starting up a device/OS.

2024-08-20 00:27 UTC, rmouritzen-splunk submitted a review, later dismissed

2024-08-27 19:52 UTC, floydtree submitted a review, later dismissed

2024-08-27 20:50 UTC, mikeradka approved these changes

2024-08-28 18:32 UTC, mikeradka approved these changes
Thanks Max

2024-08-28 18:44 UTC, floydtree approved these changes

2024-09-03 15:56 UTC, pagbabian-splunk approved these changes

2024-09-04 14:27 UTC, merged