Add router, ids, and ips entries to type_id enum in the Endpoint object
ocsf/ocsf-schema pull request #1121
Opened 2024-06-25 16:01 UTC by zl551q

#### Related Issue: 
[1120](https://github.com/ocsf/ocsf-schema/issues/1120)

#### Description of changes:
Adds three enum type_id values to the Endpoint object:
- router
- ids
- ips

Miscellaneous: Updates grammar on the IOT entry.

I confirm that I have tested the changes, and the server run was error free.  New entries shown with server run:
![image](https://github.com/ocsf/ocsf-schema/assets/173811405/01ce99f7-2451-46ef-a8ac-cea3caf1192e)

2024-06-26 20:37 UTC, davemcatcisco requested changes

2024-06-26 20:37 UTC, davemcatcisco commented on CHANGELOG.md
> +    9. Added `router`, `ids`, and `ips` entries to `type_id` enum in the `Endpoint` object.
You should cross-reference the PR here, as done in the other entries in this list.

2024-06-26 20:37 UTC, davemcatcisco commented on objects/endpoint.json
> +          "caption": "IPS",
Is an IPS so different to an IDS that it needs to have a separate type? I'd have thought that detection is an integral part of prevention. I note too that the MITRE definition to which you linked says:
> Intrusion prevention systems (IPS), also known as intrusion detection and prevention systems (IDPS)...

This suggests to me that a single new IDPS enum value would adequately cover both, but I'm happy to defer to domain expertise if not.

2024-06-26 20:42 UTC, zl551q commented on objects/endpoint.json
> +          "caption": "IPS",
Yes and no.  I had the thought to combine them - `IDS/IPS` - but historically they are different devices.  IPS can function as IDS only, but IPS are generally in-line with traffic (e.g., running on a UTM firewall), and IDS can be devices off span ports, just getting a copy of data, without being in the traffic flow.

I'm open to the combination, though.  It's been some time since I've actively managed them myself, and most of the data I would be mapping would be IPS in nature, so perhaps IDS is more deprecated than I believe it to be.

2024-06-26 20:46 UTC, zl551q commented on CHANGELOG.md
> +    9. Added `router`, `ids`, and `ips` entries to `type_id` enum in the `Endpoint` object.
Is that possible without a subsequent commit?  I would have but didn't know the PR# prior to creating the PR, unless my lack of github knowledge is affecting me here.

2024-06-26 21:26 UTC, davemcatcisco commented on CHANGELOG.md
> +    9. Added `router`, `ids`, and `ips` entries to `type_id` enum in the `Endpoint` object.
What I usually do is create the PR without the change to CHANGELOG.md and then push a second commit containing that. By the way, assuming you are the only person working on this, you can then tidy up by squashing the two commits locally into one (see the `git rebase -i` command) and then doing a force push (see `git push --force-with-lease` command) to completely replace the previous commits.

2024-07-09 16:09 UTC, floydtree approved these changes

2024-07-09 16:11 UTC, mikeradka approved these changes

2024-07-09 16:13 UTC, zschmerber approved these changes

2024-07-09 18:24 UTC, merged