feat: [1122]-ldap and user extension + AD profile
ocsf/ocsf-schema pull request #1136
Opened 2024-07-02 08:38 UTC by PavelJurka

#### Related Issue: .
https://github.com/ocsf/ocsf-schema/issues/1122

#### Description of changes:

This issue is about adding a few useful fields to LDAP user, User object and adding a way how to map Azure ID to it.

### Delete once you have confirmed the following: 
TBD
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Is your PR title in sync with the description?

2024-07-02 15:56 UTC, Aniak5 commented on dictionary.json
> +      "type": "integer_t"
This was recently changed to a `long_t` in [this PR](https://github.com/ocsf/ocsf-schema/pull/1117). Is there a reason you are changing it back?

2024-07-02 16:01 UTC, Aniak5 commented on dictionary.json
> +      "caption": "Admin Count",
Can `is_privileged` be used here instead? This appears to be a binary indicator of whether an object is privileged or not.

2024-07-02 16:03 UTC, Aniak5 commented on objects/user.json
> +      "requirement": "recommended",
This should be added to the dictionary.

2024-07-02 16:06 UTC, Aniak5 commented on objects/user.json
> +      "description": "Indicated if the user is a privileged user"
Nit: Something like `Indicates whether the user has privileged access.` would be a bit more clear.

2024-07-02 17:01 UTC, mikeradka commented on objects/user.json
> +      "description": "Indicated if the user is a privileged user"
To piggyback here, maybe even simpler: `Indicates whether the user is privileged.`

2024-07-10 12:14 UTC, PavelJurka commented on dictionary.json
> +      "caption": "Admin Count",
@Aniak5 pushed back admin_count to be more consistent with AD specific field

2024-07-23 16:21 UTC, mikeradka requested changes

2024-07-23 16:21 UTC, mikeradka commented on dictionary.json
> +    "allowed_to_act_on_behalf_of_other_identity": {
This is a very long name. Could this be made more concise? Also should this be a boolean?

2024-07-24 07:56 UTC, PavelJurka commented on dictionary.json
> +    "allowed_to_act_on_behalf_of_other_identity": {
It's long but name and type is consistent with AD. Can we keep it? thank you!

2024-07-24 14:08 UTC, mikeradka commented on dictionary.json
> +    "allowed_to_act_on_behalf_of_other_identity": {
Do you have some examples of how this looks in AD?

We may still want to consider looking how to make this more concise, if it is possible to do so. Why not something along `act_on_behalf` or `acts_on_behalf` with the details about the indication that the account is allowed to act on behalf of another identity within the attribute's description?

2024-07-25 21:08 UTC, pagbabian-splunk commented on dictionary.json
> +    "allowed_to_act_on_behalf_of_other_identity": {
It is the native AD name.  There is an LDAP display name, and a CN name.  `adminCount` (which doesn't have an internal separator) is a LDAP display name.  `Admin-Count` is the CN name.

`msDS-Allowed-To-Act-On-Behalf-Of-Other-Identity` is the CN name and `msDSAllowedToActOnBehalfOfOtherIdentity` is the LDAP display name.

2024-08-14 17:19 UTC, pagbabian-splunk commented on dictionary.json
> +    },
We usually sort these attributes even if they are related (e.g. `is_` stays together) but not absolute.

2024-08-14 17:48 UTC, pagbabian-splunk commented on dictionary.json
> +    },
May need `ldap_` because it is a `DN` or an object.  A convention around objects like AD could be retrofitted to LDAP too (we would need to deprecate).

2024-08-14 18:15 UTC, pagbabian-splunk commented
We may need to break this PR down into a few smaller PRs - it is quite large with many new attributes, but is also very important to get right.

2024-08-14 18:44 UTC, floydtree requested changes
I echo @pagbabian-splunk's comment, these additions are much needed for the framework, but we need to break the PR down in smaller chunks. Perhaps you can target additions/enhancements to just one object at a time in a single PR. 

Other things to consider -
1. If you have sample events that you want to normalize, it will help us quite a bit to review.
2. Consider re-using existing attributes before adding new ones. (Refer to Paul's inline comments)
3. Consider all the specific [data-types](https://schema.ocsf.io/1.3.0/data_types?extensions=) as you add new attributes, instead of defaulting to `string_t`
4. Consider object creation to avoid redundancy in naming and re-usability of attributes. (e.g `on_premises_*` vs on `on_premises { * }`)
5. Consider if you can create an object to group AD specific attributes together (thinking about re-usability and portability across the framework)

@pagbabian-splunk @mikeradka @zschmerber Feel free to add, if I missed anything.

2024-08-14 18:44 UTC, floydtree commented on dictionary.json
> +    },
Also, can the caption be made clearer?

2025-07-15 16:12 UTC, zschmerber commented
should we split this into a couple of PR's and remove this one ?

2025-09-05 19:37 UTC, mikeradka commented
Closing this ticket out, as it has gone stale over a few releases and the group ultimately decided to tackle LDAP and Entra ID enhancements to OCSF in smaller downstream PRs.

2025-09-05 19:37 UTC, closed without merging