Enhancement to load_balancer object
ocsf/ocsf-schema pull request #1138
Opened 2024-07-02 22:06 UTC by pagbabian-splunk

#### Related Issue: N/A (from Slack)

#### Description of changes:
Added ip to the load_balancer object.  Added Load Balancer to the endpoint type_id enum list.

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?

2024-07-03 10:12 UTC, irakledibm approved these changes

2024-07-03 17:47 UTC, Aniak5 commented on objects/load_balancer.json
> +        "description": "The IP address of the load balancer (not the address of traffic returned through the load balancer)."
Is `not the address of traffic returned through the load balancer` trying to clarify that this is not the IP address of the device where the traffic is distributed? If so, then this might be a little clearer:

```not the IPs of the distribution endpoints```

2024-07-03 22:13 UTC, pagbabian-splunk commented on objects/load_balancer.json
> +        "description": "The IP address of the load balancer (not the address of traffic returned through the load balancer)."
It is unclear to me whether the return address to clients comes from any of the distribution endpoints, or some other `load_balancer` configured address.  Therefore I don't want to assume that the distribution endpoint addresses that are known to the LB would be returned in any situation.  I only want to say that this address is the LB address itself.

2024-07-09 14:58 UTC, floydtree commented on objects/load_balancer.json
> +        "description": "The IP address of the load balancer (not the address of traffic returned through the load balancer)."
I think we should simplify it, perhaps something on the lines of `The IP address of the load balancer node that handled the request. (Note, this is not an IP address of the target/distribution endpoint.`

2024-07-09 15:34 UTC, Aniak5 commented on objects/load_balancer.json
> +        "description": "The IP address of the load balancer (not the address of traffic returned through the load balancer)."
I like that @floydtree, it's more clear.

2024-07-10 14:56 UTC, floydtree requested changes
Updates to the description of the new attribute, as discussed in the line specific comments.

2024-07-23 14:48 UTC, pagbabian-splunk commented on objects/load_balancer.json
> +        "description": "The IP address of the load balancer (not the address of traffic returned through the load balancer)."
Ok - here is how I have updated it:
`"The IP address of the load balancer node that handled the client request (Note: this is not an address of the target/distribution endpoint - see <code>dst_endpoint</code>)."`

2024-07-23 16:18 UTC, zschmerber approved these changes

2024-07-23 16:22 UTC, floydtree submitted a review, later dismissed

2024-07-23 16:23 UTC, mikeradka approved these changes

2024-07-23 17:05 UTC, floydtree requested changes

2024-07-23 17:05 UTC, floydtree commented on CHANGELOG.md
> +    4. Added `ticket` to `Incident Finding` object. ticket. #1068
this specific entry can be deleted, it's already added to the Improved event classes section

2024-07-24 15:50 UTC, pagbabian-splunk commented on CHANGELOG.md
> +    4. Added `ticket` to `Incident Finding` object. ticket. #1068
got it - I'll fix it

2024-07-24 16:13 UTC, mikeradka approved these changes

2024-07-25 15:41 UTC, Aniak5 submitted a review, later dismissed
LGTM!

2024-07-26 18:17 UTC, mikeradka submitted a review, later dismissed

2024-07-26 18:17 UTC, zschmerber approved these changes

2024-07-26 18:18 UTC, floydtree approved these changes

2024-07-26 18:56 UTC, mikeradka approved these changes

2024-07-26 18:57 UTC, merged