Added new activity "Listen" to `Network Activity` and relax requirement of `src_endpoint`
ocsf/ocsf-schema pull request #1147
Opened 2024-07-19 18:32 UTC by mlmitch

This adds support for representing a network endpoint listening for new network connections on a network.

The listening network endpoint will always be the `dst_endpoint`, and there is no `src_endpoint` because no network connection has been established yet. Therefore `src_endpoint` is changed from required to recommended.

The rational behind using `Network Activity` is that when a data consumer asks their data set for `Network Activity`, they will probably be interested in things that are listening on the network even if there wasn't a connection established yet.
This is in contrast to needing to ask the data set for a different event type.

2024-07-22 17:53 UTC, floydtree approved these changes

2024-07-23 16:42 UTC, zschmerber approved these changes

2024-07-23 16:44 UTC, rmouritzen-splunk approved these changes

2024-07-23 17:03 UTC, merged

2024-07-23 17:04 UTC, mikeradka requested changes

2024-07-23 17:04 UTC, mikeradka commented on includes/network/network_activities.json
> +          "description": "A network endpoint began listening for new network connections."
Slight nitpick here - is the activity always the beginning of a listen, or could it also just represent that the endpoint is listening?

2024-07-23 17:07 UTC, mlmitch commented on includes/network/network_activities.json
> +          "description": "A network endpoint began listening for new network connections."
I think I see what you mean.

I wrote "began listening" because I think that is what the event is.
If it represents that an endpoint is listening, that's sort of a state rather than an event?
Also, this maybe starts to venture into "discovery" events?

What do you think?

2024-07-23 17:08 UTC, mikeradka commented on includes/network/network_activities.json
> +          "description": "A network endpoint began listening for new network connections."
That makes sense. And since it is really a nit, I think it is okay to proceed as-is.