Feat: [1148] - enrichment extension
ocsf/ocsf-schema pull request #1149
Opened 2024-07-22 12:13 UTC by PavelJurka

#### Related Issue: 

https://github.com/ocsf/ocsf-schema/issues/1148

#### Description of changes:

extending - enrichment by:

time, recommended - The timestamp when the enrichment data was generated.
desc optional - A long description of the enrichment data.
reputation optional - The reputation of the enrichment data
short_desc, recommended - A short description of the enrichment data.
url_string, recommended - The URL of the source of the enrichment data

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Is your PR title in sync with the description?

2024-07-23 07:25 UTC, PavelJurka commented
Note - ticket added to incident finding change log record pushed back.

2024-07-23 13:30 UTC, floydtree requested changes

2024-07-23 13:30 UTC, floydtree commented on CHANGELOG.md
> +    4. Added `ticket` to `Incident Finding` object. ticket. #1068
There's an entry for it [here.](https://github.com/ocsf/ocsf-schema/pull/1149/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL72)

Incident Finding is an event class, so doesn't make sense to add that entry in this section.

2024-07-24 07:56 UTC, PavelJurka commented on CHANGELOG.md
> +    4. Added `ticket` to `Incident Finding` object. ticket. #1068
oh, ok, I thought it was removed by accident;) Let me remove it. Thank you!

2024-07-24 13:17 UTC, floydtree submitted a review, later dismissed

2024-07-24 13:48 UTC, mikeradka commented on dictionary.json
> +      "description": "The sort description that pertains to the object or event. See specific usage.",
There is a minor typo here (`sort description`)

2024-07-24 13:52 UTC, mikeradka commented on objects/enrichment.json
> +    "src_url": {
Is there a reason this is of type `string` rather than a `url` object?

2024-07-24 13:54 UTC, mikeradka requested changes
Added a couple of inline comments to look at.

2024-07-24 13:56 UTC, floydtree commented on objects/enrichment.json
> +    "src_url": {
just a note, `src_url` is of type `url_t`

2024-07-24 14:01 UTC, mikeradka commented on objects/enrichment.json
> +    "src_url": {
@floydtree if simply a url strings is what we want for this attribute rather than a url object, then that is fine. Just wanted to double check. Can you confirm a string is what we want for `src_url` rather than a url object?

2024-07-25 08:02 UTC, PavelJurka commented on dictionary.json
> +      "description": "The sort description that pertains to the object or event. See specific usage.",
Thank you!

2024-07-25 14:59 UTC, floydtree commented on objects/enrichment.json
> +    "src_url": {
I'll defer to @PavelJurka about what he requires, a url string vs a url object.

2024-07-25 18:10 UTC, pagbabian-splunk commented on objects/enrichment.json
> +    "src_url": {
I'm assuming it is of type url_t not string, because `src_url` is the attribute he added, vs `url_string` if he had wanted a string.

2024-07-25 18:28 UTC, mikeradka commented on objects/enrichment.json
> +    "src_url": {
Some clarification - `url_t` is of base type string, so when viewing the `src_url` field, it says `url string`

<img width="883" alt="image" src="https://github.com/user-attachments/assets/0d92ea8e-e0bb-40e9-9355-a3a30a95ef94">

<img width="893" alt="image" src="https://github.com/user-attachments/assets/192108d2-aac8-4273-8e25-7a08ef4adf55">

Essentially what I am asking here is does the enrichment require a url object, or a url string? Are there any circumstances in the future where we would anticipate the enrichment needing a url object?

2024-07-26 19:05 UTC, mikeradka submitted a review, later dismissed

2024-07-26 19:10 UTC, mikeradka approved these changes

2024-07-29 18:21 UTC, floydtree approved these changes

2024-07-30 00:46 UTC, pagbabian-splunk approved these changes

2024-07-30 00:47 UTC, merged