Add evidences to Compliance Finding
ocsf/ocsf-schema pull request #1157
Opened 2024-08-14 07:18 UTC by lukas-krecan

When reporting Compliance Finding, we want to specify which File, API or Device caused us to trigger the finding. For example, if we have a terraform file which creates an AWS ec2 instance with public 22 port, we want to point to the file where we found the issue.

#### Description of changes:
* Add evidences to Compliance Finding

2024-08-15 17:59 UTC, mikeradka requested changes
Looks straightforward, but can you please make sure to update the CHANGELOG.md? Thanks.

2024-08-16 06:57 UTC, lukas-krecan commented
Sorry, added

2024-08-16 18:17 UTC, mikeradka commented
For this one, we should probably change the dictionary definition of `evidences` from:

- A collection of evidence artifacts associated to the activity/activities that triggered a ~~security detection~~ . to
- A collection of evidence artifacts associated to the activity/activities that triggered a finding. See specific usage.

2024-08-16 19:32 UTC, lukas-krecan commented on CHANGELOG.md
> +    3. Added `evidences` to `compliance_finding` class. #1157
Done, thanks

2024-08-22 17:13 UTC, jonrau-at-queryai commented
I feel as if `evidences` should just be a Profile instead to give flexibility across the entirety of the schema, similar to how `OSINT` is now - since any type of event could be implicated in a greater detection or case management context.

2024-08-27 15:53 UTC, floydtree requested changes

2024-08-27 15:53 UTC, floydtree commented on events/findings/compliance_finding.json
> +    "evidences": {
Since, the dictionary definition has now become more generic, we'll need to update any class specific definitions of this attribute.

In your local server run, you should be able to see warnings about it - 

```
[warning] mfa=Schema.Cache.missing_desc_warning/4 line=1177  Please update the description for compliance_finding.evidences: A collection of evidence artifacts associated to the activity/activities that triggered a finding. See specific usage.

[warning] mfa=Schema.Cache.missing_desc_warning/4 line=1177  Please update the description for detection_finding.evidences: A collection of evidence artifacts associated to the activity/activities that triggered a finding. See specific usage.


```

2024-08-27 17:43 UTC, lukas-krecan commented on events/findings/compliance_finding.json
> +    "evidences": {
Thanks, updated. I haven't expected description change to actually change anything. Learning new stuff every day.

2024-08-29 15:46 UTC, floydtree approved these changes

2024-08-29 18:02 UTC, mikeradka approved these changes

2024-08-29 18:03 UTC, jonrau-at-queryai approved these changes

2024-08-29 18:04 UTC, merged