Updated event classes, added missing categories.
ocsf/ocsf-schema pull request #1163
Opened 2024-08-20 18:03 UTC by irakledibm

#### Related Issue: 
 #1162
#### Description of changes:
Updated event classes, added missing categories. 
It is not a critical problem, since all events that were missing category were extending higher level event. All higher level events have categories specified. This update is for a consistency.

2024-08-20 18:19 UTC, mikeradka commented
This might be a silly question, but just for curiosity's sake - if a class is extending a higher-level class that already has a `category` defined, does defining the `category` more specifically in the lower-level class effectively overwrite it?

For hypothetical instance:
- `api.json` extensions `"extends": "application"`, which assigns it to the `application` category.
- If, in `api.json`, I still extend `application`, but introduce a typo such as `category: applcation`, would the category be overwritten with the typo-value?

2024-08-20 21:08 UTC, pagbabian-splunk commented
I'm not sure about this one.  Given an extended class MUST have the same category as the parent from a metaschema logical point of view, I might suggest that extended classes MUST NOT set the category, since it could result in an error (i.e. Mike's example).

2024-08-20 22:19 UTC, irakledibm commented
As I mentioned out of 70 classes 23 classes had category set, out of them only 7 are parent classes. This PR was submitted for consistency. I would agree that extending parent class would inherit a category; however I find it inconsistent when some classes include category and others don't.

2024-08-22 14:26 UTC, floydtree commented
I agree, we should be consistent in our definitions. However, I think we should do it the other way round, let's remove category definitions from all 'child' classes and only have them in the 'parent' classes. In the spirit of keeping things and lean and simple for the metaschema definitions. Thoughts? @pagbabian-splunk @mikeradka @irakledibm and others?

Mechanistically, 
@alanisaac will it possible to update the json-schema used for validation to disallow the key `category` whenever a key `extends` is used in the event class definition?

2024-08-22 15:44 UTC, zschmerber commented
I also agree.

2024-08-22 15:46 UTC, irakledibm commented
There could be a problem with validation. For example all parent classes extend base_event, and base_event category is "other". So, logic already has an exception.

Another scenario is for the future, would we allow for new classes to extend more then one parent? Is it possible to have a class that would inherit properties from lets say system and application classes at same time?

2024-08-22 16:41 UTC, irakledibm commented
Potentially another bug is found. Classes email, email_url and email_file belong to network category, however extend base_event class.

2024-08-22 16:59 UTC, irakledibm commented
PR is updated

2024-08-22 17:02 UTC, pagbabian-splunk commented
> Another scenario is for the future, would we allow for new classes to extend more then one parent? Is it possible to have a class that would inherit properties from lets say system and application classes at same time?

I would want to avoid a 'multiple inheritance' construction.  Things are already seeming complicated to newcomers, and the only reason we use the 'extends' construction is for linear constructions.  Having classes be part of more than one category would be a side effect of multiple extend parents, something that has been discussed but would need to be properly done in the framework first.

I think most of us favor better use of profiles (composition) vs. more classes and deeper inheritance.

2024-08-22 17:05 UTC, pagbabian-splunk commented on CHANGELOG.md
I think metaschema adjustments that don't affect the schema don't need to be tracked in the CHANGELOG.  In any case, now that you have removed rather than added categories to the metaschema this line would be changed, and it would fall under the Improved section rather than the Added section.  (Otherwise the substance looks good!).

2024-08-22 17:19 UTC, floydtree requested changes

2024-08-22 17:19 UTC, floydtree commented on events/application/web_resources_activity.json
As discussed in the comments of this PR, anything that extends base_event, requires the `category` key, otherwise the class will be orphaned. If you run the server against this PR, you'll see this class has disappeared.

2024-08-22 17:19 UTC, floydtree commented on events/discovery/discovery_result.json
Similar to the previous comment, category key is required here.

2024-08-22 17:19 UTC, floydtree commented on events/findings/security_finding.json
Similar to the previous comment, category key is required here.

2024-08-22 17:19 UTC, floydtree commented on CHANGELOG.md
Yep, agree a changelog entry won't be necessary, as this won't be a schema affecting change.

2024-08-22 17:41 UTC, floydtree requested changes

2024-08-22 17:41 UTC, floydtree commented on .vscode/settings.json
thanks for getting all the changes in! Just noticed this one, why are deleting it?

2024-08-22 17:53 UTC, irakledibm commented on .vscode/settings.json
It is IDE generated file from vscode. Probably was merged with one of the PRs at some point. Each IDE has some "hidden" files added.

2024-08-22 18:02 UTC, mikeradka commented on .vscode/settings.json
I could be wrong here, but i am not sure we want to delete it. I *think* this file may be related to the .vscode IDE validation for the OCSF metaschema, judging by its contents having OCSF in it:

```
{
    "json.schemas": [
        {
            "fileMatch": [
                "/**/categories.json"
            ],
            "url": "./metaschema/categories.schema.json"
        },
        {
            "fileMatch": [
                "/**/dictionary.json"
            ],
            "url": "./metaschema/dictionary.schema.json"
        },
        {
            "fileMatch": [
                "/**/extension.json"
            ],
            "url": "./metaschema/extension.schema.json"
        },
        {
            "fileMatch": [
                "/events/**/*.json"
...
```

I think this may have been purposely added, as I believe it helps VSCode to underline schema validation issues. @alanisaac , could you confirm this?

2024-08-22 18:02 UTC, floydtree commented on .vscode/settings.json
Not this one, this helps your vscode instance do a local validation(json-schema based) of the schema definition files.  You can view the metaschema validation files in /metaschema dir

2024-08-22 18:08 UTC, irakledibm commented on .vscode/settings.json
Ok, I will bring it back

2024-08-22 18:20 UTC, floydtree approved these changes

2024-08-22 20:49 UTC, mikeradka approved these changes
Looks good

2024-08-22 21:02 UTC, rmouritzen-splunk commented
> and base_event category is "other".

Note that the `other` category is _not_ defined in the schema. It is a special-case that the schema compiler needs to handle. (Which is annoying to me.) 

Fix it could be possible, though to avoid a breaking change the `caption` of the `other` category would need to be "Uncategorized", plus this new category would show up in the schema browser and compiled schema with a single member: `base_event`. 

And even if we added the `other` category, we would have the special-case raised here, though in this case it may be occurring because `base_event` is both a concrete class and a base class for other classes. I don't know if this happens in other event class inheritance hierarchies, but it certainly could.

2024-08-22 22:04 UTC, rmouritzen-splunk approved these changes
Aside from my comment (which isn't immediately actionable anyway), this PR looks good.

2024-08-23 12:55 UTC, merged