Eliminated includes directory and associated metaschema
ocsf/ocsf-schema pull request #1171
Opened 2024-09-05 18:55 UTC by alanisaac

#### Related Issue: 
#1170 

#### Description of changes:
Following on from https://github.com/ocsf/ocsf-schema/pull/1167, this PR removes the `includes/` folder and the associated `include` metaschema.

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Is your PR title in sync with the description?

2024-09-06 14:06 UTC, floydtree requested changes
Looks good, just a minor inline comment about the changelog entry.

2024-09-06 14:06 UTC, floydtree commented on CHANGELOG.md
> +7. Eliminated `includes` directory and associated metaschema. #1171
Entry 5 talks about the same change. Perhaps, only include this PR number in that entry?

2024-09-12 13:34 UTC, alanisaac commented on CHANGELOG.md
> +7. Eliminated `includes` directory and associated metaschema. #1171
fixed in [ad0f7ba](https://github.com/ocsf/ocsf-schema/pull/1171/commits/ad0f7ba7e97168d2d9e280a661fc4e3da729d234)

2024-09-12 13:54 UTC, floydtree approved these changes

2024-09-12 15:43 UTC, mikeradka approved these changes

2024-09-12 18:12 UTC, zschmerber approved these changes

2024-09-12 18:14 UTC, merged