Added the is_detection flag to the dictionary, the security_conttrol …
ocsf/ocsf-schema pull request #1178
Opened 2024-09-13 21:56 UTC by pagbabian-splunk

…profile, and the detection_finding class.

#### Related Issue: 1177

#### Description of changes:
Added an attribute, `is_detection` that indicates that an event is a security alert or detection finding, either determined by a security product monitoring activies, via the `Security Control` profile, or by an analytic process on one or more events via the `Detection Finding` class.

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?

2024-09-15 22:45 UTC, irakledibm commented
What is the purpose of this flag? Isn't a security alert a result of the detection?

2024-09-16 15:57 UTC, pagbabian-splunk commented
Yes, it is.  However there are two ways to model an 'alert' or detection, yet there was the assumption that there was only Detection Finding (which was added post 1.0).  Originally security alerts were modeled by combining Security Control profile with the associated Activity event that was being monitored by the security control product.  Those are the typical alerts coming from firewalls and AV products.  Findings were the result of known analytics, usually coming from a SIEM or UBA type of product, and often analyzing multipile events.

The purpose of this flag `is_detection` is to tie the two types of detections together from a query perspective.  All Detection Findings are detections, and most but not all Security Control activities are detections.  This is because Security Control was expanded to apply to access control activities, starting with its applications to Web Resource Activity.  Not all 'Actions' of Allowed or Denied would constitute detections.

This came up via a Slack question, on how to model alerts from Suricata, followed by some assumptions that all alerts (not just network alerts) needed to be Detection Findings (due to the name possibly).  I will make this a topic for this week.

2024-09-16 16:57 UTC, irakledibm commented
It could be determined from related_analytics and data_sources, however I guess there is no harm in having a flag.

2024-09-17 16:07 UTC, floydtree requested changes

2024-09-17 16:07 UTC, floydtree commented on dictionary.json
Looks like it is undoing the changes that we merged in related to the data-types. Perhaps a pull and then an edit to the file will help.

2024-09-25 20:07 UTC, irakledibm submitted a review, later dismissed

2024-09-26 23:37 UTC, pagbabian-splunk commented on dictionary.json
Yes, that's what I did, thanks.

2024-09-27 00:43 UTC, mikeradka approved these changes

2024-09-27 01:08 UTC, irakledibm approved these changes
lgfm

2024-09-27 02:25 UTC, mikeradka approved these changes

2024-09-27 12:21 UTC, Aniak5 approved these changes
Great additions!

2024-09-27 13:23 UTC, floydtree requested changes

2024-09-27 13:23 UTC, floydtree commented on events/findings/detection_finding.json
> +    "is_alert": {
I think we should provide clarification and/or guidance via an overridden description for this field, particularly how and when to populate it in this class. I suspect, this will be a point of confusion for producers and mappers alike. In the scope of a `Detection Finding`, what does it mean if it's not populated or populated as `false`? Additionally, what special meaning does it add to the detection finding when it's populated as `true`

2024-09-27 16:15 UTC, pagbabian-splunk commented on events/findings/detection_finding.json
> +    "is_alert": {
Yes, I think that would be good.  I'll update the description(s) - either now, or in a quick followup if you resolve this conversation first.

2024-09-27 16:29 UTC, pagbabian-splunk commented on events/findings/detection_finding.json
> +    "is_alert": {
Here is some proposed wording for `detection_finding`:

Indicates that the event is considered to be an alertable signal. For example, an activity_id of 'Create' could constitute an alertable signal and the value would be true, while 'Close' likely would not and either omit the attribute or set its value to false. Note that other events with the security_control profile may also be deemed alertable signals and may also carry is_alert = true attributes.
--
Category ID

2024-09-27 18:45 UTC, floydtree commented
I resolved this [conversation](https://github.com/ocsf/ocsf-schema/pull/1178#discussion_r1778626412), in favor of a quick followup PR to update the description of `is_alert` in detection finding class. Everything else in this PR looks great.

2024-09-27 18:45 UTC, floydtree approved these changes

2024-09-27 18:45 UTC, merged