Updating hostname_t regex, other minor formatting changes
ocsf/ocsf-schema pull request #1182
Opened 2024-09-25 14:45 UTC by floydtree

#### Related Issue: 
Current hostname_t regex, doesn't allow fqdns. However, hostname_t is used by attributes which can and will represent fqdns in the dataset. (`dns_query.hostname`). 

#### Description of changes:
1. Updating hostname_t regex to reflect FQDNs. (https://regexr.com/3g5j0)
2. Minor formatting consistency updates

2024-09-25 14:56 UTC, mikeradka approved these changes

2024-09-25 14:59 UTC, Aniak5 submitted a review, later dismissed
LGTM

2024-09-25 18:37 UTC, mikeradka requested changes
I'm going to go back on this one. The more I think about this, it is not uncommon for the value of a `hostname` field to contain ONLY a hostname, such as `myhost`. Or further, a netbios name, such as `MYDOMAIN/myhost`. The new regex does not support either of these values. Along with this, IPv4/IPv6 can often make it as values, and the old expression did except IPv4. Wouldn't we consider this to be breaking?

2024-09-25 19:13 UTC, rmouritzen-splunk requested changes

2024-09-25 19:13 UTC, rmouritzen-splunk commented on dictionary.json
> +        "regex": "^(?!:\\/\\/)(?=.{1,255}$)((.{1,63}\\.){1,127}(?![0-9]*$)[a-z0-9-]+\\.?)$",
Not to pile one, but this should support all of the following:
* Hostname without domain, e.g., `example`
* FQDN, e.g., `www.example.com`
* IPv4, e.g., `192.168.0.1`
* IPv6 in all its representations, examples: `2001:0db8:0000:0000:0000:ff00:0042:8329`, `2001:db8:0:0:0:ff00:42:8329`, `2001:db8::ff00:42:8329`, and `::1`
* Windows NetBIOS names (I couldn't find a good source for this online)
* Windows DNS domain names (as usual, Windows does its own thing; specifically Windows DNS supports Unicode in names, not just ASCII)

OS APIs and clients like web browsers allow quite a wide range for hostnames, and those (probably) end up in the source raw logs.

This seems quite broad. IMHO, I'd would _not_ include a regex in this case. OCSF should accept whatever the original source considers a hostname.

Finally, it seems clear the `hostname_t` is meant to capture hostname and IP addresses since the original accepted IPv4 addresses, and IP addresses are _not_ legal domain names. (The current regex does not accept IPv6 addresses, however that seems like an oversight.)

2024-09-25 19:15 UTC, floydtree commented
> I'm going to go back on this one. The more I think about this, it is not uncommon for the value of a `hostname` field to contain ONLY a hostname, such as `myhost`. Or further, a netbios name, such as `MYDOMAIN/myhost`. The new regex does not support either of these values. Along with this, IPv4/IPv6 can often make it as values, and the old expression did except IPv4. Wouldn't we consider this to be breaking?

About making it flexible to allow just hostnames without a FQDN, agree I'll update the regex to account for those since we are using the same attribute for both use-cases.

However, about allowing IPv4 and v6, I am hesitant about these, even if the old regex allowed IPv4 as hostnames, was it correct or was it a bug? Why would we allow IPs as hostnames?

2024-09-25 19:30 UTC, floydtree commented on dictionary.json
> +        "regex": "^(?!:\\/\\/)(?=.{1,255}$)((.{1,63}\\.){1,127}(?![0-9]*$)[a-z0-9-]+\\.?)$",
Agree that, building a cover-it-all regex for hostname would be quite infeasible, considering the lack of general agreement about what constitutes a hostname. I would be okay to open it up.

About hostname_t allowing IP Addresses seems like a mistake to me, unless I am missing one of the dozen RFCs.

2024-09-25 22:00 UTC, rmouritzen-splunk commented on dictionary.json
> +        "regex": "^(?!:\\/\\/)(?=.{1,255}$)((.{1,63}\\.){1,127}(?![0-9]*$)[a-z0-9-]+\\.?)$",
As a real-world example, syslog headers can contain IP addresses its hostname field.

> The HOSTNAME field will contain only the hostname, the IPv4 address, or the IPv6 address of the originator of the message.

https://www.rfc-editor.org/rfc/rfc3164#section-4.1.2

> In practice, not all syslog applications are able to provide an FQDN. As such, other values MAY also be present in HOSTNAME.  This document makes provisions for using other values in such situations.  A syslog application SHOULD provide the most specific available value first. The order of preference for the contents of the HOSTNAME field is as follows:
>
>   1.  FQDN
>
>   2.  Static IP address
>
>   3.  hostname
>
>   4.  Dynamic IP address
>
>   5.  the NILVALUE

https://www.rfc-editor.org/rfc/rfc5424#section-6.2.4

2024-09-26 13:11 UTC, floydtree commented on dictionary.json
> +        "regex": "^(?!:\\/\\/)(?=.{1,255}$)((.{1,63}\\.){1,127}(?![0-9]*$)[a-z0-9-]+\\.?)$",
That's the syslog protocol's RFC, but yeah proves the point. The implementation of hostname is quite varied. I am gonna remove the regex for hostname_t with a new commit.

2024-09-26 18:36 UTC, rmouritzen-splunk approved these changes

2024-09-27 00:45 UTC, mikeradka approved these changes
Looks great

2024-09-27 14:00 UTC, Aniak5 approved these changes

2024-09-27 14:01 UTC, merged