Removed constraint from group_management
ocsf/ocsf-schema pull request #1193
Opened 2024-10-04 19:07 UTC by pagbabian-splunk

#### Related Issue:  N/A (Slack discussion)

#### Description of changes:
The `Group Management` class had an unnecessary restriction to populate either `user` or `privileges`.  This is too stringent for the case where the group is created or deleted where no users or privileges are known or relevant.  Therefore the PR removes the constraint.

2024-10-04 19:13 UTC, floydtree requested changes

2024-10-04 19:13 UTC, floydtree commented on CHANGELOG.md
> +    4. Removed constraint from `group_management` class
minor: just need to add the PR number to this entry

2024-10-04 22:31 UTC, pagbabian-splunk commented on CHANGELOG.md
> +    4. Removed constraint from `group_management` class
Done.

2024-10-07 12:23 UTC, alanisaac approved these changes

2024-10-07 14:32 UTC, floydtree approved these changes

2024-10-08 16:59 UTC, zschmerber approved these changes

2024-10-08 16:59 UTC, merged

2024-10-08 16:59 UTC, Aniak5 approved these changes
LGTM!