Add is_deleted to the file object
ocsf/ocsf-schema pull request #1196
Opened 2024-10-07 23:41 UTC by antchan2

#### Related Issue: 
https://github.com/ocsf/ocsf-schema/issues/1192

#### Description of changes:

Adds optional `is_deleted` field to the file object, with type `boolean_t`.

<img width="1349" alt="add_deleted_screenshot" src="https://github.com/user-attachments/assets/5f0fd230-1989-4cc3-910e-9039624032ed">

2024-10-08 22:29 UTC, irakledibm submitted a review, later dismissed
lgfm

2024-10-09 12:37 UTC, mikeradka submitted a review, later dismissed

2024-10-09 14:34 UTC, jonrau-at-queryai submitted a review, later dismissed
LGTM

2024-10-10 23:32 UTC, antchan2 commented
Fixed CHANGELOG merge conflict in [90bebba](https://github.com/ocsf/ocsf-schema/pull/1196/commits/90bebba82dd49b6843c749950739cb472b24101d).

2024-10-10 23:41 UTC, jonrau-at-queryai submitted a review, later dismissed

2024-10-11 13:13 UTC, floydtree approved these changes

2024-10-11 13:18 UTC, floydtree requested changes

2024-10-11 13:18 UTC, floydtree commented on dictionary.json
Ah, realized after approving, but thinking of resuability of `is_deleted` it would be good to keep the dictionary description more general, and adding the specific description in the file object. Something like - 
In the dictionary - 
`Indicates if the entity was deleted. See specific usage.`
In the file object - 
`Indicates if the file was deleted from the filesystem.`

2024-10-11 14:34 UTC, antchan2 commented on dictionary.json
That is a good suggestion. Changed in [29587a7](https://github.com/ocsf/ocsf-schema/pull/1196/commits/29587a7b08065232b809fd958ba52ef361e2f047).

2024-10-11 14:55 UTC, jonrau-at-queryai approved these changes

2024-10-11 15:18 UTC, irakledibm approved these changes

2024-10-14 12:39 UTC, mikeradka approved these changes

2024-10-14 12:39 UTC, merged