Fix http activity
ocsf/ocsf-schema pull request #1200
Opened 2024-10-15 02:16 UTC by zschmerber

#### Related Issue: 

#### Description of changes:

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Is your PR title in sync with the description?

2024-10-15 23:30 UTC, pagbabian-splunk submitted a review, later dismissed

2024-10-15 23:30 UTC, pagbabian-splunk commented on CHANGELOG.md
> +    10. Added `body_length` as an `integer_t`
minor: should have the PR # 1200 here too.

2024-10-16 13:46 UTC, floydtree requested changes

2024-10-16 13:46 UTC, floydtree commented on CHANGELOG.md
> +    10. Added `body_length` as an `integer_t`
@zschmerber you would anyhow need to fix the merge conflicts in this file before we can proceed. Would be good to fix this specific minor miss, along with that.

2024-10-16 15:17 UTC, jonrau-at-queryai approved these changes

2024-10-16 15:20 UTC, floydtree approved these changes

2024-10-16 16:32 UTC, Aniak5 approved these changes
LGTM!

2024-10-16 16:32 UTC, merged