Add ontology anchor to metaschema
ocsf/ocsf-schema pull request #1220
Opened 2024-10-23 18:00 UTC by netfl0

#### Related Issue: 
https://github.com/ocsf/ocsf-schema/issues/1218

#### Description of changes:

Additional new metaschema ontology object and updates to other schema elements.

2024-10-29 15:46 UTC, floydtree requested changes

2024-10-29 15:46 UTC, floydtree commented on metaschema/ontology.schema.json
> +    "$id": "https://schema.ocsf.io/references.schema.json",
copy-paste error in the $id value.

2024-10-29 15:46 UTC, floydtree commented on metaschema/ontology.schema.json
> +    "description": "Concept definition and anchor to D3FEND cybersecurity ontology. This enables grounding of OCSF concepts into D3FEND Ontology classes, object properties, and data properties.",
Great to see that we are moving towards a stronger relation between D3FEND and OCSF. 

My question here is, do we need a wholly separate metaschema attribute **dedicated** to represent the referential correlation between OCSF and D3FEND entities? 
We recently added `source` & `references` as metaschema attributes to tie in non-OCSF-native entities together. Can we not utilize these instead? I am guessing, `references` would be a better fit amongst the two.

The key concerns/questions I have with this is, 

1. A generic word such as `Ontology` being tied down to a specific entity like D3FEND.
2. Are all the keys you define within absolutely necessary to portray the relation? Would a URL (`references`) to the D3FEND entity not suffice? Thinking about the end-user, a schema viewer's experience. I would prefer keeping the "references" experience clean and consistent across the board.

2024-10-29 22:24 UTC, netfl0 commented on metaschema/ontology.schema.json
> +    "description": "Concept definition and anchor to D3FEND cybersecurity ontology. This enables grounding of OCSF concepts into D3FEND Ontology classes, object properties, and data properties.",
I tried to explain the rationale for the approach here https://github.com/ocsf/ocsf-schema/issues/1218

I was making the case that an anchor to the ontology project should be something unique versus generic references. Specifically, we'd like to establish technical compatibility between the two projects at a deep level. I am happy to discuss further as well.

2025-01-22 17:22 UTC, pagbabian-splunk commented
The approach outlined here is superseded by the `references` meta schema keyword which has been used for all d3fend cross-references that are defined.

2025-01-22 17:22 UTC, closed without merging