Fix section ordering and missing entry in changelog
ocsf/ocsf-schema pull request #1230
Opened 2024-10-30 15:44 UTC by antchan2

#### Related Issue: 

N/A

#### Description of changes:

Fix two minor issues I noticed with the change-log after the [latest update](https://github.com/ocsf/ocsf-schema/commit/8d86a98f7ea225736e42843e774c21002943d86a):
1. The Unreleased Misc. section missed a recently added line:

<img width="937" alt="image" src="https://github.com/user-attachments/assets/5fb0b15d-8ff6-4553-a6d9-9c4ef86eea0b">

2. The "Bugfixes" section somehow got moved in side the "Improved" section, resulting in incorrect indent and formatting.  In 1.3.0, Bugfixes follow Improved Profiles:

<img width="849" alt="image" src="https://github.com/user-attachments/assets/96f1dc4b-9116-428d-b382-689b93058473">

But in Unreleased, the order was reversed:

<img width="886" alt="image" src="https://github.com/user-attachments/assets/3336749e-654b-4e99-b896-ecd38c06ed9f">

2024-10-30 15:47 UTC, floydtree requested changes

2024-10-30 15:47 UTC, floydtree commented on CHANGELOG.md
> +1. Added `http_request` and `http_response` to the evidences object. #1212
This is a duplicate entry, look at line 108. Was fixed earlier, but got brought back in an overriding PR.

2024-10-30 15:49 UTC, antchan2 commented on CHANGELOG.md
> +1. Added `http_request` and `http_response` to the evidences object. #1212
Fixed in 05e7fa7

2024-10-30 15:49 UTC, floydtree commented on CHANGELOG.md
> +1. Added `http_request` and `http_response` to the evidences object. #1212
thank you!

2024-10-30 15:51 UTC, floydtree approved these changes
Just need to update the PR description to reflect the now-removed changes.

2024-10-30 15:52 UTC, antchan2 commented
I've updated the PR title and description accordingly.

2024-10-30 16:25 UTC, jonrau-at-queryai approved these changes
Nice 👍

2024-10-31 22:04 UTC, rmouritzen-splunk approved these changes

2024-10-31 22:04 UTC, merged