D3fend reference links moved to new references meta data fields.
ocsf/ocsf-schema pull request #1231
Opened 2024-10-30 21:12 UTC by pagbabian-splunk

#### Related Issue: N/A

#### Description of changes:
Updated existing MITRE d3fend references in descriptions to use the new `references` meta data tag field.
Removed the d3fend reference to d3f:PhysicalLocation from `location` as it was removed.
Updated the `country` attribute to use new `references` meta data tag field.

2024-10-31 22:35 UTC, rmouritzen-splunk requested changes
Found various minor typos, some of which are from before this PR.

2024-10-31 22:35 UTC, rmouritzen-splunk commented on dictionary.json
> +      "references": [{"url": "https://d3fend.mitre.org/dao/artifact/d3f:SoftwarePackage/", "description": "D3FEND Ontology d3f:SoftwarePackage."}],
```suggestion
      "references": [{"url": "https://d3fend.mitre.org/dao/artifact/d3f:SoftwarePackage/", "description": "D3FEND™ Ontology d3f:SoftwarePackage."}],
```
Add TM mark.

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3f_technique.json
> +  "description": "The MITRE DEFEND™ Technique object describes the leaf defensive technique ID and/or name associated to a countermeasure.",
```suggestion
  "description": "The MITRE D3FEND™ Technique object describes the leaf defensive technique ID and/or name associated to a countermeasure.",
```
Should be "D3FEND" (not "DEFEND").

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3f_technique.json
> +  "description": "The MITRE DEFEND™ Technique object describes the leaf defensive technique ID and/or name associated to a countermeasure.",
```suggestion
  "description": "The MITRE D3FEND™ Technique object describes the leaf defensive technique ID and/or name associated to a countermeasure.",
```
Should be "D3FEND" (not "DEFEND").

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3f_technique.json
> +  "references": [{"url": "href='https://d3fend.mitre.org", "description": "DEFEND™ Matrix"}],
```suggestion
  "references": [{"url": "href='https://d3fend.mitre.org", "description": "D3FEND™ Matrix"}],
```
Should be "D3FEND" (not "DEFEND").

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3f_technique.json
> +      "references": [{"url": "https://d3fend.mitre.org", "description": "DEFEND™ Matrix"}]
```suggestion
      "references": [{"url": "https://d3fend.mitre.org", "description": "D3FEND™ Matrix"}]
```
Should be "D3FEND" (not "DEFEND").

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3f_technique.json
> +      "references": [{"url": "https://d3fend.mitre.org", "description": "DEFEND™ Matrix"}]
```suggestion
      "references": [{"url": "https://d3fend.mitre.org", "description": "D3FEND™ Matrix"}]
```
Should be "D3FEND" (not "DEFEND").

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3f_technique.json
> +      "references": [{"url": "https://d3fend.mitre.org", "description": "DEFEND™ Matrix"}],
```suggestion
      "references": [{"url": "https://d3fend.mitre.org", "description": "D3FEND™ Matrix"}],
```
Should be "D3FEND" (not "DEFEND").

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3f_technique.json
> +      "references": [{"url": "https://d3fend.mitre.org", "description": "DEFEND™ Matrix"}]
```suggestion
      "references": [{"url": "https://d3fend.mitre.org", "description": "D3FEND™ Matrix"}]
```
Should be "D3FEND" (not "DEFEND").

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/d3fend.json
> +        "description": "The D3FEND<sup>TM</sup> Matrix version.",
```suggestion
        "description": "The D3FEND™ Matrix version.",
```
Change to TM character instead of HTML version (for consistency).

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/image.json
> +  "references": [{"url": "https://d3fend.mitre.org/dao/artifact/d3f:ContainerImage/", "description": "D3FEND Ontology d3f:ContainerImage"}],
```suggestion
  "references": [{"url": "https://d3fend.mitre.org/dao/artifact/d3f:ContainerImage/", "description": "D3FEND™ Ontology d3f:ContainerImage"}],
```
Add TM mark.

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/kernel_driver.json
> +  "references": [{"url": "https://d3fend.mitre.org/dao/artifact/d3f:KernelModule/", "description": "D3FEND Ontology d3f:KernelModule"}],
```suggestion
  "references": [{"url": "https://d3fend.mitre.org/dao/artifact/d3f:KernelModule/", "description": "D3FEND™ Ontology d3f:KernelModule"}],
```
Add TM mark.

2024-10-31 22:35 UTC, rmouritzen-splunk commented on objects/url.json
> +  "description": "The Uniform Resource Locator(URL) object describes the characteristics of a URL.",
```suggestion
  "description": "The Uniform Resource Locator (URL) object describes the characteristics of a URL.",
```
Add missing space between "Locator" and "(URL)".

2024-10-31 23:31 UTC, pagbabian-splunk reviewed
Thanks Rick for the fixes.

2024-10-31 23:33 UTC, rmouritzen-splunk approved these changes

2024-11-01 23:44 UTC, irakledibm approved these changes
lgfm

2024-11-19 16:57 UTC, mikeradka approved these changes

2024-11-19 16:59 UTC, merged