Identity Provider object additions, create SCIM object
ocsf/ocsf-schema pull request #1239
Opened 2024-11-01 02:07 UTC by jonrau-at-queryai

#### Description of changes:

Improves the Identity Provider (`idp`) Object by expanding greatly on its remit and original two attributes, seemingly this was made only for support mapping of CloudTrail logs, now the IDP object can be used to describe a multitude of configurations related to IDPs and their configurations such as those in AWS (Identity Center), Google Workspace, Salesforce, and more.

- Creates a new `scim` Object to represent System for Cross-domain Identity Management (SCIM) resource configurations as part of an IDP
- Adds 4 new dictionary attributes that are SCIM-specific, see CHANGELOG for more details.
- Adds several new attributes to the `idp` Object to reflect details that can be programmatically retrieved via APIs or details that are expressed in logs from a variety of tools
- Fixes formatting for several descriptions, replace single quotes with <code> tags where appropriate

And yes, I ran the server this time 🎃

2024-11-03 02:50 UTC, query-jeremy approved these changes

2024-11-07 21:15 UTC, zschmerber reviewed
looks good just have one question

2024-11-07 21:15 UTC, zschmerber commented on dictionary.json
> +    "sso_metadata_url": {
To keep it similar do we want `metadata_endpoint`?

2024-11-07 21:28 UTC, jonrau-at-queryai commented on dictionary.json
> +    "sso_metadata_url": {
good point I'll change that ish

2024-11-08 15:40 UTC, floydtree requested changes

2024-11-08 15:40 UTC, floydtree commented on CHANGELOG.md
> +    1. Added `altitude_ceiling`, `altitude_floor`, `geodetic_altitude`, `aerial_height`, `horizontal_accuracy`, `pressure_altitude`, `radius`, `speed`, `track_direction`, and `vertical_speed` all to
duplicate entry

2024-11-08 15:40 UTC, floydtree commented on objects/idp.json
> +  },
you don't need to define the constraints here, as these will be inherited from `_entity`

2024-11-08 15:40 UTC, floydtree commented on objects/scim.json
> +      "scim_group_provisioning_enabled": {
for all the new scim_* attributes, do you think we can avoid redundancy in the naming? `scim.scim_group_schema`  vs `scim.group_schema`? 

Would allow for attribute re-usability down the road as well. If you go that route, just add generic descriptions in the dict, and more specific ones here in the object

2024-11-08 15:40 UTC, floydtree commented on objects/sso.json
> +      "sso_idle_timeout": {
similar comment as `scim_*` attributes.

2024-11-13 16:04 UTC, floydtree submitted a review, later dismissed

2024-11-13 16:04 UTC, floydtree commented on dictionary.json
> +      "description": "URL where metadata about is available (e.g., for SAML configurations). See specific usage.",
nit in desc, metadata about?

2024-11-13 16:04 UTC, floydtree commented on dictionary.json
> +    "group_provisioning_enabled": {
`is_group_provisioning_enabled` for consistency with other booleans

2024-11-13 16:04 UTC, floydtree commented on dictionary.json
> +    "user_provisioning_enabled": {
same as the other boolean comment,

`is_user_provisioning_enabled`

2024-11-13 16:09 UTC, floydtree approved these changes
Noice! Thank you

2024-11-13 18:12 UTC, mikeradka approved these changes

2024-11-13 18:18 UTC, merged