Expanded Application Lifecycle Schema (Class 6002)
ocsf/ocsf-schema pull request #1241
Opened 2024-11-04 19:44 UTC by pladamgregory

---

## Proposal: Expanded Application Lifecycle Schema (Class 6002)

**Description**: This proposal introduces additional activities and attributes to the Application Lifecycle (Class 6002) schema. The goal is to enhance this class by covering operational metrics, configuration changes, data access, and user activities.

### Application Lifecycle [6002] Class
**Category**: Application Activity  
Application Lifecycle events capture installation, removal, start, stop, and other essential activities related to an application's operation and lifecycle.

---

### Updated Activity IDs

### Activity ID

    "activity_id": {
      "requirement": "required",
      "enum": {
        "1": {
          "caption": "Install",
          "description": "Install the application."
        },
        "2": {
          "caption": "Remove",
          "description": "Remove the application."
        },
        "3": {
          "caption": "Start",
          "description": "Start the application."
        },
        "4": {
          "caption": "Stop",
          "description": "Stop the application."
        },
        "5": {
          "caption": "Restart",
          "description": "Restart the application."
        },
        "6": {
          "caption": "Enable",
          "description": "Enable the application."
        },
        "7": {
          "caption": "Disable",
          "description": "Disable the application."
        },
        "8": {
          "caption": "Update",
          "description": "Update the application."
        },
        "9": {
          "caption": "Create",
          "description": "Create a configuration or setting within an application."
        },
        "10": {
          "caption": "Delete",
          "description": "Delete a configuration or setting within an application."
        },
        "11": {
          "caption": "Backup",
          "description": "Backup the application."
        },
        "12": {
          "caption": "Recover",
          "description": "Recover from an application backup."
        },
        "13": {
          "caption": "User_Activity",
          "description": "Logs actions taken by users, such as logins and feature use."
        },
        "14": {
          "caption": "Data_Access",
          "description": "Tracks access to data, including read operations."
        },
        "15": {
          "caption": "Session",
          "description": "Records details about user sessions, including duration and type."
        },
        "16": {
          "caption": "Transaction",
          "description": "Logs the start, checkpoints, and end of complex transactions."
        },
        "17": {
          "caption": "Notification",
          "description": "Tracks alerts and notifications sent by the system."
        },
        "18": {
          "caption": "Error",
          "description": "Logs a significant error that occurs within a process or service."
        },
        "19": {
          "caption": "Retry",
          "description": "Attempts to re-execute a failed action due to temporary issues."
        },
        "20": {
          "caption": "Debug",
          "description": "Captures detailed logs for troubleshooting issues within the system."
        },
        "21": {
          "caption": "Metric",
          "description": "Tracks performance metrics."
        }
      }
    },

---

### New `trace_info` Object & Profile

**Trace Object**: Defines key application Trace Information for trace events. (Included Via `trace` profile)

    "trace": {
      "caption": "Trace",
      "description": "The attributes associated with an event containing trace data. See specific usage.",
      "type": "trace"
    },
    "trace_id": {
      "caption": "Trace",
      "description": "The unique identifier used in distributed systems and microservices architecture to track and correlate requests across various components of an application.",
      "type": "string_t"
    },
    "span_id": {
      "caption": "Trace",
      "description": "The unique identifier representing a single operation or unit of work within a trace.",
      "type": "string_t"
    },
    "trace_type": {
      "caption": "Trace Type",
      "description": "The trace type, as defined by the spac_type_id.",
      "type": "string_t"
    },
    "trace_type_id": {
      "caption": "Trace Type",
      "description": "Spans represent specific operations in and between systems and is defined by https://opentelemetry.io/docs/specs/semconv/general/trace/.",
      "sibling": "span_type",
      "type": "integer_t",
      "enum": {
        "0": {
          "caption": "Unknown",
          "description": "The span_type is unknown."
        },
        "1": {
          "caption": "general",
          "description": "General Semantic Conventions."
        },
        "2": {
          "caption": "cloud_providers",
          "description": "Semantic Conventions for cloud providers libraries."
        },
        "3": {
          "caption": "cloud_events",
          "description": "Semantic Conventions for the CloudEvents specification."
        },
        "4": {
          "caption": "database",
          "description": "Semantic Conventions for database operations."
        },
        "5": {
          "caption": "exceptions",
          "description": "Semantic Conventions for exceptions."
        },
        "6": {
          "caption": "faas",
          "description": "Semantic Conventions for Function as a Service (FaaS) operations."
        },
        "7": {
          "caption": "feature_flags",
          "description": "Semantic Conventions for feature flag evaluations."
        },
        "8": {
          "caption": "generative_ai",
          "description": "Semantic Conventions for generative AI (LLM, etc.) operations."
        },
        "9": {
          "caption": "graph_ql",
          "description": "Semantic Conventions for GraphQL implementations."
        },
        "10": {
          "caption": "http",
          "description": "Semantic Conventions for HTTP client and server operations."
        },
        "11": {
          "caption": "messaging",
          "description": "Semantic Conventions for messaging operations and systems."
        },
        "12": {
          "caption": "object_stores",
          "description": "Semantic Conventions for object stores operations."
        },
        "13": {
          "caption": "rpc",
          "description": "Semantic Conventions for RPC client and server operations."
        },
        "14": {
          "caption": "System",
          "description": "System Semantic Conventions."
        },
        "99": {
          "caption": "Other",
          "description": "The event span_type is not mapped. See the <code>status</code> attribute, which contains a data source specific value."
        }
      }
    },
---

## Updated `metric` Object & Profile

**Metric Object**: Defines key application Metric Information for metric events. (Included Via `metric` profile)

    "metric_type": {
      "caption": "Metric Type",
      "description": "The metric type, as defined by the metric_type_id.",
      "type": "string_t"
    },
    "metric_type_id": {
      "caption": "Metric Type",
      "description": "Metric type represent specific type of metric asociated with a metric value as defined by defined by the types in https://opentelemetry.io/docs/specs/semconv/general/trace/.",
      "sibling": "metric_type",
      "type": "integer_t",
      "enum": {
        "0": {
          "caption": "Unknown",
          "description": "The metric type is unknown."
        },
        "1": {
          "caption": "db_client_operation_duration",
          "description": "Duration of database client operations."
        },
        "2": {
          "caption": "db_client_connection_count",
          "description": "Total count of database client connections."
        },
        "3": {
          "caption": "db_client_connection_idle_max",
          "description": "Max [...]

2024-11-04 20:12 UTC, floydtree requested changes

2024-11-04 20:12 UTC, floydtree commented on objects/cvss.json
> +    "metric": {
From a quick glance, attributes can not be changed like this, this will lead to a breaking change.

2024-11-04 20:41 UTC, pladamgregory commented on objects/cvss.json
> +    "metric": {
reverted the attribute naming back to prevent breaking.

2024-11-04 21:10 UTC, jonrau-at-queryai requested changes
Looks good overall. Some feedback to keep the dictionary a bit shorter, some feedback on descriptions, and expanding on `trace` a bit to be inclusive of other attributes outside of OTEL

2024-11-04 21:10 UTC, jonrau-at-queryai commented on dictionary.json
> +    "metric_type_id": {
You can use `type_id` within `metric` and override the enums with these to avoid making two new Dictionary entires.

2024-11-04 21:10 UTC, jonrau-at-queryai commented on dictionary.json
> +    "otel_attributes": {
nit: define the acronym in the description

2024-11-04 21:10 UTC, jonrau-at-queryai commented on dictionary.json
> +    "trace_type_id": {
Same comment as `metric_type_id`. You can use `type_id` in `trace` and override the enums.

2024-11-04 21:10 UTC, jonrau-at-queryai commented on events/application/application_lifecycle.json
>      "$include": [
This is good. You should add it to other places you may think it makes sense. Some of the `network_activity` Events come to mind (if not all of them minus the emails)

2024-11-04 21:10 UTC, jonrau-at-queryai commented on objects/cvss.json
> +      "is_array": true
Since this is used in a few different places, it makes sense to make this description more generic, then amend it for `load_balancer` and `cvss` separately

2024-11-04 21:10 UTC, jonrau-at-queryai commented on objects/trace.json
> +  "name": "trace",
To me, I'd want to expand `trace` to also be inclusive of other standards beyond OTEL such as AWS X-Ray

https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html

2024-11-04 21:10 UTC, jonrau-at-queryai commented on objects/trace.json
> +      "description": "The trace type, as defined by the spac_type_id.",
I'll just leave one comment but when you reference another attribute/object name surround it with `<code>` and `</code>` tags so it renders nicely on the schema browser

2024-11-05 15:36 UTC, jonrau-at-queryai approved these changes

2024-11-05 16:59 UTC, floydtree requested changes

2024-11-05 16:59 UTC, floydtree commented on objects/metric.json
> +      "description": "The metric type, as defined by the metric_type_id.",
description is referring to a non existent field

2024-11-05 16:59 UTC, floydtree commented on objects/metric.json
> +          "caption": "db_client_operation_duration",
OCSF grammar conventions. 

This is the first time, we have used a `_` bridged word for captions of an ENUM. We need to consider its consistency throughout the framework. All other enums have captions that use standard Camel case. 

Is there an authoritative source for these eum items? If so, we should not reinvent them. 

Another question, what is it being normalized against? Do different implementations each metric type differently? If not, then do we even need this enum?

2024-11-05 16:59 UTC, floydtree commented on objects/trace.json
> +          "description": "The trace_type is unknown."
If this is coming from OTEL, let's link the authoritative source via `source` and/or `references` metaschema attributes.

Regarding captions, the same comment as `metric.type_id` caption

2024-11-05 16:59 UTC, floydtree commented on profiles/metrics.json
> +  "description": "The attributes that identify metrics attributes.",
This description needs some work. Let's try to explain what the profile actually does.

2024-11-05 16:59 UTC, floydtree commented on profiles/traces.json
> +  "description": "The attributes that identify trace attributes.",
Same as above, description needs some work

2024-11-05 16:59 UTC, floydtree commented on events/application/application_lifecycle.json
> +          "caption": "User_Activity",
The same caption inconsistency comment as in other enums. In here though, you are mixing Camel case with an `_`

We must be consistent in how captions are, throughout the framework

2024-11-05 16:59 UTC, floydtree commented on events/application/application_lifecycle.json
>      "activity_id": {
In general, I don't understand how these `activity_ids` will be used in this class. Also, if you are changing this class, please also update the class description to reflect the new capability.

What does `activity_name` "Session" mean in context of an event class titled Application Lifecycle? Subsequently, what does it affect the class schema? There's no relevant information to store details about the session. The same pattern applies to a lot of the newly added enum items.

What will really help is, providing a real world log, that is using the proposed class.

2024-11-05 17:19 UTC, mlmitch commented on dictionary.json
> +      "type": "json_t"
I was curious about the type choice here as well. Where is `key_value_object` defined? I see it used twice in dictionary.json but I don't see the definition.

2024-11-05 18:03 UTC, floydtree commented on dictionary.json
> +      "type": "json_t"
@mlmitch https://github.com/ocsf/ocsf-schema/blob/main/objects/key_value_object.json

It should be available in the schema-browser, in the `objects` view as well

2024-11-05 19:15 UTC, closed without merging