Email object and Email Activity updates. Deprecate Email URL Activity and Email File Activity.
ocsf/ocsf-schema pull request #1259
Opened 2024-11-20 21:56 UTC by pagbabian-splunk

#### Related Issue: N/A

#### Description of changes:

Added `domains` `files` `urls` and `message_trace_uid` to the dictionary for use with the `email` object and `email_activity` class.
Deprecated the two other classes in favor of a single `email_activity` class where the `email` object can also hold files domains and urls.

2024-11-20 23:14 UTC, mikeradka submitted a review, later dismissed
Looks great

2024-11-21 11:53 UTC, davemcatcisco requested changes
The requested changes are only the grammatical things in descriptions. My other comments are just suggestions or observations.

2024-11-21 11:53 UTC, davemcatcisco commented on dictionary.json
> +      "description": "The domains that pertain to the event or object",
Consistency: The vast majority of descriptions in this dictionary end with a full stop (period). This comment applies to all of the descriptions in this PR.

2024-11-21 11:53 UTC, davemcatcisco commented on dictionary.json
> +      "description": "The domains that pertain to the event or object",
The word _domains_ is quite general in meaning, e.g. I work in the security domain. Presumably the meaning in our dictionary with be DNS domains. Consider if this attribute would be more appropriately named `domain_names` or `dns_domains`.

2024-11-21 11:53 UTC, davemcatcisco commented on dictionary.json
> +      "description": "The identifier that tracks a message that travels through multiple points of a messaging service.",
Would it be helpful to give examples of what this maps to in real email products and/or protocol exchanges? One of the challenges I often have when working with the OCSF schema is that it's not clear to me what exactly is intended to go in a particular attribute.

2024-11-21 11:53 UTC, davemcatcisco commented on CHANGELOG.md
> +    1. Added `domains` `files` `urls` and `message_trace_uid`. #1259
Put commas between the attribute names, and optionally put an Oxford comma before the _and_. This comment applies to other additions to CHANGELOG.md in this PR.

2024-11-22 15:07 UTC, Aniak5 commented on dictionary.json
> +      "description": "The domains that pertain to the event or object",
The fact that `domains` is general in meaning might  be a good thing, then we have a higher likelihood that we can re-use that dictionary attribute. Maybe we should add `See specific usage.` to the description.

2024-11-22 15:08 UTC, Aniak5 commented on dictionary.json
> +      "description": "The files that are part of the event or object",
Nit: Add a period to the dscription.

2024-11-22 15:12 UTC, Aniak5 commented on dictionary.json
> +      "description": "The identifier that tracks a message that travels through multiple points of a messaging service.",
With Adam's proposal we will have a trace object (and profile) and a `trace.uid` within it. Are we trying to keep this attribute at the highest level?

2024-11-22 15:52 UTC, Aniak5 commented on events/network/email_activity.json
>      "smtp_hello": {
Do we maybe want to make this more generic since we are encapsulating more than just SMTP with this event class? Maybe using `command`?

`SMTP Commands: HELO, MAIL FROM, RCPT TO, DATA, QUIT, etc.
POP3 Commands: USER, PASS, RETR, DELE, QUIT, etc.
IMAP Commands: LOGIN, SELECT, FETCH, LOGOUT, etc.`

2024-11-22 15:55 UTC, Aniak5 commented on events/network/email_activity.json
>    "attributes": {
We should probably add a field to represent `protocol` so we can specify `SMTP`, `POP3`, `IMAP`, etc. We could either create a new `protocol` field or change the description of `protocol_name` in the dictionary and add `See specific usage.`

2024-11-22 16:03 UTC, pagbabian-splunk commented
Good suggestions all - I will update and convert from DRAFT.

2024-11-22 16:08 UTC, pagbabian-splunk commented on dictionary.json
> +      "description": "The identifier that tracks a message that travels through multiple points of a messaging service.",
Yes, I looked at that first, but I didn't want to use a `trace` object for this - in fact if I wanted to be more specific to Microsoft (which I'm trying to avoid), the `MessageTraceId` would be the `source` and it is directly in the event. Adam's PR is mirroring the OTel `Trace` concept which is related but likely its description and definitely usage will be different.

2024-11-22 16:16 UTC, pagbabian-splunk commented on dictionary.json
> +      "description": "The domains that pertain to the event or object",
Yes, we've had many discussions on domain, subdomain, path, hostname, suffix etc. `domain` is in the dictionary already and in use.  Interestingly in `URL` we have an example that tries to indicate what we mean by `domain` as a string, but it could be a `see specific usage` to be more general. In the email class, it should be similar in meaning to the `URL` meaning.

2024-11-22 23:27 UTC, pagbabian-splunk commented on dictionary.json
> +      "description": "The domains that pertain to the event or object",
Good catch.

2024-11-22 23:30 UTC, pagbabian-splunk commented on dictionary.json
> +      "description": "The domains that pertain to the event or object",
The dictionary description is almost tautological but I added `See specific usage.` to both `domain` and `domains`. Note that the descriptions for `subdomain` and `subdomains` are more specific, and relate to URLs.

2024-11-22 23:47 UTC, pagbabian-splunk commented on events/network/email_activity.json
>      "smtp_hello": {
The only issue I see is that if we make it `smtp_command` or just `command` we will have a value returned but we won't know which SMTP command it was.  If we want to cover all commands, we'd probably want to have an `SMTP Command` object and objects for POP3 and IMAP.  Or a single object such as `Email Command` that includes an enum that describes what the command is.  Please think about that @Aniak5 and we can have a separate PR for it, but I'll just leave the current `smtp_hello` intact for now.

2024-11-22 23:48 UTC, pagbabian-splunk commented on events/network/email_activity.json
>    "attributes": {
Let's do this at the same time as figuring out the `SMTP Command` approach since they are related, and we haven't really had much other discussion about it.

2024-11-26 16:29 UTC, Aniak5 commented on events/network/email_activity.json
>      "smtp_hello": {
Sounds good to me

2024-11-26 16:45 UTC, Aniak5 commented on objects/email.json
> +      "description": "The domain names that pertain to the email sender or recipients."
In Jeremy's example i see that `email_url_activity.url.hostname`  would potentially map to `domains` with description `The domains seen in the email.` The example shows:

```  
"email_url_activity": {
    "url": {
      "hostname": [
        "cimfl.com",
        "www.w3.org",
        "www.dinkumdunnies.com.au",
        "gnxpublishers.ca",
        "www.beenleighinterior.com.au",
        "ns-hd.co.jp",
        "schemas.microsoft.com"
      ],
      "url_string": [
        "http://www.beenleighinterior.com.au/",
        "https://gnxpublishers.ca/wp-content/uploads/2020/04/vary/28506345.zip",
        "http://www.dinkumdunnies.com.au",
        "http://cimfl.com/wp-content/vary/100516985.zip",
        "http://ns-hd.co.jp/wp-content/uploads/2020/04/vary/63223.zip",
        "http://schemas.microsoft.com/office/2004/12/omml",
        "http://www.w3.org/TR/REC-html40"
      ]
    }
```

so it seems as if this is actually more like the hostname/domain of the url's seen in the email rather than the domains of the sender/recipient within the email.

2024-11-26 22:37 UTC, pagbabian-splunk commented on objects/email.json
> +      "description": "The domain names that pertain to the email sender or recipients."
Good catch.  I will make the change.

2024-11-26 23:10 UTC, Aniak5 commented on objects/email.json
> +      "description": "The domain names that pertain to the email sender or recipients."
The URL object has a `hostname` attribute. We could potentially use that though it will be nested inside the URL object.

2024-11-26 23:14 UTC, pagbabian-splunk commented on objects/email.json
> +      "description": "The domain names that pertain to the email sender or recipients."
I used examples to show both `www.w3.org` and `ocsf.io` would equate to domains. Looking online I found quite a few examples of this (I used to think of `www` as a standard hostname but it seems people also consider it part of the primary domain name).

2024-11-26 23:26 UTC, Aniak5 commented on objects/email.json
> +      "description": "The domain names that pertain to the email sender or recipients."
Actually the URL object also has `domain` attribute as optional.

2024-12-02 17:52 UTC, mikeradka approved these changes

2024-12-02 17:53 UTC, jonrau-at-queryai approved these changes

2024-12-03 17:19 UTC, davemcatcisco approved these changes

2024-12-03 17:20 UTC, merged