feat: [1277] - Added `architecture` for `os` object
ocsf/ocsf-schema pull request #1278
Opened 2024-12-10 09:22 UTC by PavelJurka

#### Related Issue: 
1277 - Add Architecture to OS #1277

#### Description of changes:
Adding architecture to os object.

2024-12-10 20:21 UTC, gordonr-ca-ibm-com commented on objects/os.json
> +    "architecture": {
Is architecture really an operating system attribute? What is the architecture of Ubuntu 24.04.1 LTS? Well, it depends on which hardware it's running on.  arm64, x86_64, i386, etc, these are examples of _CPU_ architectures.

I see there is already an attribute (cpu_bits) describing the operating system's CPU. Maybe this property would be better named with the cpu_ prefix also.

2024-12-10 20:22 UTC, jonrau-at-queryai commented on objects/os.json
> +    "architecture": {
+1 this should be under `device.hw_info` and I do like `cpu_architecture` but I think `architecture` is self-explanatory.

2024-12-10 20:23 UTC, jonrau-at-queryai requested changes

2024-12-10 20:25 UTC, mikeradka commented on objects/os.json
> +    "architecture": {
Architecture already exists within the dictionary. In the spirit of keeping the dictionary clean, I would suggest refining the dictionary definition to be more generic and say `See specific usage`, and then reuse this attribute where needed.

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/84be63ef-c222-4c1b-8d56-193b71720df0">

2024-12-10 20:26 UTC, jonrau-at-queryai commented on objects/os.json
> +    "architecture": {
Haha just testing you!

Yeah, reuse that one

2024-12-10 21:41 UTC, davemcatcisco commented on objects/os.json
> +    "architecture": {
Nerdboy says: The word _architecture_ could also be a reference to the memory architecture, i.e. Harvard architecure, Princeton architecture, etc.

2024-12-10 21:57 UTC, davemcatcisco commented on objects/os.json
> +    "architecture": {
One other question...

There is already a `hw_info.cpu_type` attribute which, per the description, is supposed to contain strings like "x86 Family 6 Model 37 Stepping 5". Is this not equivalent to the architecture?

2024-12-10 22:03 UTC, davemcatcisco commented on objects/os.json
> +    "architecture": {
My Windows ARM machine reports "ARM-8 (64-bit) Family 8 Model 0 Revision 0" in `hw_info.cpu_type`.

My Windows x64 machine reports "Intel64 Family 6 Model 183 Stepping 1".

Are you wanting something less fine-grained?

2024-12-11 14:12 UTC, davemcatcisco commented on objects/os.json
> +    "architecture": {
If the possible values are to be "canned" like that, then I think it would achieve greatest consistency and hence usefulness if the new attribute is an enum type with a text sibling, i.e. `cpu_architecture_id` and `cpu_architecture`.

Suggested types:
- 0 = "Unknown"
- 1 = "x86 32-bit"
- 2 = "x86 64-bit"
- 3 = "ARM 32-bit"
- 4 = "ARM 64-bit"
- 5 = "RISC-V 32-bit"
- 6 = "RISC-V 64-bit"
- 99 = "Other"

Arguably, you don't need the bit count because there is already a `cpu_bits` attribute. So you could simplify the above to:
- 0 = "Unknown"
- 1 = "x86"
- 2 = "ARM"
- 3 = "RISC-V"
- 99 = "Other"

2024-12-12 10:01 UTC, PavelJurka commented on objects/os.json
> +    "architecture": {
Defined cpu_architecture + id and put under device_hw_info.

2024-12-12 10:01 UTC, PavelJurka commented on objects/os.json
> +    "architecture": {
device_hw_info extended by cpu_architecture

2024-12-12 12:24 UTC, davemcatcisco requested changes
Just a few minor but important changes please. Thanks.

2024-12-12 12:24 UTC, davemcatcisco commented on dictionary.json
> +        "description": "The CPU architecture, as reported by the event source.",
For the text sibling of an enum attribute, the description follows a defined pattern. In this case of this one, the wording would be:
```
The CPU architecture, normalized to the caption of the <code>cpu_architecture_id</code> value. In the case of <code>Other</code>, it is defined by the source.
```

2024-12-12 12:24 UTC, davemcatcisco commented on dictionary.json
> +          "caption": "x86"
Optional, but you could add a `description` to each of these:
- CPU uses the x86 ISA. For bitness, refer to <code>cpu_bits</code>.
- CPU uses the ARM ISA. For bitness, refer to <code>cpu_bits</code>.
- CPU uses the RISC-V ISA. For bitness, refer to <code>cpu_bits</code>.

2024-12-12 12:24 UTC, davemcatcisco commented on dictionary.json
> +          "description": "The cpu architecture is unknown."
Capitalise 'CPU' in this description.

2024-12-12 12:24 UTC, davemcatcisco commented on dictionary.json
> +          "description": "The cpu architecture is not mapped. See the <code>cpu_architecture</code> attribute, which contains a data source specific value."
Capitalise 'CPU' in this description.

2024-12-12 13:14 UTC, PavelJurka commented on dictionary.json
> +        "description": "The CPU architecture, as reported by the event source.",
thank you!

2024-12-12 13:16 UTC, PavelJurka commented on dictionary.json
> +          "caption": "x86"
thank you, sounds great;)

2024-12-12 13:43 UTC, davemcatcisco submitted a review, later dismissed

2024-12-13 15:24 UTC, jonrau-at-queryai approved these changes

2024-12-13 15:37 UTC, floydtree approved these changes

2024-12-13 19:50 UTC, Aniak5 approved these changes
LGTM

2024-12-13 19:50 UTC, pagbabian-splunk approved these changes

2024-12-13 19:51 UTC, mikeradka approved these changes

2024-12-17 17:18 UTC, jonrau-at-queryai approved these changes

2024-12-17 17:42 UTC, Aniak5 approved these changes

2024-12-17 17:45 UTC, mikeradka approved these changes

2024-12-17 17:45 UTC, merged