Add: Unlock Activity
ocsf/ocsf-schema pull request #1285
Opened 2024-12-12 19:31 UTC by 0xv1n

#### Related Issue: 

In Windows, I'd like to be able to distinguish an account enable event from an account unlock event.

#### Description of changes:

This change would allow for coverage of events such as Windows EID 4767 (https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4767).

There is another Windows EID for enabling an account (https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4722) and I imagine the distinction is importing for mapping.

### Delete once you have confirmed the following: 
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Is your PR title in sync with the description?

2024-12-12 19:38 UTC, mikeradka requested changes

2024-12-12 19:38 UTC, mikeradka commented on events/iam/account_change.json
>          "10": {
@0xv1n The `Unlock` versus `Enable` distinction is important. Today, our org maps the `Enable` event, `4722`. I see benefit in adding this activity. That said, it is breaking to re-order the enum numbers, so the `Unlock` will need to be added after the `MFA Factor Disable` activity - IE this new activity should be `12` as an enum value.

2024-12-12 19:42 UTC, 0xv1n commented on events/iam/account_change.json
>          "10": {
@mikeradka Made that change in https://github.com/ocsf/ocsf-schema/pull/1285/commits/5199d8073653e6898211a9d40cc55f663de190d0 - thank you for that information I'll keep that in mind moving forward!

2024-12-12 19:44 UTC, mikeradka requested changes

2024-12-12 19:44 UTC, mikeradka commented on events/iam/account_change.json
> +        },
Looks better, you'll have to remove the comma on line 57 for it to load into the ocsf server without error.

2024-12-12 19:50 UTC, mikeradka approved these changes
Looks good from my side. Straightforward, impactful add. Nice contribution.

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/cd0ac344-ad71-4cb3-aa98-401571a58bb9" />

2024-12-13 15:23 UTC, jonrau-at-queryai approved these changes

2024-12-13 19:19 UTC, floydtree approved these changes

2024-12-13 19:19 UTC, merged