updated container activity event class.
ocsf/ocsf-schema pull request #148
Opened 2022-08-11 20:30 UTC by ashishvermarox

Updated container activity event class.
Added UID and some name changes.
Tested the json files on local server, which resulted in 0 errors.
Screenshot of UI attached.
<img width="1303" alt="Screen Shot 2022-08-11 at 4 27 38 PM" src="https://user-images.githubusercontent.com/11677628/184236322-89bf65ee-c648-440c-bd3a-457d68bd1e50.png">

 Signed-off-by: Ashish Verma [ashish_verma@live.com](mailto:ashish_verma@live.com)

2022-08-11 21:53 UTC, rroupski requested changes

2022-08-11 21:53 UTC, rroupski commented on events/container/container_activity.json
> +	"uid": 0,
If this class is meant to be the base class for the other container classes, then I'd suggest to remove the uid to hide the class from the schema browser.

2022-08-11 21:53 UTC, rroupski commented on events/container/lifecycle.json
> +	"extends": "base_event",
Perhaps you want to "extends": "container_activity" to get all attributes defined in the container_activity class?

2022-08-11 21:53 UTC, rroupski commented on events/container/lifecycle.json
> +	"description": "Container lifecycle  events report installation, removal, start, and stop of containers.",
You will need to add `"uid": 1` to make the class visible on the schema browser.

2022-08-11 22:39 UTC, ashishvermarox commented
Hello @rroupski, 
Below is summary of changes as requested.
1. container.json is removed.
2. container_activity is base class, with no UID.
3. lifecycle.json is extending conatiner_activity, with UID 1, so that it is visible on browser.

2022-08-17 21:43 UTC, rroupski approved these changes

2022-08-17 21:43 UTC, rroupski approved these changes

2022-08-17 21:45 UTC, merged