Rfb Event Class
ocsf/ocsf-schema pull request #226
Opened 2022-09-19 18:38 UTC by Aniak5

• Add new RFB event class
![image](https://user-images.githubusercontent.com/6465263/191090767-6ca15b6e-f5fc-4a77-97f7-c4ec43131fd9.png)
![image](https://user-images.githubusercontent.com/6465263/191090801-3bfa39e7-c6e7-49df-a0ce-789553d2edcc.png)

2022-09-19 23:46 UTC, rroupski requested changes
Can you bump up the version number to 0.21.0?

2022-09-19 23:46 UTC, rroupski commented on objects/framebuffer.json
> +  "name": "framebuffer",
If the object  caption is _Frame Buffer_ (2 words), then the object name should `frame_buffer`?

2022-09-19 23:46 UTC, rroupski commented on objects/server.json
> +  "constraints": {
I think the server `name` should be recommended and the contracts will be:
```
"constraints": {
   "at_least_one": [
       "name",
       "uid"
     ]
  }

```
The `protocol_ver` does not look as a server identifier, thus it should not be used in the constraints.

2022-09-19 23:46 UTC, rroupski commented on objects/vnc.json
> +  "description": "The Virtual Network Computing (VNC) authentication object describes the vnc authentication values.",
Use all-upper-case in "...describes the **VNC** authentication...".

2022-09-20 03:36 UTC, Aniak5 commented on objects/framebuffer.json
> +  "name": "framebuffer",
Sounds good!

2022-09-20 03:37 UTC, Aniak5 commented on objects/server.json
> +  "constraints": {
Good point.

2022-09-20 16:18 UTC, rroupski approved these changes

2022-09-20 16:18 UTC, merged