Field additions in proxy and authorization objects
ocsf/ocsf-schema pull request #232
Opened 2022-09-20 20:40 UTC by floydtree

1. Adding identifier fields in the proxy object
2. Adding policy identifer fields in the authorization object
3. consequent dictionary changes
![Screen Shot 2022-09-20 at 4 39 40 PM](https://user-images.githubusercontent.com/89877409/191359980-b9ec0c74-55c1-40c6-9bdc-4789758c6ca2.png)
![Screen Shot 2022-09-20 at 4 39 59 PM](https://user-images.githubusercontent.com/89877409/191360038-a61b4e25-193c-45c3-bc53-d7ee41c0e3bd.png)

2022-09-20 22:39 UTC, rroupski requested changes

2022-09-20 22:39 UTC, rroupski commented on dictionary.json
> +    "policy_name": {
We have a [policy](https://schema.ocsf.io/objects/dev/policy) object in the dev extensions, perhaps we can use it here?

2022-09-20 22:39 UTC, rroupski commented on dictionary.json
> +      "type": "authorization",
Rename the attribute as `authorizations`?

2022-09-20 22:39 UTC, rroupski commented on objects/authorization.json
> +    "policy_name": {
Use the [policy](https://schema.ocsf.io/objects/dev/policy) object?

2022-09-21 17:19 UTC, floydtree commented on dictionary.json
> +    "policy_name": {
Yeah good idea, I'll move that in, however the type_id in the policy object might need some rework. We can tackle improvement to the policy object in a separate PR

2022-09-21 17:42 UTC, merged