SMTP Event Class
ocsf/ocsf-schema pull request #239
Opened 2022-09-22 12:49 UTC by Aniak5

<img width="142" alt="image" src="https://user-images.githubusercontent.com/6465263/191636251-a4b9973a-cb62-46ab-97d5-39a7a78de987.png">
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/6465263/191637241-bbda1e72-928f-4904-80d0-60682a90825f.png">

2022-09-22 17:28 UTC, rroupski requested changes

2022-09-22 17:28 UTC, rroupski commented on dictionary.json
> +    "message_id": {
It should be message_uid, otherwise it looks like a enum?

2022-09-22 19:32 UTC, Aniak5 commented on dictionary.json
> +    "message_id": {
Yes, good catch.

2022-09-23 15:21 UTC, rroupski approved these changes

2022-09-23 15:22 UTC, merged