Revising status_id and activity_id for security finding event class
ocsf/ocsf-schema pull request #260
Opened 2022-09-29 19:33 UTC by floydtree

1. Extending `findings` instead of base_event. https://github.com/ocsf/ocsf-schema/pull/248
2. Modifying `findings` class to remove malware profile.
   1. All the necessary attributes are already defined in the security finding class.
   2. Adding malware profile creates duplication of these attributes and conflicting query paths.
3. Adding a single activity_id enum for findings class.
4. Adding status_id enum specific to this class.
----
![Screen Shot 2022-09-29 at 3 33 14 PM](https://user-images.githubusercontent.com/89877409/193125379-09149f7f-0ca5-4a07-9834-bcd5e01d41a5.png)

![Screen Shot 2022-09-29 at 3 33 02 PM](https://user-images.githubusercontent.com/89877409/193125356-2f282802-9911-4557-b0c2-a9aabfa5efec.png)

Signed-off-by: Rajas <rajaspa@amazon.com>

2022-09-29 20:18 UTC, rroupski commented
How are you going to log events with updates or state changes?

I'd suggest to look at the incident classes (for example [Incident Create](https://schema.ocsf.io/classes/dev/incident_create?extensions=dev )). 

Also, I'd recommend to use the `state_id` instead of `status_id` attribute. The `status_id` should be used to indicate the status of an activity -- successful or failure. For example, for a failed attempt to create a new finding, the `status_id` will 2 - Failure.

2022-09-29 20:19 UTC, rroupski requested changes

2022-09-29 20:19 UTC, rroupski commented on events/findings/findings.json
> +          "caption": "Finding Generated",
The activity_id Caption should use a present tense.

2022-09-29 20:56 UTC, floydtree commented on events/findings/findings.json
> +          "caption": "Finding Generated",
Cool, changing. I have also added an `Update` activity in the enum

2022-09-29 22:32 UTC, rroupski approved these changes

2022-09-29 22:32 UTC, merged

2022-09-30 01:38 UTC, johan1252 commented on events/findings/security_finding.json
> -  ],
@floydtree Question relating to profile for security finding events, how are we determining which profiles make sense to include here?
Security findings could contain malware information if they are a malware finding, but could contain network information (src ip, dst ip, etc.) if they are an intrusion prevention finding, or could contain cloud information if the finding was found in a cloud environment (list goes on...).
Feels like there could be many profiles (some of which likely don't exist yet) that could apply to this event class.