Move K8s object from AWS extension to core
ocsf/ocsf-schema pull request #266
Opened 2022-09-30 14:22 UTC by magnologan

Moving the K8s object from the AWS extension to the core schema. 

As discussed here: https://opencybersecu-lz97379.slack.com/archives/C03C2QJRA73/p1664470650464869

Updated dictionary.json with the required attributes.

2022-09-30 16:12 UTC, rroupski requested changes
Please make sure that all new attributes are defined in the dictionary.

2022-09-30 16:12 UTC, rroupski commented on dictionary.json
> +    "pod_ip": {
I see a few attributes that have a prefix `pod_`, perhaps create and use a `pod` object ?

Then we can "reuse" `name`, `uid`, and `namespace` attributes.

2022-09-30 16:12 UTC, rroupski commented on objects/kubernetes.json
> +    "container_orchestration_runtime": {
where is the `container_orchestration_runtime` defined? I don't see it in the dictionary changes above? BTW, can we use the existing `runtime` attribute, instead of defining a new attribute?

2022-09-30 16:12 UTC, rroupski commented on objects/kubernetes.json
> +      "description": "AuditLevel at which event was generated",
Missing space in `AuditLevel`, use *Audit level* ...?

2022-09-30 16:12 UTC, rroupski commented on objects/kubernetes.json
> +      "description": "The HTTP Request Object details a request made to a web server",
The description looks generic, what is the role of the `http_request` in the Kubernetes object context?

2022-09-30 16:12 UTC, rroupski commented on objects/kubernetes.json
> +      "description": "The HTTP Response Object details a response from a web server to a requester",
The description looks generic, what is the role of the `http_response` in the Kubernetes object context?

2022-09-30 16:12 UTC, rroupski commented on objects/kubernetes.json
> +      "description": "Embedded Kubernetes API JSON dict from the request",
what is "JSON dict"? dictionary?

2022-09-30 16:15 UTC, magnologan commented on dictionary.json
> +    "pod_ip": {
Added the missing attributes. I'm just moving this object from the AWS extension to Core, nothing has changed yet.

2022-09-30 17:27 UTC, floydtree commented on dictionary.json
> +    "stage_timestamp": {
perhaps rename it to `stage_time` to be consistent with other timestamp fields?

2022-09-30 18:48 UTC, rroupski commented on dictionary.json
> +    "pod_ip": {
ok, we can do that later.

2022-09-30 18:56 UTC, rroupski requested changes

2022-09-30 18:56 UTC, rroupski commented on dictionary.json
> +      "type": "container_orchestration_runtime"
We need to move the container_orchestration_runtime object too.

2022-10-24 00:22 UTC, rroupski commented
@magnologan is this PR still applicable? Or, we should close it?

2022-10-24 15:48 UTC, closed without merging