Add account_name attribute
ocsf/ocsf-schema pull request #370
Opened 2022-11-22 18:43 UTC by LiamSennitt

2022-11-22 18:48 UTC, rroupski commented
Please update the version number.

2022-11-22 18:48 UTC, rroupski requested changes
Update the version number.

2022-11-22 18:48 UTC, rroupski commented on objects/resource.json
> +      "description": "The unique identifier of the resource owning account (e.g. AWS Account ID).",
What does the description mean? The resource owns the account or the account owns the resource?

2022-11-22 18:53 UTC, floydtree commented on objects/resource.json
> +      "description": "The unique identifier of the resource owning account (e.g. AWS Account ID).",
I interpret it as, account that owns the resource.

2022-11-22 19:03 UTC, LiamSennitt commented on objects/resource.json
> +      "description": "The unique identifier of the resource owning account (e.g. AWS Account ID).",
I just added the missing space 😅

2022-11-22 19:08 UTC, floydtree approved these changes

2022-11-22 19:29 UTC, LiamSennitt commented on dictionary.json
> +      "description": "The unique identifier of the account (e.g. AWS Account Name).",
This should be "The name of...", I'll update that 👍

2022-11-22 19:29 UTC, LiamSennitt commented on objects/resource.json
> +      "description": "The unique identifier of the resource owning account (e.g. AWS Account ID).",
Out of interest could I remove this description as it's duplicated in the `dictionary.json`?

2022-11-22 22:28 UTC, rroupski requested changes
Since you are changing the resource.json file, can you update the `account_uid` description as: `The unique identifier of the account that owns the resource (e.g. AWS Account ID).`

2022-11-23 17:54 UTC, rroupski approved these changes

2022-11-23 17:54 UTC, merged