Move Email Activities to Network Category
ocsf/ocsf-schema pull request #378
Opened 2022-11-29 17:00 UTC by ablyler

Email-related activities better fit the network category rather than the system category; this also allows email activities not to require an actor attribute, which is hard to determine what the appropriate value should be.

2022-11-29 19:00 UTC, rroupski commented
I don't think we need any email class(es) in the Findings category. Instead, we should use the email classes in the network category with a profile, e.g. Malware profile, for events that include detections of bad things found in the email.

2022-11-29 19:00 UTC, rroupski requested changes
See my comment

2022-11-29 19:19 UTC, Aniak5 commented on extensions/dev/events/findings/email/email.json
>    "name": "email_finding",
Agreed with @rroupski that we should remove `email` from the `findings` category.

2022-11-29 19:44 UTC, ablyler commented
@rroupski + @Aniak5 thanks for the feedback, updates have been made.

2022-11-29 20:08 UTC, ablyler commented on extensions/dev/events/network/email/email.json
>      }
I am okay with removing it, it seems like something we could add back if we need to link email objects with the vendor's quarantine system.

2022-11-29 20:28 UTC, Aniak5 commented
@ablyler did you mean to move the `peripheral_activity` class from the `system` to the `network` category?

2022-11-29 20:39 UTC, ablyler commented
> @ablyler did you mean to move the `peripheral_activity` class from the `system` to the `network` category?

Good catch, that was not intentional. I have fixed that now.

2022-11-29 22:20 UTC, Aniak5 approved these changes
LGTM!

2022-11-30 01:22 UTC, rroupski approved these changes

2022-11-30 01:23 UTC, merged