Add auth_type_id and update rcode_id
ocsf/ocsf-schema pull request #431
Opened 2023-01-22 14:23 UTC by Aniak5

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/6465263/213920716-f70a8968-0224-4dc4-b3ec-da8616918523.png">

2023-01-22 14:24 UTC, Aniak5 commented
The changes to `rcode_id` are so that the soon to come LDAP class can use this attribute.

2023-01-23 17:12 UTC, rroupski approved these changes

2023-01-25 15:06 UTC, floydtree requested changes

2023-01-25 15:06 UTC, floydtree commented on events/network/rfb.json
> +      "enum": {
99 instead of -1?

2023-01-25 15:06 UTC, floydtree commented on events/network/dns.json
> +        "-1": {
99 instead of -1

2023-01-25 16:58 UTC, mr-splunk approved these changes

2023-01-25 20:31 UTC, floydtree requested changes

2023-01-25 20:31 UTC, floydtree commented on dictionary.json
> +        "-1": {
99 instead of -1

2023-01-25 20:37 UTC, Aniak5 commented on dictionary.json
> +        "-1": {
Oops, missed that one. Done, thanks!

2023-01-25 20:44 UTC, floydtree approved these changes

2023-01-25 22:49 UTC, merged