WIP: Add system resource object
ocsf/ocsf-schema pull request #433
Opened 2023-01-23 23:17 UTC by awhite456

Add the system resource object to satisfy https://github.com/ocsf/ocsf-schema/issues/432

2023-01-23 23:31 UTC, rroupski requested changes

2023-01-23 23:31 UTC, rroupski commented on dictionary.json
> +    "resource_attributes": {
Since the `resource_attributes` is used in the `system_resource` object, the `resource_` should be removed to avoid repetition of words.

Also, the attribute type is a string (a single value), thus the attribute name should be a singular noun.

2023-01-23 23:31 UTC, rroupski commented on dictionary.json
> +    "resource_server": {
Since the `resource_attributes` is used in the `system_resource` object, the `resource_` should be removed to avoid repetition of words.

2023-01-23 23:31 UTC, rroupski commented on dictionary.json
>      "resource_type": {
You can use `type` attribute  instead of defining an attribute.

2023-01-23 23:31 UTC, rroupski commented on objects/system_resource.json
> +  "description": "The system resource object describes a resource managed by an operating system, such as mutant or timer.",
mutant or mutex  ? :-)

2023-01-24 19:07 UTC, awhite456 commented on dictionary.json
> +    "resource_attributes": {
Done

2023-01-24 19:07 UTC, awhite456 commented on dictionary.json
> +    "resource_server": {
Done

2023-01-24 19:08 UTC, awhite456 commented on objects/system_resource.json
> +  "description": "The system resource object describes a resource managed by an operating system, such as mutant or timer.",
Resource object is `mutant`, kernel object is `mutex`, thanks Windows!

2023-01-25 00:30 UTC, rroupski approved these changes

2023-01-25 00:54 UTC, Aniak5 approved these changes
LGTM

2023-01-25 01:09 UTC, Aniak5 approved these changes

2023-01-25 01:15 UTC, merged