Change System Resource to be Windows specific
ocsf/ocsf-schema pull request #442
Opened 2023-01-25 22:58 UTC by awhite456

Make System Resource specific to Windows, and rename to `win_resource`

2023-01-25 23:01 UTC, mr-splunk approved these changes
This looks good to me, thanks for submitting this one.

2023-01-26 16:44 UTC, rroupski requested changes
The descriptions refer the "resource" in multiple ways, as  _resource_,  _resource/object_, _resource object_.

Based on this [Windows doc](https://learn.microsoft.com/en-us/windows/win32/sysinfo/handles-and-objects), perhaps we should use "object handle"?

2023-01-26 16:44 UTC, rroupski commented on dictionary.json
> +      "caption": "object_server",
Since the `caption` is a short user-friendly name, thus it should **Object Server**.

2023-01-26 16:44 UTC, rroupski commented on objects/win_resource.json
> +            "caption": "WindowStation"
Add spaces in the caption text, e.g. `Window Station`. The same applies for the others below.

2023-01-26 16:44 UTC, rroupski commented on events/system/windows/resource.json
>    "caption": "Resource Activity",
Windows Resource Activity?

2023-01-26 17:51 UTC, awhite456 commented on objects/win_resource.json
> +      "caption": "Attribute"
In the 4663 event, it is defined as follows:
> Resource Attributes: attributes associated with the object. For some objects, the field does not apply and “-“ is displayed.
> For example, for a file, the following might be displayed: S:AI(RA;ID;;;;WD;("Impact_MS",TI,0x10020,3000))
I have reworked the description, maybe it makes more sense now? Could also rename to `attribute_string` or `resource_attributes`

2023-01-26 17:57 UTC, awhite456 commented on objects/win_resource.json
> +            "caption": "WindowStation"
I would rather leave these as is - per Microsoft docs the type is a `WindowStation` not a `Window Station`.

2023-01-26 21:56 UTC, rroupski commented on dictionary.json
> +    "object_server": {
OK, I see. In this case we should use the existing attribute: `svc_name`, with this description: "The service managing the resource object, such as Security or Security Account Manager.",

2023-01-26 21:56 UTC, rroupski commented on objects/win_resource.json
> +      "caption": "Attribute"
Let's use the existing `details` attribute, which is already used by the existing `resource` object.

2023-01-26 22:04 UTC, rroupski requested changes
Did you update the `type_id's` captions? I still see joined words, e.g.I see `WindowStation` -- it  should be `Window Station`.

2023-01-27 16:58 UTC, mr-splunk approved these changes

2023-01-27 17:43 UTC, rroupski submitted a review, later dismissed

2023-01-27 17:46 UTC, mr-splunk commented on dictionary.json
> +    "object_server": {
I think this makes a lot of sense actually, as what this represents is the service such as SAM.

2023-01-27 17:51 UTC, mr-splunk commented on objects/win_resource.json
> +      "caption": "Attribute"
I certainly agree here that 'attribute' is maybe too common of a name.

2023-01-27 18:28 UTC, awhite456 commented on objects/win_resource.json
> +      "caption": "Attribute"
Changed to `details`

2023-01-27 18:28 UTC, awhite456 commented on dictionary.json
> +    "object_server": {
Changed to `svc_name`

2023-01-27 19:19 UTC, rroupski approved these changes

2023-01-27 19:22 UTC, mr-splunk approved these changes
LGTM, thanks Andrew

2023-01-27 19:25 UTC, merged