reorganize email fields
ocsf/ocsf-schema pull request #452
Opened 2023-01-30 14:53 UTC by ablyler

- make attempt optional
- move direction, direction_id, and smtp_hello from email object to email activity class
- rename smtp_hello to src_smtp_hello to ensure it is clear it is the hello banner from the client that is sending the email to the server
- move dkim_signature from email activity class to email auth object
- move raw_header from email auth object to email activity class

Signed-off-by: Andy Blyler <ablyler@barracuda.com>

2023-01-30 15:10 UTC, ablyler commented
The logic behind these changes:

email activity:
- attempt: Make this field optional since it doesn't apply to security scanners unless they are in line.
- direction and direction id: Move these fields from the email object since they describe the activity and not the actual contents of an email.
- smtp_hello: Move the field from the email object since it is only present during the activity and not part of the actual email. Also, rename it to src_smtp_hello to make it clear it is the hello from the client. In the future, we might want to add an upstream hello field for proxies.

email auth class:
- dkim_signature: Move the field from the email activity because it is related to the other auth fields in the auth class.

email object:
- raw_header: Move the field from the email auth object since it is part of the core information for the email and not just used for auth.

2023-01-30 16:11 UTC, Aniak5 commented on extensions/dev/events/network/email/email.json
> +      "description": "The direction of the email relative to the scanning host or organization.</p>Email scanned at an internet gateway might be characterized as inbound to the organization from the
Did you want to have this `</p>` here? I do not see a starting paragraph element.

2023-01-30 16:18 UTC, rroupski requested changes

2023-01-30 16:18 UTC, rroupski commented on extensions/dev/events/network/email/email.json
> +    "src_smtp_hello": {
Rename the `smtp_hello` attribute in the dictionary, and also move the description to the dictionary.

2023-01-30 16:18 UTC, rroupski commented on extensions/dev/events/network/email/email.json
> +      "description": "The direction of the email, as defined by the <code>direction_id</code> value.",
Add `group`: primary or context?

2023-01-30 16:18 UTC, rroupski commented on extensions/dev/events/network/email/email.json
> +    "direction_id": {
Add `group`: primary or context?

2023-01-30 16:18 UTC, rroupski commented on extensions/dev/events/network/email/email.json
> +      "description": "The initiator (client) SMTP hello banner.",
Add `group`: primary or context?

2023-01-30 16:57 UTC, ablyler commented on extensions/dev/events/network/email/email.json
> +      "description": "The direction of the email relative to the scanning host or organization.</p>Email scanned at an internet gateway might be characterized as inbound to the organization from the
Good catch; this was copied and pasted from the email object class. What is the general guidance on HTML in the description? Should we start this with an opening tag?

2023-01-30 17:08 UTC, ablyler commented on extensions/dev/events/network/email/email.json
> +      "description": "The direction of the email relative to the scanning host or organization.</p>Email scanned at an internet gateway might be characterized as inbound to the organization from the
Looking at the web UI, it looks like we should start and end the paragraph tags. I'll fix this one and put up another PR to fix other instances I found of this.

2023-01-30 17:12 UTC, ablyler commented
@rroupski + @Aniak5 I resolved the issues you raised. Thanks for the feedback!

I also reverted the `smtp_hello` name change. I talked myself out of it after realizing that if a proxy was receiving and sending emails, it should be two activities.

2023-01-30 17:19 UTC, Aniak5 approved these changes
LGTM!

2023-01-31 00:43 UTC, rroupski requested changes

2023-01-31 00:43 UTC, rroupski commented on extensions/dev/events/network/email/email.json
> +    "src_smtp_hello": {
I don't see the src_smtp_hello in the dictionary?

2023-01-31 18:24 UTC, rroupski approved these changes

2023-01-31 18:24 UTC, merged