Issue 500: Update JA3 Attributes in TLS Object
ocsf/ocsf-schema pull request #516
Opened 2023-03-09 15:17 UTC by Aniak5

-  Remove `ja3_string`/`ja3s_string`
- Rename `ja3_fingerprint`/`ja3s_fingerprint` to `ja3_hash`/`ja3s_hash` and update description to relay that this is an md5 hash

#500 
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/6465263/224068913-b1f0cce7-82ce-4625-8778-6b68d8582fd0.png">

2023-03-09 15:49 UTC, rroupski requested changes

2023-03-09 15:49 UTC, rroupski commented on dictionary.json
> +      "description": "The MD5 hash of JAS3 string.",
typo, **JA3S** string?

2023-03-09 15:55 UTC, Aniak5 commented on dictionary.json
> +      "description": "The MD5 hash of JAS3 string.",
Oops i noticed that, made the change and then didnt push it up :D

2023-03-09 16:29 UTC, rroupski approved these changes

2023-03-09 16:34 UTC, mr-splunk approved these changes
Looks good to me

2023-03-11 17:03 UTC, pagbabian-splunk approved these changes

2023-03-13 16:46 UTC, merged