Rename Audit to Access Control
ocsf/ocsf-schema pull request #521
Opened 2023-03-14 17:31 UTC by jc-sumo

Per discussion on 2023-03-14, renames "Audit Activity" category to "Access Control Activity" to remove confusion stemming from generalized definition of "Audit" and bring it closer in line with the present definition of the category: "...events relate to the supervision of the system's access control model. Examples of such events are the success or failure of authentication, granting of authority, password change, entity change, privileged use, system state change, and resource access."

Removes extraneous 'audit.json' from events as this was not being used and is out of line with the proposed adjustment to the name.

Changes path for category and classes within it and changes class association accordingly.

Does not change association of "API Activity" class as was discussed, this should be done in a separate PR once the Application category class is resurrected.

2023-03-14 18:12 UTC, floydtree requested changes
Grammar changes & fixes to all class definitions

2023-03-14 18:12 UTC, floydtree commented on categories.json
> +    "access control": {
To be in sync with our naming convention/grammar, underscore instead of space to separate the word? `access_control`

2023-03-14 18:12 UTC, floydtree commented on events/access_control/access_activity.json
> +  "extends": "access control",
I don't see an access_control.json that this class could extend, if we are not creating any, all the classes must extend the `base_event`.

But note that, host profile was in the audit.json definition, so we should either create a new access_control.json similar to audit.json and have all the classes extend access_control OR add host profile individually in the classes. I would prefer the first option for simplicity and consistency with other classes across OCSF.

2023-03-14 19:14 UTC, floydtree requested changes
The classes still seem to extend access_control, but a corresponding file is not present. So the server build will fail. Let's pick it up on slack, will be quicker to resolve.

2023-03-16 00:47 UTC, rroupski requested changes

2023-03-16 00:47 UTC, rroupski commented on events/audit/audit.json
We still need this class, which is the base class for the audit/access_control events adding category and the host profile. Rename the file as access_control.json and update the classes that extends it.

2023-03-17 16:29 UTC, closed without merging