Adding new objects and attributes for Security Finding: Proposal #490
ocsf/ocsf-schema pull request #526
Opened 2023-03-18 02:34 UTC by pagbabian-splunk

From Proposal #490 adding objects and attributes from the Splunk Detection Report extension to Findings, to the core Security Finding event class.  Note, these are the objects.  There is another Proposal for other attributes, a change in an activity_id caption, and ultimately an update to the Security Finding event class still to come.

2023-03-19 20:46 UTC, pagbabian-splunk commented
Also added attributes for Security Finding from Proposal #491 including a new `impact_score` integer attribute and changing the Splunk extension type of `impact` to a `string_t` sibling.

2023-03-19 23:50 UTC, irakledibm submitted a review, later dismissed

2023-03-20 14:34 UTC, floydtree requested changes

2023-03-20 17:29 UTC, pagbabian-splunk commented on objects/kill_chain.json
> +      "phase_id": {
Ah, missed that one.  Thanks.  Will update.

2023-03-20 21:02 UTC, rroupski approved these changes

2023-03-20 21:17 UTC, irakledibm submitted a review, later dismissed
looks good

2023-03-20 21:19 UTC, floydtree requested changes

2023-03-20 21:19 UTC, floydtree commented on events/findings/findings.json
>            "description": "A security finding is generated."
Might as well update the description to reflect the change?

2023-03-20 22:14 UTC, pagbabian-splunk commented on events/findings/findings.json
>            "description": "A security finding is generated."
Yes, just pushed that change.

2023-03-20 22:17 UTC, floydtree approved these changes

2023-03-20 23:16 UTC, rroupski approved these changes

2023-03-20 23:19 UTC, rroupski approved these changes

2023-03-21 02:47 UTC, irakledibm approved these changes

2023-03-21 03:22 UTC, merged