Minor enhancements to Authorization class
ocsf/ocsf-schema pull request #531
Opened 2023-03-21 13:14 UTC by odianosen

Changelog: 

* Added Revoke activities to `Authorization` class.
* Added `resource` to `Authorization` class.
* Updated attribute `dst_endpoint` from required to recommended.
* Added a constraint that at least one of `dst_endpoint` or `resource` is required.
* Updated some descriptions for consistency.

<img width="1522" alt="Screen Shot 2023-03-21 at 6 13 23 AM" src="https://user-images.githubusercontent.com/9001550/226616708-dd92aa75-eb6d-4521-af21-c49d660580c4.png">

2023-03-23 03:28 UTC, pagbabian-splunk requested changes
Needs to be updated to reflect discussion in #533.

2023-03-23 16:26 UTC, floydtree submitted a review, later dismissed

2023-03-24 16:27 UTC, pagbabian-splunk commented
I think the 'at least one' constraint should be for `user` `related_groups` or `session` not `dst_endpoint` and `resource` because those are the targets for all of the activities.  If we only required `dst_endpoint` or `resource` I'm not sure how any of the activities would be enforced.

2023-03-24 18:28 UTC, odianosen commented
> I think the 'at least one' constraint should be for `user` `related_groups` or `session` not `dst_endpoint` and `resource` because those are the targets for all of the activities. If we only required `dst_endpoint` or `resource` I'm not sure how any of the activities would be enforced.

@pagbabian-splunk Yes, I don't disagree. I had thought about it. But the same applies to `privileges` and `assigned_groups` - they are common to all activities and also require enforcement with an 'at least one' constraint (an authorization event that doesn't specify what permissions are being given isn't much use). 

The problem though is syntactic - there doesn't appear to be a way to enforce multiple 'at least one' constraints.

2023-03-30 21:21 UTC, floydtree requested changes

2023-03-30 21:21 UTC, floydtree commented on dictionary.json
> +      "caption": "Privileges",
caption needs an update

2023-04-04 16:26 UTC, jp-harvey requested changes
Looking pretty good @odianosen! have left some comments

2023-04-04 16:26 UTC, jp-harvey commented on events/access_control/authorization.json
> +    "dst_endpoint": {
Do we still need this if we have `resource`? This class becomes very "device" focused if we do. Suggest we make a single attribute for one of `resource` or `dst_endpoint` if it needs to be retained.

2023-04-04 16:26 UTC, jp-harvey commented on enums/authorization.json
>      "1": {
We only cover permissions / privs here, we should expand a bit to cover groups so it's clear.

2023-04-04 16:26 UTC, jp-harvey commented on enums/authorization.json
> +      "description": "Revoke permissions or privileges from a principal.",
Ditto with groups in the description for clarity.

2023-04-04 16:26 UTC, jp-harvey commented on objects/grants.json
> +  "description": "Permissions or privileges that are granted to or revoked from a principal.",
Suggest adding language about `groups` in here so it more closely reflects the functionality.

2023-04-04 16:26 UTC, jp-harvey commented on dictionary.json
> +      "description": "Permissions or privileges that are granted to or revoked.",
Is this relevant to groups as well or just permissions / privs?

2023-04-06 20:50 UTC, jp-harvey commented
@odianosen we had an off-topic discussion about this class in the System Activity call yesterday. I've summarized the conversation in this discussion: https://github.com/ocsf/ocsf-schema/discussions/562

2023-04-27 18:23 UTC, closed without merging