#428 Add a Windows Events profile
ocsf/ocsf-schema pull request #551
Opened 2023-03-29 20:47 UTC by mr-splunk

Adds the long-awaited Windows Events profile. Kept it short and simple to start:

<img width="158" alt="image" src="https://user-images.githubusercontent.com/91983279/228663096-b537130d-ad51-4bf6-af39-b7a16c7df88f.png">

2023-03-29 23:33 UTC, rroupski requested changes

2023-03-29 23:33 UTC, rroupski commented on events/system/windows/registry_key.json
> +    "$include": [
The `registry_key_activity` extends the `system` class, so you don't need to include the `winlog` profile.

2023-03-30 00:27 UTC, pagbabian-splunk commented on dictionary.json
> +    },
I would avoid putting requirements in the dictionary, as they will be defined by how they are used in each class or profile.

2023-03-30 00:29 UTC, pagbabian-splunk commented
I thought we would have platform naming, e.g. Windows, rather than WinLog which is the caption in the code (vs. Windows Events which is the popup caption in the screen shot).  Also, I would avoid camel case as we don't use it anywhere.  Can we make the profile name `Windows`?

2023-03-30 15:32 UTC, awhite456 commented
> I thought we would have platform naming, e.g. Windows, rather than WinLog which is the caption in the code (vs. Windows Events which is the popup caption in the screen shot). Also, I would avoid camel case as we don't use it anywhere. Can we make the profile name `Windows`?

This profile really only adds support for Windows Event Log messages, it doesn't really provide any general Windows functionality. I think we discussed this on the call before you were able to join

2023-03-30 15:38 UTC, awhite456 reviewed
Looks good once other feedback is addressed

2023-03-30 15:38 UTC, awhite456 commented on profiles/winlog.json
> +      "description": "The service that logged the Windows event. Ex: 'Microsoft-Windows-Security-Auditing' (xml) or Microsoft Windows security auditing. (multiline).",
Nit - Either both examples should have quotes or neither

2023-03-30 15:38 UTC, awhite456 commented on dictionary.json
> +    },
+1, shouldn't have requirements here

2023-03-30 15:41 UTC, mr-splunk commented on events/system/windows/registry_key.json
> +    "$include": [
Removed the winlog include

2023-03-30 15:44 UTC, mr-splunk commented on profiles/winlog.json
> +      "description": "The service that logged the Windows event. Ex: 'Microsoft-Windows-Security-Auditing' (xml) or Microsoft Windows security auditing. (multiline).",
Resolved via fa674a279f312dfb30dbe78101813f58ccd3278f

2023-03-30 15:52 UTC, awhite456 approved these changes
lgtm

2023-03-30 17:28 UTC, pagbabian-splunk commented on dictionary.json
> +      "type": "integer_t"
Can we move the very specific Windows description to the profile specific use and make the dictionary description more general purpose?

2023-03-30 17:31 UTC, mr-splunk commented on profiles/winlog.json
> +  "caption": "WinLog",
Changed via 21ece1036c242038519d28dd0e03bf923a305eca

2023-03-30 17:37 UTC, mr-splunk commented on dictionary.json
> +      "type": "integer_t"
Take a look at changes on this commit: 38a312db06277aab5706a9da2f8d4372b487c005

2023-03-30 17:51 UTC, pagbabian-splunk approved these changes

2023-03-30 17:57 UTC, rroupski requested changes

2023-03-30 17:57 UTC, rroupski commented on dictionary.json
> +      "type": "integer_t"
to make the version useful for other products (general purpose), the type should be string, not an integer.

2023-03-30 18:00 UTC, mr-splunk commented on dictionary.json
> +      "type": "integer_t"
Changed to `string_t` via commit 70dc6e26d73f25cf2d74846a701c59ab5afef3af

2023-03-30 18:02 UTC, rroupski approved these changes

2023-03-30 18:02 UTC, pagbabian-splunk commented on dictionary.json
> +      "type": "integer_t"
Good catch.

2023-03-30 18:03 UTC, pagbabian-splunk approved these changes

2023-04-03 22:08 UTC, jp-harvey approved these changes
LGTM

2023-04-04 14:22 UTC, merged