Move Api Activity from the Access Control category to the Application Activity category
ocsf/ocsf-schema pull request #559
Opened 2023-04-05 21:45 UTC by pagbabian-splunk

Per Weekly discussion and #555 Discussion

2023-04-05 21:49 UTC, pagbabian-splunk commented
Note: I used uid 3 instead of 2 as there is a pending PR coming from @maxhotta for Application LIfecycle that was marked as uid 2.

2023-04-05 21:54 UTC, rroupski requested changes

2023-04-05 21:54 UTC, rroupski commented on events/application/api.json
> +    "category": "application",
In this case (extending the `application` class, which defines the category value), the `category` field is redundant, so you can remove it.

2023-04-06 16:21 UTC, maxhotta approved these changes

2023-04-06 17:45 UTC, mr-splunk approved these changes

2023-04-06 17:52 UTC, rroupski approved these changes

2023-04-06 17:52 UTC, merged