Promoted the Discovery category from dev extension, and replaced the Inventory / Configuration category
ocsf/ocsf-schema pull request #560
Opened 2023-04-05 22:22 UTC by pagbabian-splunk

Created new events/discovery folder, moved existing inventory classes to the discovery category with fixups.

2023-04-05 23:54 UTC, rroupski approved these changes

2023-04-06 16:31 UTC, floydtree requested changes

2023-04-06 16:31 UTC, floydtree commented on events/discovery/discovery.json
>    "description": "The Device Inventory/Configuration event is a generic event that defines a set of attributes available in the inventory/configuration events. As a generic event, it could be used to
Although this class won't be visible in the server, might be good to update the description to match the caption.

2023-04-06 18:15 UTC, pagbabian-splunk commented on events/discovery/discovery.json
>    "description": "The Device Inventory/Configuration event is a generic event that defines a set of attributes available in the inventory/configuration events. As a generic event, it could be used to
Oops, yes, I'll fix that.

2023-04-06 18:46 UTC, floydtree approved these changes

2023-04-06 18:53 UTC, rroupski approved these changes

2023-04-06 19:02 UTC, jasonbreimer approved these changes

2023-04-06 19:43 UTC, merged