Add the Application Lifecycle event.
ocsf/ocsf-schema pull request #561
Opened 2023-04-05 23:54 UTC by maxhotta

PR for merging the Application Lifecycle Event per discussion [552](https://github.com/ocsf/ocsf-schema/discussions/552)

2023-04-06 19:01 UTC, rroupski approved these changes

2023-04-07 15:29 UTC, mr-splunk approved these changes

2023-04-07 18:09 UTC, floydtree requested changes

2023-04-07 18:09 UTC, floydtree commented on events/application/application_lifecycle.json
> +      "description": "The product that initiated the Application Lifecycle activity.",
This might need some clarification, unclear from the description what the intended use-case is

2023-04-11 22:37 UTC, maxhotta commented on events/application/application_lifecycle.json
> +      "description": "The product that initiated the Application Lifecycle activity.",
Perhaps we can change the description to something like, "The product originating the installation, removal, start, or stop event.".  For example, when a security product logs a start event after a machine reboot.  Open to any suggestions.

2023-04-18 01:04 UTC, pagbabian-splunk approved these changes

2023-04-18 16:08 UTC, mr-splunk approved these changes

2023-04-18 18:50 UTC, rroupski approved these changes

2023-04-18 18:52 UTC, rroupski approved these changes

2023-04-18 18:52 UTC, merged