Remove the winlog profile
ocsf/ocsf-schema pull request #563
Opened 2023-04-06 22:29 UTC by rroupski

Add event_code, log_name, log_provider, log_version to the metadata

Signed-off-by: Roumen Roupski <rroupski@gmail.com>

2023-04-06 23:05 UTC, pagbabian-splunk approved these changes

2023-04-07 12:57 UTC, floydtree requested changes

2023-04-07 12:57 UTC, floydtree commented on dictionary.json
> +      "description": "The logging subsystem the product uses for the event. For example, Windows logging subsystem: Channel=Security (xml) or LogName=Security (multiline).",
Looking at the description of this field, it appears one can use `metadata.product.feature.name` for this, don't see a need for a duplicate field.
We'll be creating duplication and confusion as a consequence of adding it.

2023-04-07 12:57 UTC, floydtree commented on dictionary.json
> +    "log_provider": {
Same as above, but this time one can use `metadata.product.name`

2023-04-07 12:57 UTC, floydtree commented on objects/metadata.json
> +    "log_version": {
Adding `log_version` to the `product` object instead of the base of metadata would make more sense I think.
`product` definition in `metadata` is `The product that reported the event.`

2023-04-07 15:26 UTC, mr-splunk approved these changes

2023-04-07 16:04 UTC, pagbabian-splunk commented on dictionary.json
> +      "description": "The logging subsystem the product uses for the event. For example, Windows logging subsystem: Channel=Security (xml) or LogName=Security (multiline).",
I'm not sure that's true.  The Product/Feature logs into a log which would have a different name than the feature.  E.g. Application Log, Security Log, System Log, Directory Service Log, DNS Server Log, File Replication Service Logs.  These aren't the same as Product Features that are the source of the events in those logs.

2023-04-07 17:44 UTC, rroupski commented on objects/metadata.json
> +    "log_version": {
There is a difference between the product and log format version. The log_version is the event schema version that the product uses to log the events, so many product versions could use same log schema/format version.

2023-04-07 17:49 UTC, floydtree commented on objects/metadata.json
> +    "log_version": {
I don't think you understood my point, to re-iterate, I am asking to move `log_version` inside the product object instead of being in the base of `metadata`. I am **not** asking to remove that field. It will be a cleaner, consistent experience, but I'll leave it you.

2023-04-07 17:52 UTC, rroupski commented on dictionary.json
> +      "description": "The logging subsystem the product uses for the event. For example, Windows logging subsystem: Channel=Security (xml) or LogName=Security (multiline).",
@mr-splunk correct me if I am wrong. In the example, the logging subsystem, aka log name is `Security`. The example shows where the name is found, the Channel, and the format of the original data (xml or multiline). Maybe that's too much windows-specific details in this example.

2023-04-10 16:30 UTC, mr-splunk commented on dictionary.json
> +      "description": "The logging subsystem the product uses for the event. For example, Windows logging subsystem: Channel=Security (xml) or LogName=Security (multiline).",
This field was originally created for the Windows profile, so the definition is specific to Windows. If broadening this field to OCSF core, it may be better to keep it less specific to Windows.

2023-04-14 15:53 UTC, pagbabian-splunk approved these changes

2023-04-14 16:01 UTC, mr-splunk approved these changes

2023-04-14 17:32 UTC, merged