Issue 557
ocsf/ocsf-schema pull request #564
Opened 2023-04-07 16:45 UTC by Aniak5

#557 
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/6465263/230645931-a5226c09-c278-4c5b-aebb-45f1e215c523.png">

2023-04-07 16:55 UTC, rroupski requested changes

2023-04-07 16:55 UTC, rroupski commented on objects/account.json
> +      "type",
I think we don't need `type` and `type_id` in the constraints. The type_id should be required and the account must have a `name` or `uid` (or both) to identify the account.

2023-04-07 16:55 UTC, rroupski commented on objects/account.json
> +      "requirement": "recommended"
it should be required.

2023-04-07 16:55 UTC, rroupski commented on objects/account.json
> +      "requirement": "optional"
It should be recommended

2023-04-07 16:59 UTC, Aniak5 commented on objects/account.json
> +      "type",
Makes sense

2023-04-07 17:04 UTC, floydtree commented on objects/account.json
> +      "requirement": "recommended"
I disagree, it shouldn't be required. `account` object will be used in the `resource` object, where account type information will be not necessarily available. Assigning it as unknown, basically means we are adding more data to an object where it's not necessary. Leaving it as recommended is appropriate.

This goes to my original argument about an account object not being necessary as discussed in https://github.com/ocsf/ocsf-schema/issues/557

2023-04-07 17:05 UTC, floydtree commented on objects/account.json
> +      "type",
Having `name` & `uid` in constraints makes sense. Both cannot be required.

2023-04-07 17:07 UTC, floydtree requested changes

2023-04-07 17:07 UTC, floydtree commented on dictionary.json
> -          "caption": "AWS IAM User"
We'll need to add `AWS Account`  to the enum as well. It would be a separate entity when compared to an IAM user/role

2023-04-07 17:08 UTC, floydtree requested changes

2023-04-07 17:08 UTC, floydtree commented on objects/account.json
> +      "requirement": "required"
Please see my comment here - https://github.com/ocsf/ocsf-schema/pull/564#discussion_r1160837313

2023-04-07 17:36 UTC, rroupski commented on objects/account.json
> +      "requirement": "recommended"
I this case, use the Unknown or Other.

2023-04-07 17:38 UTC, rroupski approved these changes

2023-04-07 17:44 UTC, floydtree commented on objects/account.json
> +      "requirement": "recommended"
Yes, feel free to do so. It shouldn't be required though.

2023-04-10 16:32 UTC, mr-splunk submitted a review, later dismissed

2023-04-12 17:14 UTC, rroupski commented on objects/account.json
> +      "type",
The type of the account must be required, otherwise what would be the difference between missing `type_id` and `type_id=Unknown`?

It also unnecessary complicates the queries:  `account.type_id != null and account.type_id==3` vs `account.type_id==3`

2023-04-12 17:31 UTC, pagbabian-splunk commented on objects/account.json
> +      "requirement": "recommended"
For consistency, we have `type_id` to be Required throughout the schema.  It is a small increase in size for the nominal representation but for storage or binary transmission, it should be negligible.  Let's stay consistent and make it Required.

2023-04-13 22:22 UTC, rroupski approved these changes

2023-04-14 14:51 UTC, mr-splunk approved these changes

2023-04-14 14:51 UTC, merged