Add org_unit,org_uid, org_name to account/user objects
ocsf/ocsf-schema pull request #576
Opened 2023-04-18 15:51 UTC by Aniak5

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/6465263/232832639-1a475600-79d6-415e-98da-2e7581ec1ce9.png">

#557

2023-04-18 16:01 UTC, mr-splunk submitted a review, later dismissed

2023-04-18 18:35 UTC, rroupski requested changes

2023-04-18 18:35 UTC, rroupski commented on dictionary.json
> +      "description": "The name of the organizational unit, within an organization.  For example, Finance, IT, R&D",
nitpick: missing `.` end the end of the description.

2023-04-18 21:41 UTC, Aniak5 commented on dictionary.json
> +      "description": "The name of the organizational unit, within an organization.  For example, Finance, IT, R&D",
Oops, good catch!

2023-04-19 22:38 UTC, rroupski commented
Should we use the new organization object?

2023-04-19 22:48 UTC, Aniak5 commented
> Should we use the new organization object?

Yup, I will wait until @pagbabian-splunk PR is merged.

2023-04-28 16:22 UTC, closed without merging