Created Organization object, and org, ou_name, ou_uid attributes.
ocsf/ocsf-schema pull request #582
Opened 2023-04-19 21:48 UTC by pagbabian-splunk

There are four organization related attributes that merit an object.  Note the org_name, org_uid, org_unit attributes have not been removed or replaced with this PR.

2023-04-19 21:59 UTC, Aniak5 commented on dictionary.json
>        "type": "string_t"
Should we get rid of `org_name` and `org_uid`? Though then we need to replace uses of them with the `org` object.

2023-04-19 22:12 UTC, rroupski requested changes

2023-04-19 22:12 UTC, rroupski commented on dictionary.json
>        "description": "The name of the organizational unit, withiin an organization.  For example, Finance, IT, R&D",
typo in `withiin`

2023-04-19 22:12 UTC, rroupski commented on dictionary.json
> +      "description": "The name of the organizational unit, withiin an organization.  For example, Finance, IT, R&D",
typo in `withiin`

2023-04-19 22:12 UTC, rroupski commented on objects/organization.json
> +{
where are we going to use this object? Replace the existing org_unit, org_name, and org_uid?

2023-04-24 17:24 UTC, rroupski commented on dictionary.json
> +    "ou_name": {
The ou_name has the caption and description as org_unit, is that correct?

2023-04-24 22:19 UTC, pagbabian-splunk commented on objects/organization.json
> +{
Yes. That was what we discussed since they show up together. I didn't remove the other ones yet as that would be breaking and hadn't gotten consensus

2023-04-24 22:20 UTC, pagbabian-splunk commented on dictionary.json
> +    "ou_name": {
Yes correct. OU = Org Unit

2023-04-25 15:35 UTC, Aniak5 approved these changes

2023-04-27 23:37 UTC, Aniak5 approved these changes

2023-04-28 16:05 UTC, rroupski submitted a review, later dismissed

2023-04-28 16:21 UTC, Aniak5 approved these changes

2023-04-28 16:22 UTC, rroupski submitted a review, later dismissed

2023-04-28 17:05 UTC, rroupski approved these changes

2023-04-28 17:07 UTC, Aniak5 approved these changes

2023-04-28 18:32 UTC, floydtree commented
Do you want to remove `org_unit` and `org_uid`from the dictionary and replace their current usage in the user, cloud, device objects with the new `org` object?

2023-04-28 18:39 UTC, jp-harvey requested changes

2023-04-28 18:39 UTC, jp-harvey commented on dictionary.json
> +      "caption": "Org Unit ID",
This change is a little confusing to me. In the dictionary we have `org` defined as the organization (the O in x500 speak presumably), and `org_unit` defined as the `OU` in x500 speak. Shouldn't this remain how it was, and a new `org_unit_id` be added as the identified for the `OU`?

Actually I just realized after looking further we have `ou_uid` already, so I think this is referring to the `O` uid, and should be reverted?

2023-04-28 18:39 UTC, jp-harvey commented on dictionary.json
> +    "ou_name": {
An `O` and an `OU` are different but this defines them as the same, I think this was a mistake?

2023-04-28 20:17 UTC, rroupski commented
> Do you want to remove `org_unit` and `org_uid`from the dictionary and replace their current usage in the user, cloud, device objects with the new `org` object?

@floydtree yes, that is goal -- remove the org_uid/org_name/org_unit attributes and use the `org` object.

2023-04-28 20:27 UTC, floydtree commented
> > Do you want to remove `org_unit` and `org_uid`from the dictionary and replace their current usage in the user, cloud, device objects with the new `org` object?
> 
> @floydtree yes, that is goal -- remove the org_uid/org_name/org_unit attributes and use the `org` object.

Okay, then looks good. (assuming there's followup PR that removes them from dict and updates the affected object)

2023-04-28 20:33 UTC, floydtree approved these changes

2023-04-28 21:41 UTC, jp-harvey commented on dictionary.json
> +      "caption": "Org Unit ID",
Ok that makes more sense.

2023-04-28 21:42 UTC, jp-harvey approved these changes

2023-04-28 21:42 UTC, merged