Add container profile to allow container context to be applied to processes
ocsf/ocsf-schema pull request #583
Opened 2023-04-19 21:55 UTC by awhite456

Prior to the container profile, it was not possible to associate a process with its container. With the container profile enabled, each `process` object gains a `container` field, where details about the container the process is executing inside of can be provided. This is useful when monitoring Kubernetes clusters, where multiple containers can be executing on the one host.

2023-04-19 22:01 UTC, pagbabian-splunk approved these changes

2023-04-19 22:31 UTC, rroupski requested changes

2023-04-19 22:31 UTC, rroupski commented on dictionary.json
> +    "exposed_port": {
since the attribute is an array ( is_array: true), rename `exposed_port` as `exposed_ports`

2023-04-19 22:31 UTC, rroupski commented on dictionary.json
> +      "description": "The IP port number exposed by container. For example 0.0.0.0:49155-> <<exposed_port>>/tcp",
Use plural "The IP port **numbers** ...."

2023-04-19 22:31 UTC, rroupski commented on dictionary.json
> +      "description": "The IP port number exposed by container. For example 0.0.0.0:49155-> <<exposed_port>>/tcp",
If the example is an example of the actual data, then it is incorrect. It should be `[80, 443]`. The `port_t` is an `integer` value.

2023-04-19 22:31 UTC, rroupski commented on dictionary.json
> +    "pod_id": {
`pod_id` should be renamed as `pod_uid` or if it is always uuid, then it should be `pod_uuid` of type `uuid_t`.

I found this data:
```json
    "resource": {
        "type": "gke_container",
        "labels": {
          "zone": "us-central1-a",
          "pod_id": "1138528c-c36e-11e9-a1a7-42010a800198",
          "project_id": "auto-scaling-springboot",
          "cluster_name": "load-test",
          "container_name": "",
          "namespace_id": "f0965889-c36d-11e9-9e00-42010a800198",
          "instance_id": "3962380509873542383"
        }
      }
```

2023-04-19 22:31 UTC, rroupski commented on dictionary.json
> +    "runtime": {
perhaps we can use enum?

2023-04-19 22:31 UTC, rroupski commented on events/system/system.json
> +      "profiles/container.json"
We don't want the `container` attribute in the class, right? If no, then remove: "profiles/container.json"

2023-04-19 22:31 UTC, rroupski commented on profiles/container.json
> +  "annotations": {
The `container` attributes are used in the process object, thus you can remove the annotations. Note, the object attributes don't use the `group` property.

2023-04-20 15:43 UTC, awhite456 commented on dictionary.json
> +      "description": "The IP port number exposed by container. For example 0.0.0.0:49155-> <<exposed_port>>/tcp",
Took out the example, this should be pretty obvious.

2023-04-20 15:44 UTC, awhite456 commented on dictionary.json
> +    "pod_id": {
Good idea, from what I can tell you are right that pod id's are always UUIDs

2023-04-20 16:09 UTC, rroupski approved these changes

2023-04-20 17:17 UTC, mr-splunk approved these changes

2023-04-20 19:11 UTC, awhite456 commented on dictionary.json
> +      "description": "The IP port numbers exposed by container.",
The container itself will have ports exposed as part of it's configuration, such as via the `EXPOSE` command in Docker. This is what this field intends to represent.

As you point out however, just because the container exposes that port, it does make it accessible - the orchestrator has to map that exposed port to an interface (eg a `service` in K8s). I think it makes sense for those mappings to be in the orchestrator logs - which I'm not sure we model just yet.

2023-04-20 19:55 UTC, awhite456 commented on dictionary.json
> +      "description": "The IP port numbers exposed by container.",
JP and I talked offline about this - container definitions can expose ports, and orchestrators can map those ports to external interfaces. It is not clear without delving into a potential container lifecycle activity class what information would be required here to provide enough information to satisfy both view points, so going to remove this field for now.

2023-04-20 21:42 UTC, jp-harvey commented on dictionary.json
> +      "description": "The IP port numbers exposed by container.",
For refernce, OCI (as an example) does not define ports, so we need to determine at a future point where they should be in OCSF: https://github.com/opencontainers/runtime-spec/issues/178

2023-04-20 21:43 UTC, jp-harvey approved these changes
LGTM

2023-04-21 18:46 UTC, mr-splunk requested changes

2023-04-21 18:46 UTC, mr-splunk commented on dictionary.json
> +      "description": "The container information.",
Is it possible to get a more discreet description for `container`? For instance, the `container.json` in its description includes this verbiage:

```...an instance of a specific container. A container is a prepackaged, portable system image that runs isolated on an existing system using a container runtime like containerd.```

2023-04-24 17:19 UTC, rroupski approved these changes

2023-04-25 19:03 UTC, awhite456 commented on dictionary.json
> +      "description": "The container information.",
Updated this previous definition to match the new one I wrote in the container profile

2023-04-27 16:41 UTC, Aniak5 approved these changes

2023-04-27 16:49 UTC, rroupski approved these changes

2023-04-27 18:09 UTC, jp-harvey submitted a review, later dismissed

2023-04-27 18:29 UTC, merged