Add Linux platform extension to add support for linux_users profile
ocsf/ocsf-schema pull request #584
Opened 2023-04-19 22:30 UTC by awhite456

The linux_users profile adds additional fields to the `process` object to support the various standard user information that is provided, such as `auid`, `euid`, `egid` and `gid`.

This is done via a Linux platform extension to keep the Linux-specific information out of the core schema

2023-04-19 22:30 UTC, awhite456 commented on extensions/linux/extension.json
> +  "uid": 998
What convention do we want to set for numbering these?

2023-04-19 22:31 UTC, awhite456 commented on extensions/linux/objects/process.json
> +    "extends": "process",
I'm not sure if this is a browser bug, but this `process` object seems to overwrite the original - any fields added here show up, regardless of whether the extension is enabled.

2023-04-19 22:36 UTC, rroupski commented on extensions/linux/extension.json
> +  "uid": 998
I think since we want to define the Linux extension as a platform, using 998 is ok.

BTW, I think we don't need to add the Linux extension right now. It does not add any new classes. Are you thinking of adding classes to the Linux extension?

2023-04-19 23:11 UTC, rroupski commented on extensions/linux/objects/process.json
> +    "extends": "process",
yes, it is a bug that I shall fix soon.

2023-04-19 23:18 UTC, rroupski requested changes

2023-04-19 23:18 UTC, rroupski commented on extensions/linux/dictionary.json
> +      "type": "user"
I thought the type would be integer, not an object?

2023-04-19 23:18 UTC, rroupski commented on extensions/linux/profiles/linux_users.json
> +    "annotations": {
Group annotation is not applicable to object attributes, so it should be removed.

2023-04-19 23:18 UTC, rroupski commented on extensions/linux/profiles/linux_users.json
> +          "description": "The group under which this process is running",
nitpick: missing `.` at the end of the description.

2023-04-19 23:18 UTC, rroupski commented on extensions/linux/profiles/linux_users.json
> +    "description": "The attributes that Linux uses to identify user information",
nitpick: missing `.` at the end of the description.

2023-04-20 17:19 UTC, mr-splunk approved these changes

2023-04-24 17:17 UTC, rroupski approved these changes

2023-04-27 16:10 UTC, Aniak5 approved these changes

2023-04-27 16:52 UTC, merged