Update the Authentication class
ocsf/ocsf-schema pull request #597
Opened 2023-04-29 03:42 UTC by pagbabian-splunk

Refer to Issue #567 .
Added an `account`, `certificate`, and `service` attributes.
Removed `mfa` from `Session`.
Renamed `mfa` to `is_mfa` for consistency with other boolean_t attributes.
Added a constraint for `dst_endpoint` and `user`
Update some descriptions.

2023-05-01 12:51 UTC, floydtree requested changes

2023-05-01 12:51 UTC, floydtree commented on events/access_control/authentication.json
> +    "account": {
Do we need an additional account object at the base level of the class? the `user` object *used as the subject of authentication) already has a nested account object which will serve the same purpose. This could be a duplication

2023-05-01 15:58 UTC, pagbabian-splunk commented on events/access_control/authentication.json
> +    "account": {
Good catch Rajas.  I will remove it, and change the description for `user` to "The subject (user/role **or account**) to authenticate."

2023-05-01 17:17 UTC, floydtree approved these changes

2023-05-01 18:27 UTC, mr-splunk approved these changes
LGTM

2023-05-01 19:41 UTC, odianosen commented
As per #597, I agree that is_remote should be part of `session` rather than `authentication` class. But that change wasn't included in this PR?

2023-05-01 19:42 UTC, odianosen requested changes
As per https://github.com/ocsf/ocsf-schema/pull/597, shouldn't `is_remote` be changed to be part of session rather than authentication class?

2023-05-01 23:06 UTC, pagbabian-splunk commented
> As per #597, shouldn't `is_remote` be changed to be part of session rather than authentication class?

I discussed with @rroupski last week and we felt that it could remain in the Auth class w/ fewer breaking changes.  If you or others feel it should be part of the `Session` object I can move it.

2023-05-02 19:43 UTC, floydtree approved these changes

2023-05-03 14:25 UTC, odianosen approved these changes

2023-05-04 20:59 UTC, mr-splunk approved these changes

2023-05-04 20:59 UTC, merged