Rename and update Authorization class to Authorize Session
ocsf/ocsf-schema pull request #602
Opened 2023-05-03 01:18 UTC by pagbabian-splunk

The name of the class was too general, it now describes the activities more specifically.

It was missing key attributes, and their uses were adjusted.

2023-05-03 14:32 UTC, odianosen requested changes

2023-05-03 16:15 UTC, Aniak5 approved these changes

2023-05-03 16:15 UTC, pagbabian-splunk commented on events/access_control/authorization.json
> +      "requirement": "required"
Good call on that, I've updated with a Recommended requirement, and slightly reworded description for session.

2023-05-04 16:25 UTC, mr-splunk approved these changes

2023-05-05 16:49 UTC, odianosen approved these changes
Looks good to me.

2023-05-05 16:54 UTC, merged