Updated the description for the user's account, and the uid example.
ocsf/ocsf-schema pull request #620
Opened 2023-05-12 17:36 UTC by pagbabian-splunk

Refer to Issue #572

2023-05-12 17:42 UTC, floydtree requested changes

2023-05-12 17:42 UTC, floydtree commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
ARN would be more appropriate for uuid, I would recommend leaving description of uid as is, and adding ARN in uuid desc.

2023-05-13 01:12 UTC, pagbabian-splunk commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
uuid is of the type for guids. arn would fail validation.

2023-05-15 13:03 UTC, floydtree commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
Interesting, never noticed till today that we have a specific data type for uuid. If that's the case, then the definition of uuid will have to be broadened, `128-bit universal unique identifier.` is quite narrow.

2023-05-15 15:17 UTC, pagbabian-splunk commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
GUIDs/UUIDs are important identifiers with a specific format that can be validated.  They are used extensively with Windows.  For example, from MS: "When a new domain user or group account is created, Active Directory stores the account's SID in the ObjectSID property of a User or Group object. It also assigns the new object a globally unique identifier (GUID), which is a 128-bit value that's unique not only in the enterprise, but also across the world. "

2023-05-15 15:37 UTC, floydtree commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
Agreed with your point, ARN's format might not fit how Windows defines a GUID, but ARNs are conceptually globally unique identifiers and are used as such.

2023-05-15 21:20 UTC, pagbabian-splunk commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
Seems we should discuss tomorrow.  AWS also has a Unique identifier, but it isn't the ARN, and it isn't a UUID either (akin to Windows with a SID and GUID):
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-unique-ids
### Unique identifiers
When IAM creates a user, user group, role, policy, instance profile, or server certificate, it assigns a unique ID to each resource. The unique ID looks like this:

AIDAJQABLZS4A3QDU576Q

For the most part, you use friendly names and [ARNs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-arns) when you work with IAM resources. That way you don't need to know the unique ID for a specific resource. However, the unique ID can sometimes be useful when it isn't practical to use friendly names.

In general, we recommend that you specify the ARN for the resource in your policies instead of its unique ID. However, every IAM user has a unique ID, even if you create a new IAM user that reuses a friendly name you deleted before. In the example, the old IAM user John and the new IAM user John have different unique IDs.

2023-05-16 14:14 UTC, floydtree commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
Right, but as you can see from the text in your link itself, ARNs are our preferred, easily accessible and utilized GUIDs.

Further, `uuid` is not used only in the context of a user, `uuid` are used for Device identifiers as well, which is again an ARN. Therefore, the example you noted doesn't apply.

Simply put, ARNs are GUIDs and are used as such.

2023-05-16 15:14 UTC, pagbabian-splunk commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
We are going to discuss on the call this morning.  UUIDs/GUDs are industry standard types (RFC 4122).

2023-05-17 18:21 UTC, pagbabian-splunk commented on objects/user.json
> +      "description": "The unique user identifier. For example, AWS PrincipalID, ARN, or Windows user SID."
Removed `uuid` from User, replaced with `alt_uid` (added to dictionary) and updated descriptions according to our discussion, and inspection of Windows Logon Attempt events (4648).

2023-05-17 18:56 UTC, pagbabian-splunk commented
Renamed `alt_uid` to be `uid_alt` per suggestion by @awhite456

2023-05-17 19:12 UTC, Aniak5 approved these changes
LGTM!

2023-05-17 19:25 UTC, floydtree approved these changes

2023-05-17 19:28 UTC, awhite456 commented on objects/user.json
> +      "description": "The unique user identifier. For example, the Windows user SID, ActiveDirectory DN or AWS user ARN, or ."
Nit - the description here has an extra "or" on the end

2023-05-17 19:31 UTC, awhite456 approved these changes

2023-05-17 19:31 UTC, pagbabian-splunk commented on objects/user.json
> +      "description": "The unique user identifier. For example, the Windows user SID, ActiveDirectory DN or AWS user ARN, or ."
will do

2023-05-17 19:31 UTC, mr-splunk approved these changes

2023-05-17 19:31 UTC, merged