Resource type object clean up, removal of data from base event
ocsf/ocsf-schema pull request #656
Opened 2023-05-30 17:54 UTC by floydtree

Relevant Issue - https://github.com/ocsf/ocsf-schema/issues/655
Cleaning up resource-type object hierarchy

Additionally - 
1. removing `data` from base_event as discussed in May 30th OCSF weekly call
2. replacing resources with web_resources in Web resource access activity class

2023-05-30 18:28 UTC, pagbabian-splunk approved these changes

2023-05-30 18:31 UTC, Aniak5 submitted a review, later dismissed
LGTM

2023-05-30 18:34 UTC, rroupski reviewed
Since we are making changes, we should rename `resource_type` as `type`.

2023-05-30 18:34 UTC, rroupski commented on events/application/web_resource_access_activity.json
> +    "web_resources": {
It used to be a single resource, and now it will be an array of resources. Is that correct?

2023-05-30 18:34 UTC, rroupski commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
By extending the resource, we are adding a new recommended attribute, `owner`. And more optional attributes: `criticality`, `data`, `group`, `labels`, `resource_type`, and `version`.  In addition, the `web_resource` already has `type` attribute, and by extending the `resource` we add `resource_type` as well. 

I think, this is a big change, and I am not sure what would be the benefit of it?

2023-05-30 18:53 UTC, floydtree commented on events/application/web_resource_access_activity.json
> +    "web_resources": {
That's correct.

2023-05-30 18:57 UTC, floydtree commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
`resource_type` is no longer present in the `resource` object, so there's no additional type attribute that will be added.

Agreed, extra descriptor fields will be added but that's the trade off we discussed in the call today, didn't we? You are correct, not all the descriptor fields will be available in all cases, therefore they are optional.

2023-05-30 20:18 UTC, rroupski commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
The main reason to extend an object is to **reuse** common attributes. In this case, we are [mostly] **adding** new attributes -- attributes that are probably not going to be used by windows resource.

Are we extending the `resource` object just because the `resource` and `win_resource` names are similar (which may imply some relationship)? 

For example, if we've used `win_desc` instead of `win_resource`, then should we extend the `resource` again?

2023-05-30 20:46 UTC, floydtree commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
I see your point, I think the idea is to logically bring all resource-type objects together to bring uniformity in such objects.

But if you think, Windows event logs OR EDR products generating events for windows resources will never have descriptors like labels, criticality, owner etc, then we can let win_resource be unique and not have it extend resource.

2023-05-30 22:58 UTC, pagbabian-splunk commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
I think we can tweak this a bit - put the common attrs in _resource, and then extend with `resource` and `win_resource` and `web_resource`.  We can change the `details` of `win_resource` to `data` to be consistent.

2023-05-31 13:02 UTC, floydtree commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
Regarding ` We can change the details of win_resource to data to be consistent.`

I am not changing it in this PR, I'll let @mr-splunk create a PR to adjust that object, wouldn't want to disrupt his usecases.

2023-05-31 16:03 UTC, rroupski requested changes

2023-05-31 16:03 UTC, rroupski commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
Based on the latest updates, the resource adds 4 more attributes to the `win_resource` object + 2 more if the cloud profile is checked. None of those attributes is applicable to the `win_resource` object. Therefore, we should not extend the resource.

2023-05-31 16:18 UTC, floydtree commented on extensions/windows/objects/win_resource.json
> +  "extends": "resource",
Taking it offline, we seem to be talking in circles

2023-05-31 16:52 UTC, rroupski approved these changes

2023-05-31 16:58 UTC, mr-splunk approved these changes

2023-05-31 17:02 UTC, Aniak5 approved these changes

2023-05-31 17:02 UTC, merged