Issue-672: Extend network event in network file activity
ocsf/ocsf-schema pull request #677
Opened 2023-06-26 15:40 UTC by Aniak5

- Make network file activity more generic and extend network event class. This will add `dst_endpoint`, `connection_info` and `traffic` to the event class. 
- Change the requirement options on the `connection_info` and `dst_endpoint`.

#672 
<img width="866" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/6465263/4d9c3827-83d6-4fa7-869c-07d423ea5222">

<img width="1391" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/6465263/ef02e707-e865-4908-a363-a0dd80b2f9f4">

2023-06-26 16:25 UTC, rroupski requested changes

2023-06-26 16:25 UTC, rroupski commented on events/network/file_activity.json
> +      "group": "primary"
nickpick: you can remove the group, it is the same as defined in the network activity class.

2023-06-26 16:25 UTC, rroupski commented on events/network/file_activity.json
> +      "group": "primary",
nickpick: you can remove the group, it is the same as defined in the network activity class.

2023-06-26 16:34 UTC, Aniak5 commented on events/network/file_activity.json
> +      "group": "primary"
Good point! will do

2023-06-27 16:03 UTC, rroupski approved these changes

2023-07-03 18:55 UTC, pagbabian-splunk approved these changes

2023-07-06 16:27 UTC, mr-splunk approved these changes

2023-07-06 16:27 UTC, merged