Adding CWE object to the framework & in the vulnerability object
ocsf/ocsf-schema pull request #678
Opened 2023-06-27 18:06 UTC by floydtree

Picking up changes proposed in https://github.com/ocsf/ocsf-schema/pull/558.
Related issue: https://github.com/ocsf/ocsf-schema/issues/676

* Keeping in all the changes from the original PR. (new cwe object, replacing individual cwe fields with cwe object)
* Additionally, added a constraint of at_least_one(cve, cwe) in the vulnerability object.

This is a backwards incompatible change since, cwe_uid has been removed from the dictionary.

2023-06-27 21:15 UTC, rroupski requested changes

2023-06-27 21:15 UTC, rroupski commented on objects/cwe.json
> +{
IMO, we should add `caption` attribute, so we can have the short description of the CWE in the event data. It will make the data more readable and user-friendly. For example:
```json
{
  "uid": "CWE-787",
  "caption": "Out-of-bounds Write",
  "src_url": "https://cwe.mitre.org/data/definitions/787.html"
}
```

2023-06-27 21:15 UTC, rroupski commented on objects/cwe.json
> +    "cwe_url": {
I'd recommend using an exciting URL string attribute, such as `src_url` or `url_string`. I like the `src_url` attribute, it is shorted than `url_string`, and it seems relevant to the context (points to the source of the weakness information).
Also, we avoid the name repetition -- `cwe.cwe_url` vs `cwe.src_url`.

2023-06-27 21:15 UTC, rroupski commented on objects/cve.json
> +      "description": "The Common Weakness Enumeration (CWE) is a community-developed list of software and hardware weakness types. The CWE Specification provides a common language of discourse for di
We should use the description from the dictionary.

2023-06-27 21:21 UTC, rroupski commented on objects/vulnerability.json
The `title` of the vulnerability should be a `required` attribute, not `optional`.
The same comment for the `packages` attribute, it should be at least recommended.

2023-06-28 22:17 UTC, rroupski approved these changes

2023-07-03 18:53 UTC, pagbabian-splunk approved these changes

2023-07-06 18:08 UTC, merged