Filewall Profile Implementation
ocsf/ocsf-schema pull request #680
Opened 2023-06-28 23:32 UTC by adplotzk

The following is an example AWS WAF log conforming to the firewall profile as applies to 4002.

    {
        "activity_id": 1,
        "activity_name": "Get",
        "category_name": "Network Activity",
        "category_uid": 4,
        "class_name": "HTTP Activity",
        "class_uid": 4002,
        "type_name": "HTTP Activity: Get",
        "type_uid": 400503,
        "time": 1576280412771,
        "metadata": {
	        "product": {
		        "name": "AWS WAF",
		        "vendor_name": "AWS"
	        },
	        "feature": {
		        "uid": "arn:aws:wafv2:ap-southeast-2:111122223333:regional/webacl/STMTest/1EXAMPLE-2ARN-3ARN-4ARN-123456EXAMPLE"
	        },
	        "log_version": "1",
	        "profiles": [firewall],
	        "version": "1.0.0-rc.3",
	        "labels": [
		        {
			        "name": "value"
		        }
	        ]
        },
        "src_endpoint": {
	        "ip": "1.1.1.1",
	        "location": {
		        "country": "AU"
	        }
        },
        "http_request": {
	        "args": "",
	        "version": "HTTP/1.1",
	        "method": "GET",
	        "uid": "rid",
	        "user_agent": "curl/7.61.1",
	        "url": {
		        "hostname": "localhost:1989",
		        "path": "/myUri",
		        "url_string": "localhost:1989/myUri"
	        },
	        "headers": [
		        {
			        "name": "Accept",
			        "value": "*/*"
		        },
		        {
			        "name": "x-stm-test",
			        "value": "10 AND 1=1"
		        }
	        ]
        },
        "rule": {
	        "action": "BLOCK",
	        "uid": "STMTest_SQLi_XSS",
	        "type": "REGULAR",
	        "condition": "SQL_INJECTION",
	        "sensitivity": "HIGH",
	        "location": "HEADER",
	        "matched_data": [
		        "10",
		        "AND",
		        "1"
	        ]
        },
        "unmapped": {
	        "httpSourceName": "APIGW",
	        "httpSourcId": "-"
        }
    }

2023-06-28 23:47 UTC, rroupski commented
If I understand correctly, the purpose of this PR is to define a `firewall` profile and apply it to the existing `rule` object, then there is already a good example to follow. See [Linux profile](https://github.com/ocsf/ocsf-schema/blob/main/extensions/linux/profiles/linux_users.json) and how it is used to extend the existing [process](https://github.com/ocsf/ocsf-schema/blob/main/extensions/linux/objects/process.json) object.

2023-06-28 23:59 UTC, adplotzk commented
> If I understand correctly, the purpose of this PR is to define a `firewall` profile and apply it to the existing `rule` object, then there is already a good example to follow. See [Linux profile](https://github.com/ocsf/ocsf-schema/blob/main/extensions/linux/profiles/linux_users.json) and how it is used to extend the existing [process](https://github.com/ocsf/ocsf-schema/blob/main/extensions/linux/objects/process.json) object.

Linux here is an extension not a profile. 

I've implemented my approach in a way that the cloud profile modified the resource_details object.

2023-06-29 00:01 UTC, adplotzk commented
you can see here ---> https://github.com/ocsf/ocsf-schema/blob/main/objects/resource_details.json

2023-06-29 12:54 UTC, floydtree requested changes
General comment before reviewing the actual content - better not to change indentation in the files, for e.g. it's causing the entire `dictionary.json` file to be treated as "modified", making it impossible to review what actually changed. This applies to all the files you have changed. Also, for consistency, better to keep the indentation in sync with other json definitions.

It appears there are merge conflicts, which need to be resolved.

2023-06-29 15:38 UTC, adplotzk reviewed
these changes have been implemented

2023-06-29 15:59 UTC, adplotzk commented
@floydtree @rroupski @mr-splunk All syntax has been updated + merge conflicts resolved.

2023-06-29 20:15 UTC, rroupski commented
@adplotzk did you follow the links in: See [Linux profile](https://github.com/ocsf/ocsf-schema/blob/main/extensions/linux/profiles/linux_users.json) and how it is used to extend the existing [process](https://github.com/ocsf/ocsf-schema/blob/main/extensions/linux/objects/process.json) object.

The [Linux profile](https://github.com/ocsf/ocsf-schema/blob/main/extensions/linux/profiles/linux_users.json) points to the **Linux user** profile, which is show as Linux profile on the profiles list. So, I was referring to the Linux profile, defined in the Linux extension.

2023-06-29 20:18 UTC, rroupski commented
> cloud profile modified resource_details object to include additional fields
> 
> 1. https://github.com/ocsf/ocsf-schema/blob/main/profiles/cloud.json
> 2. https://github.com/ocsf/ocsf-schema/blob/main/objects/resource_details.json
> 
> In a similar way my firewall profile modifies the existing rule object to include the additional fields.

I don't think that is a good example -- the cloud profile does not add additional attributes to the resource_detail.

2023-06-29 20:27 UTC, floydtree commented
> > cloud profile modified resource_details object to include additional fields
> > 
> > 1. https://github.com/ocsf/ocsf-schema/blob/main/profiles/cloud.json
> > 2. https://github.com/ocsf/ocsf-schema/blob/main/objects/resource_details.json
> > 
> > In a similar way my firewall profile modifies the existing rule object to include the additional fields.
> 

> I don't think that is a good example -- the cloud profile does not add additional attributes to the resource_detail.

It does add cloud specific attributes via the cloud profile - 
![Screen Shot 2023-06-29 at 4 24 20 PM](https://github.com/ocsf/ocsf-schema/assets/89877409/53b92ee6-c35f-4429-8bb7-c25b7ad7849d)

2023-06-29 20:29 UTC, rroupski commented
The issue that I see is that the profile does not list all the attribute it adds:

<img width="1095" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/2128145/6ba3892f-fc14-4332-a4af-c51b90b29bf7">

Compare to the added rule attributes:

<img width="1095" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/2128145/e36007c4-5fed-4528-bbf2-51afda5ef290">

2023-06-29 20:43 UTC, floydtree commented
Yeah true, besides this PR I'll message you to talk about it. I like the simplicity and intuitive nature of the cloud profile on resource object method

2023-07-03 10:52 UTC, adplotzk commented
> The issue that I see is that the profile does not list all the attribute it adds:
> 
> <img alt="image" width="1095" src="https://user-images.githubusercontent.com/2128145/249889854-6ba3892f-fc14-4332-a4af-c51b90b29bf7.png">
> Compare to the added rule attributes:
> 
> <img alt="image" width="1095" src="https://user-images.githubusercontent.com/2128145/249890070-e36007c4-5fed-4528-bbf2-51afda5ef290.png">

Im currently running a local copy of the server as well but no profiles have these features. We should be be consistent across all existing profiles, and based on the current PR, it is in line with current OCSF standards. Lets please have a resolution for this ASAP.

2023-07-05 17:33 UTC, adplotzk commented
![image](https://github.com/ocsf/ocsf-schema/assets/106110648/9fac2ade-caad-45ab-b88c-f96f8814c2e2)

@rroupski @pagbabian-splunk @floydtree

2023-07-11 15:53 UTC, rroupski requested changes

2023-07-11 15:53 UTC, rroupski commented on objects/firewall_rule.json
> +  "extends": "_entity",
We should extend the rule object to reuse the common attributes.

2023-07-11 16:39 UTC, mr-splunk approved these changes

2023-07-11 16:50 UTC, adplotzk commented on objects/firewall_rule.json
> +  "extends": "_entity",
complete

2023-07-11 16:56 UTC, adplotzk reviewed
changes have been implemented

2023-07-11 16:56 UTC, adplotzk reviewed
changes have been implemented

2023-07-11 16:59 UTC, rroupski approved these changes

2023-07-11 17:09 UTC, floydtree commented on objects/firewall_rule.json
> +    "status_code": {
This appears to be the base definition, this should rather be the description specific to this object - what is the status code in context of the firewall rule?

2023-07-11 17:10 UTC, floydtree commented on objects/firewall_rule.json
> +      "description": "The description of the event, as defined by the event source.",
Same as status_code

2023-07-11 17:15 UTC, floydtree commented on objects/firewall_rule.json
> +      "description": "The location in the request where the rule matched. For example: HIGH.",
Appears description is duplicated with rule_location attribute

2023-07-11 17:18 UTC, floydtree commented on dictionary.json
> +	  "is_array": true,
nit: unnecessary indent

2023-07-11 17:23 UTC, adplotzk commented on dictionary.json
> +	  "is_array": true,
indent removed - complete

2023-07-11 17:30 UTC, floydtree requested changes
Specific comments are in-line.

A general question regarding firewall_rule object - Is the idea to create new specific rule objects for different tools? For example, to support IPS type events, would we want a separate ips_rule? Why not use the same base rule object and add profiles for different tools? @rroupski 

Regarding this PR: I would recommend to create a new PR with these changes with precise commit messages & limited commits - this is to ensure our automated generation of release notes are actually helpful to the users. There are 38 commits in this PR, with generic commit messages, making it difficult to troubleshoot down the road.

2023-07-11 17:32 UTC, adplotzk commented on profiles/firewall.json
> +  "description": "The attributes that identify firewall attributes.",
description has been updated to be more clear.

2023-07-11 17:33 UTC, adplotzk commented on objects/firewall_rule.json
> +      "description": "The description of the event, as defined by the event source.",
updated status_code to be more clear.

2023-07-11 17:33 UTC, adplotzk commented on objects/firewall_rule.json
> +    "status_code": {
updated status_code to be more clear.

2023-07-11 17:34 UTC, floydtree commented
I would also recommend to edit the PR description and highlight what exactly has been changed, added, removed etc. This would help in generating clearer & cleaner release notes.

2023-07-11 17:41 UTC, closed without merging