[Draft] Proposal for Security Incident Findings class
ocsf/ocsf-schema pull request #682
Opened 2023-06-29 22:45 UTC by maxhotta

This is a draft proposal (PR) for a new Findings class for Security Incidents.
It includes the following:
- Security Incident (Create, Update, Close)
- Incident Associate : Binds events with Security Incidents

2023-07-11 17:24 UTC, rroupski requested changes
This PR adds 3 new classes: `conclusion`, `incident`, and `security_incident`, where `security_incident` **extends** `incident` and `incident` **extends** `conclusion`. 

The `incident` and the `conclusion` are “abstract” classes – they don't defined `activity_id`, thus they cannot be used as event classes. Since both are not extended by any other classes, we should put all attributes into a single class: `incident`.

To reduce the number of attributes in the `incident` class, we could add a new object `incident`.

2023-07-11 17:25 UTC, rroupski commented on dictionary.json
> +    "incident_url": {
It looks like the `incident_url` is not used. If so, then remove from the dictionary.

2023-07-13 16:21 UTC, rroupski commented
> but an incident could have multiple conclusions in the way conclusions are defined here (they are what findings are in fact). Therefore I wouldn’t combine what is in conclusion directly into incident, since incidents can have multiple findings (conclusions).

@pagbabian-splunk The `conclusion` class is defined and used just as a base class for the incident class, thus we cannot have multiple `conclusion`  associated with an incident (the `conclusion` is not defined as we did it in the Symantec SSIM).

2023-07-13 16:44 UTC, mr-splunk commented
Hi @Aniak5 , - Along the topic of `Endpoint` - saw a minor grammatical error in the description of the `Endpoint` observable in the `observable` object
```
The endpoint object describes an entity that has name, uid, and IP address.
should be
The endpoint object describes an entity that has a name, uid, and IP address.```

Is this something you could add to this PR?

2023-07-18 06:03 UTC, sfriedfertig commented
Don't Conclusion and Incident need UIDs?

2023-07-24 14:55 UTC, pagbabian-splunk commented
@rroupski-splunk I know that Conclusion is here a base class but in general, an incident can include many findings.  This class is just another incarnation of the current security_finding in my reading.  Incident should be reserved for a structure that can include multiple findings - it should not be a synonym for a finding itself.

2023-07-24 16:20 UTC, rroupski requested changes

2023-07-24 16:20 UTC, rroupski commented on dictionary.json
> +    "conclusion": {
If the `conclusion` attribute is not used, then we should not define it in the dictionary.

2023-08-01 15:16 UTC, irakledibm reviewed
We may want to add "notes" (array) and "tags" (array) to this class. It is often that a security analyst would add notes or tag to it during investigation.

2023-08-02 00:03 UTC, maxhotta commented on dictionary.json
> +    "conclusion": {
conclusion is used as the type in the array definition

2023-08-02 00:15 UTC, maxhotta commented on dictionary.json
> +    "conclusion": {
didn't realize we don't need this if an object is defined - will remove it from the dictionary

2023-08-02 19:40 UTC, floydtree commented on events/findings/security_incident.json
> +    "cis_csc": {
can probably use the remediation object to bring in the context and keep the concept of remediation details in sync with other classes. If you need cis_csc, it can added to the remediation object. The goal being, to keep all the remediation details together

2023-09-22 03:22 UTC, maxhotta commented
Closing this original Draft PR per the new Findings / Finding Info implementation.
Submitted an updated PR accommodating these changes.

2023-09-22 03:22 UTC, closed without merging