adding disposition ids for WAF events
ocsf/ocsf-schema pull request #686
Opened 2023-07-12 01:07 UTC by adplotzk

#### Adding additional disposition ids to handle the application of the firewall profile to web logs

2023-07-12 12:57 UTC, floydtree requested changes

2023-07-12 12:57 UTC, floydtree commented on dictionary.json
> +          "caption": "Captcha"
Descriptions for both the new added options

2023-07-12 17:02 UTC, rroupski requested changes

2023-07-12 17:02 UTC, rroupski commented on dictionary.json
> +        "19": {
I am not sure about those 2 values. I don't see how they fit with the rest of the disposition ids? How the log looks like? Can you use disposition_id = 99  + disposition = "Captcha"?

2023-07-13 17:00 UTC, adplotzk commented on dictionary.json
> +        "19": {
The reasoning behind mapping the firewall class to eventclass to http activity was because the dispositions Ids would be able to handle the activity of the rule which would require the addition of captcha and challenge.

2023-08-18 17:58 UTC, rroupski commented
@adplotzk I'd like to propose some changes to the `disposition_id` values, and that will affect this PR.

Currently, the `disposition_id` enum values are defined in the dictionary, which more or less means that all classes will share the same values. This approach is not very practical, for example most of the current `disposition_id` values are not applicable to the alert and incidents.

If that proposal gets accepted, then you can define specific `disposition_id` values for the network events.

2023-08-22 19:05 UTC, closed without merging