Refinements to object descriptions (L:Z)
ocsf/ocsf-schema pull request #694
Opened 2023-07-14 18:44 UTC by floydtree

#### Related Issue: https://github.com/ocsf/ocsf-schema/issues/693

#### Description of changes:
1. Updating descriptions of objects (L-Z), non-breaking.

2023-07-14 20:36 UTC, rroupski submitted a review, later dismissed

2023-07-17 15:00 UTC, jasonbreimer submitted a review, later dismissed

2023-07-17 15:03 UTC, Aniak5 commented on objects/service.json
> +  "description": "Descrbies characteristics of a service, <code> e.g. AWS EC2. </code>",
Typo in Describes!

2023-07-17 15:04 UTC, Aniak5 commented on objects/tls_extension.json
> +  "description": "Descrbies additional attributes that extend the base Transport Layer Security (TLS) object.",
Typo in describes

2023-07-17 15:06 UTC, Aniak5 commented on objects/san.json
> +  "description": "Descrbies a Subject Alternative name (SAN) secured by a digital certificate",
Typo in describes

2023-07-17 15:07 UTC, floydtree commented on objects/service.json
> +  "description": "Descrbies characteristics of a service, <code> e.g. AWS EC2. </code>",
good catch!

2023-07-17 15:07 UTC, floydtree commented on objects/san.json
> +  "description": "Descrbies a Subject Alternative name (SAN) secured by a digital certificate",
lol, quite a pattern

2023-07-17 18:53 UTC, Aniak5 approved these changes
LGTM!

2023-07-18 14:40 UTC, rroupski approved these changes

2023-07-18 18:15 UTC, rroupski requested changes
We should keep the original wording, _The Foo object describes/contains/etc_ ... It was recommended/used by the Symantec tech writer, who wrote the original descriptions for ICD schema. 

BTW, all changes that I made in `_ to K` commit use that style, and the object name is always in Title Case. For example: _The Email object describes the email metadata such as sender, ..._

2023-07-18 18:38 UTC, floydtree commented
> We should keep the original wording, _The Foo object describes/contains/etc_ ... It was recommended/used by the Symantec tech writer, who wrote the original descriptions for ICD schema.
> 
> BTW, all changes that I made in `_ to K` commit use that style, and the object name is always in Title Case. For example: _The Email object describes the email metadata such as sender, ..._

 I think it's adds unnecessary redundancy to the descriptions, but considering yours are already merged I'll change.

2023-07-20 15:28 UTC, rroupski approved these changes

2023-07-20 16:11 UTC, jasonbreimer approved these changes

2023-07-20 17:05 UTC, Aniak5 approved these changes
LGTM

2023-07-20 17:05 UTC, merged