New attributes and object for patch metadata (kb_article)
ocsf/ocsf-schema pull request #702
Opened 2023-07-31 16:54 UTC by jasonbreimer

#### Related Issue: 
https://github.com/ocsf/ocsf-schema/discussions/684

#### Related PR:
https://github.com/ocsf/ocsf-schema/pull/698

#### Objective:
This includes attribute and object changes to allow optional enrichment of vulnerability class with patch/update meta data. The new object kb_article replaces an attribute kb_articles and contains additional details regarding the specific patch. This change will allow allow direct mapping of patch "findings" (forthcoming).

#### Change Details:
1. New attributes: bulletin, classification, cpe, superseded, related_cves
2. New Class: kb_article

#### Next Steps:
1. New PR for cpe attribute added to product object. 
2. New draft PR for new Class in Discover for Patch Findings.

2023-07-31 19:36 UTC, floydtree requested changes

2023-07-31 19:36 UTC, floydtree commented on dictionary.json
> +      "description": "The Common Platform Enumeration (CPE) name.",
Probably good to add reference to CPE's definition (https://nvd.nist.gov/products/cpe)

2023-07-31 19:36 UTC, floydtree commented on dictionary.json
> +      "type": "related_event"
error? should be `string_t`

2023-07-31 19:36 UTC, floydtree commented on dictionary.json
> +    "related_cves": {
In general, do you think we can re-use `related_vulnerabilities` in the `kb_articles` object? Reusability is the secondary aspect, primary being, what if the `kb_article` refers to a `cwe`? `related_vulnerabilities` is more general and serves the same purpose. Curious to hear your thoughts

2023-07-31 19:36 UTC, floydtree commented on objects/kb_article.json
> +  "description": "The kb article details for the patch or update.",
Nit - For consistency - Probably good to use the convention used to describe other objects in OCSF "The KB Article object describes/contains...."

2023-08-01 14:56 UTC, irakledibm commented on dictionary.json
> +    "related_cves": {
I would agree, KB articles should be associated with vulnerabilities in general, no restricted to CVEs

2023-08-01 16:13 UTC, jasonbreimer commented on dictionary.json
> +      "type": "related_event"
Can I use string_t for a list of cves?

2023-08-01 16:24 UTC, jasonbreimer commented on dictionary.json
> +      "description": "The Common Platform Enumeration (CPE) name.",
Done

2023-08-01 16:44 UTC, jasonbreimer commented on objects/kb_article.json
> +  "description": "The kb article details for the patch or update.",
done!

2023-08-01 16:44 UTC, jasonbreimer commented on dictionary.json
> +    "related_cves": {
Done!

2023-08-01 16:47 UTC, jasonbreimer commented on dictionary.json
> +      "type": "related_event"
N/A as this is removed.

2023-08-01 16:48 UTC, jasonbreimer commented
Yes, that was my thought for classification. I started with something like kb_classification in the dictionary but thought it might be better to create something generic so it could be re-used. 

I can go either way!

2023-08-01 17:10 UTC, irakledibm commented
I have no objections then

2023-08-01 17:10 UTC, irakledibm submitted a review, later dismissed

2023-08-01 17:32 UTC, floydtree approved these changes

2023-08-02 17:49 UTC, jasonbreimer commented
Rebuilding branch and PR because of merge conflicts.

2023-08-02 17:49 UTC, closed without merging