Add cpe attribute to product object
ocsf/ocsf-schema pull request #713
Opened 2023-08-03 18:28 UTC by jasonbreimer

#### Related Issue: 
https://github.com/ocsf/ocsf-schema/discussions/684

#### Related PR:
https://github.com/ocsf/ocsf-schema/pull/698

####Objective:
This includes addition of `cpe` attribute to the `product` object. This change will allow `vulnerability` object to include `cpe` from `product` object to better describe a software product.

####Change Details:
Edit the product object to include optional `cpe` attribute

2023-08-03 18:32 UTC, floydtree commented on objects/product.json
> +      "description": "The Common Platform Enumeration (CPE) name as described by (<a target='_blank' href='https://nvd.nist.gov/products/cpe'>NIST</a>).",
you wouldn't need to add a description at the object level for this field, especially considering it's the same as the one in dictionary. (Such description overrides can be used when we want to have an object/class specific description of the field)

2023-08-03 18:53 UTC, rroupski-splunk commented
Given this screenshot, what would the value of the `cpe` attribute? One of the CPE Names, the title, or something else?

<img width="1213" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/79468508/33b8fa70-b530-460e-95b2-dd967a2445cb">

2023-08-03 18:54 UTC, rroupski-splunk commented on objects/product.json
> +    "cpe": {
The value is not defined in the dictionary. What's the data type?

2023-08-03 19:52 UTC, floydtree commented on objects/product.json
> +    "cpe": {
It's defined in the dictionary [here](https://github.com/ocsf/ocsf-schema/blob/9dd59c4f83693c26a68f5ec17c7c890325d81419/dictionary.json#L942) as a string.

2023-08-03 19:53 UTC, floydtree approved these changes

2023-08-08 16:18 UTC, Aniak5 submitted a review, later dismissed
LGTM

2023-08-11 18:19 UTC, rroupski requested changes

2023-08-11 18:19 UTC, rroupski commented on objects/product.json
> +    "cpe": {
Using `cpe` as an attribute name is not a good choice. CPE stands for Common Platform Enumeration (CPE), which is a product dictionary (not a product attribute). A better name would be `cpe_name`.

The products defined in the CPE dictionary, look like the one below. Based on Slack messages, the `cpe` (or the `cpe_name`) value will be set to the `cpe-item` name, for example: `cpe:/a:apple:safari:16.2`, not the product `title`, which is `Apple Safari 16.2`. Right?

```xml
  <cpe-item name="cpe:/a:apple:safari:16.2">
    <title xml:lang="en-US">Apple Safari 16.2</title>
    <references>
      <reference href="https://support.apple.com/en-us/HT213537">Advisory</reference>
      <reference href="https://support.apple.com/en-us/HT201222">Advisory</reference>
    </references>
    <cpe-23:cpe23-item name="cpe:2.3:a:apple:safari:16.2:*:*:*:*:*:*:*"/>
  </cpe-item>
```

2023-08-11 18:26 UTC, rroupski commented on objects/product.json
> +      "description": "The Common Platform Enumeration (CPE) name as described by (<a target='_blank' href='https://nvd.nist.gov/products/cpe'>NIST</a>).",
An improve version of the description:

The Common Platform Enumeration (CPE) product name, aka `cpe-item name` as defined in [NIST](https://nvd.nist.gov/products/cpe) product  dictionary.

The Caption should be: _CPE Product Name_.

2023-08-17 18:14 UTC, jasonbreimer commented on objects/product.json
> +    "cpe": {
Sure I can change to cpe_name.

Yes the example would be from the "cpe-item" field like "cpe:/a:apple:safari:16.2".

I can add an example value as well to the dictionary attribute as well.

2023-08-18 16:12 UTC, jasonbreimer commented on objects/product.json
> +    "cpe": {
This is done! I've changed the name of the attribute in the dictionary, added an example to the attribute, and modified the product object to include the updated attribute name.

2023-08-18 16:17 UTC, rroupski requested changes

2023-08-18 16:17 UTC, rroupski commented on objects/product.json
> +      "description": "The Common Platform Enumeration (CPE) name as described by (<a target='_blank' href='https://nvd.nist.gov/products/cpe'>NIST</a>) For example: <code>cpe:/a:apple:safari:16.2</co
You don't have to repeat the description here, and you should remove it. It makes it easier to maintain consistently over a long time.

2023-08-18 16:28 UTC, jasonbreimer commented on objects/product.json
> +      "description": "The Common Platform Enumeration (CPE) name as described by (<a target='_blank' href='https://nvd.nist.gov/products/cpe'>NIST</a>) For example: <code>cpe:/a:apple:safari:16.2</co
I've simplified the description in the product object.

2023-08-18 17:03 UTC, rroupski approved these changes

2023-08-18 18:15 UTC, floydtree approved these changes

2023-08-18 18:27 UTC, irakledibm approved these changes

2023-08-18 18:36 UTC, merged