Updating API Activity to handle Container Activity Logs
ocsf/ocsf-schema pull request #721
Opened 2023-08-10 13:21 UTC by pladam

Updating API Activity to handle Container Activity Logs:

1. Adding NEW verbosity field to metadatajson object and dictionary.json 
2. Adding adding data fields to request.json and response.json objects to handle the kubernetes response and request objects
3. Adding namespace field to resource_details.json object to handle api namespaces
4. Adding group object to api.json object to handle api groups

2023-08-10 15:38 UTC, rroupski requested changes

2023-08-15 15:12 UTC, pladam commented on dictionary.json
> +    "verbosity": {
This has been updated.

2023-08-17 16:48 UTC, rroupski requested changes

2023-08-17 16:48 UTC, rroupski commented on dictionary.json
> +    "containers": {
There are too many places where the containers attribute is used. The API Activity class has 4 of them. See the arrows on the picture below pointing to the Container object. We should simplify it.

<img width="1376" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/2128145/77e3e1f4-2a58-41a1-9359-72956ff88bda">

2023-08-17 16:48 UTC, rroupski commented on profiles/container.json
> +    "containers": {
Missing group properties, such as primary, context, etc.

2023-08-17 16:48 UTC, rroupski commented on profiles/container.json
>      "namespace_pid": {
Missing group properties, such as primary, context, etc.

2023-08-17 16:48 UTC, rroupski commented on profiles/container.json
> +    "containers": {
Remaining the `container` as `containers` is not a good idea. It breaks the existing definitions. For example, now the `process` object has a `containers` attribute, which is wrong.

 Also, this change is not a backward compatible, and we should bot make any breaking changes in the v1.1.

2023-08-17 16:53 UTC, pladam commented on profiles/container.json
> +    "containers": {
how can we account for events which have multiple containers then?

2023-08-17 16:54 UTC, pladam commented on dictionary.json
> +    "containers": {
for the sake of the log im attempting to model in particular, there are an array of containers in both the request and response of the api. any suggestions here to simplify?

2023-08-18 16:31 UTC, rroupski commented on dictionary.json
> +    "containers": {
Sure, can you send me some sample data?

2023-08-22 19:05 UTC, closed without merging