[Draft] Additional Discovery events
ocsf/ocsf-schema pull request #723
Opened 2023-08-14 20:53 UTC by maxhotta

Adding events to model various discoverable entities on Windows/Linux/MacOS:
Windows/Mac specific items were added as extensions for the OS.

Windows specific entities:
- Registry Value
- Registry Key
- Prefetch

MacOS specific entities:
- Startup Application

OS agnostic entities:
- File
- Folder
- Admin Group
- Job
- Module
- Network Connection
- Networks
- Peripheral Device
- Process
- Service
- User Session
- User Info

Other:
- Unsuccessful Discovery : result document (event) that captures when a discovery attempt failed

2023-08-22 16:19 UTC, jasonbreimer commented
This is neat! Are there any data samples we could use? Some of these I wonder how to separate from System Activity. For example registry is mentioned as possible new discovery event, what would that look like and how would it be different than a System Activity with Windows profile? Maybe this would for example capture the existence of a particular key/value that is NOT tied to an activity that wrote the value? IE.... I went and found this registry key/value state/existence. But its not  tied to an event that created the key/value.

2023-08-23 03:14 UTC, maxhotta commented
@jasonbreimer thanks for the comments, and you are correct, that the difference between the discovery version of these events is that they are not activity as logged on the device, but rather a result of a proactive search.  In our product, we expose the capability to run these "Evidence of Compromise" searches which can target all the entities defined in the PR.  If they are found, the results are returned and captured as events.  The second part of this PR will be a set of Remediation event classes where administrators can then send a command/request to remediate the found entities.

2023-08-23 22:28 UTC, rroupski requested changes

2023-08-23 22:28 UTC, rroupski commented on events/discovery/discovery_no_result.json
> +        "3": {
What's the reason to start the enum values from 3? Perhaps make them sequential: 1, 2, 3?

2023-08-23 22:28 UTC, rroupski commented on events/discovery/discovery_no_result.json
> +  "extends": "discovery",
Where is the `discovery` base class defined?

2023-08-23 22:28 UTC, rroupski commented on events/discovery/discovery_no_result.json
> +  "uid": 0,
Use `uid = 4`, which is the next available class UID in the Discovery category.

2023-08-23 22:28 UTC, rroupski commented on events/discovery/discovery_result.json
> +  "extends": "discovery",
Where is the discovery base class defined?

2023-08-23 22:28 UTC, rroupski commented on events/discovery/discovery_result.json
> +  "caption": "Discovery Result Events",
Drop Events from the caption.

2023-08-23 22:28 UTC, rroupski commented on dictionary.json
> +    "module_type": {
The Module object already has a `type` attribute. Is the `module_type` different than the `module.type`?

2023-08-23 22:28 UTC, rroupski commented on events/discovery/session_info.json
> +    "is_remote": {
The `is_remote` attribute is defined in the session object. This one seems as a redundant attribute?

2023-08-23 22:28 UTC, rroupski commented on objects/peripheral_device.json
> +  "extends": "object",
Should extend the `_entity` object, which adds `name` and `uid` attributes. Note, that it is OK to overwrite the default descriptions.

2023-08-23 22:28 UTC, rroupski commented on extensions/macos/extension.json
> +  "description": "The macOS extension defines macOS specific attributes.",
The macOS extension defines macOS specific attributes, objects, and classes.

2023-08-29 18:39 UTC, jasonbreimer commented
Hey Max, what about adding the host profile to the new classes so that a device object hostname attribute can associated with the finding/query? IE I found this registry value on this device hostname.

2023-08-31 22:59 UTC, maxhotta commented on events/discovery/discovery_no_result.json
> +        "3": {
@rroupski thanks for the feedback - will address these

2023-08-31 23:09 UTC, maxhotta commented
@jasonbreimer thanks, will take a look at the host profile.

2023-09-01 22:43 UTC, pagbabian-splunk commented on events/discovery/discovery_no_result.json
> +  "extends": "discovery",
`ocsf-schema/events/discovery/discovery.json`

2023-09-01 22:59 UTC, pagbabian-splunk commented on events/discovery/discovery_result.json
> +  "extends": "discovery",
What exists, or what is partial?  I assume each subclass defines an entity that is being queried for.  I see many small classes that seem like they are derived from `discovery_result` but none from `discovery_no_result`.  If there is no result, how do I know what was being looked for?  Why not have an `activity_id` "3" for "Not Found" or something like that?

2023-09-19 00:17 UTC, maxhotta commented on events/discovery/discovery_result.json
> +  "extends": "discovery",
Took another look here and what was previously defined as eoc_request captured the original request.  This is now called, request_obj, which is how users can view what was being searched for.  Regarding the reason for not adding a new activity id for 'not found' in each of the event classes (which I'm not sure exactly why the original schema was implemented this way) a potential con is that the full event payload may be repetitive/large to include as opposed to a relatively small 'not found' event.

2023-09-28 00:41 UTC, maxhotta commented on dictionary.json
> +    "module_type": {
Removed this in another branch.  Will submit an updated pr.

2023-11-02 18:25 UTC, merged