Updating disposition_ids to match firewall profile
ocsf/ocsf-schema pull request #734
Opened 2023-08-22 19:15 UTC by adplotzk

Updating disposition_ids to match firewall profile.

This is in response to the PR https://github.com/ocsf/ocsf-schema/pull/732.

2023-08-22 19:23 UTC, floydtree approved these changes

2023-08-22 19:47 UTC, mr-splunk reviewed
Something I noticed with Palo Alto logs - along with `blocked` there is also a `dropped`. I recall that there is an important distinction between the two. Should `dropped` be worth considering as a disposition?

2023-08-22 20:16 UTC, adplotzk commented
> Something I noticed with Palo Alto logs - along with `blocked` there is also a `dropped`. I recall that there is an important distinction between the two. Should `dropped` be worth considering as a disposition?
> 
> <img alt="image" width="96" src="https://user-images.githubusercontent.com/91983279/262468713-c03ec982-fb97-4cd5-8b90-b77706d9acc8.png">

I can add this.

2023-08-22 20:23 UTC, adplotzk commented
> Something I noticed with Palo Alto logs - along with `blocked` there is also a `dropped`. I recall that there is an important distinction between the two. Should `dropped` be worth considering as a disposition?
> 
> <img alt="image" width="96" src="https://user-images.githubusercontent.com/91983279/262468713-c03ec982-fb97-4cd5-8b90-b77706d9acc8.png">

I've added some additional Palo actions to the disp_ids. can you please review again.

2023-08-22 20:40 UTC, rroupski requested changes

2023-08-22 20:40 UTC, rroupski commented on profiles/firewall.json
> +        "3": {
I see duplicate enum value id's. Can you fix them?

2023-08-23 20:41 UTC, rroupski approved these changes

2023-08-23 21:04 UTC, floydtree approved these changes

2023-08-23 21:07 UTC, Aniak5 approved these changes
LGTM!

2023-08-23 21:07 UTC, merged