Adding containers array to request and response object, to handle container activity logs
ocsf/ocsf-schema pull request #738
Opened 2023-08-23 21:15 UTC by pladam

Adding containers array to request and response object, to handle container activity logs

This change adds `containers[]` to api.request
This change adds `data' to api.request

This change adds `containers[]` to api.response
This change adds `data' to api.response

This change adds `log_level` to dictionary.json
This change adds `log_level` to metadata object

2023-08-23 22:03 UTC, rroupski requested changes

2023-08-23 22:03 UTC, rroupski commented on objects/response.json
> +    "containers": {
The default description of the `containers` attribute is too generic, perhaps add a specific one to explain what is the rule/usage of the `containers` in the response object.

2023-08-23 22:03 UTC, rroupski commented on objects/request.json
> +    "containers": {
The default description of the `containers` attribute is too generic, perhaps add a specific one to explain what is the rule/usage of the `containers` in the request object.

2023-08-25 12:54 UTC, pladam commented on objects/response.json
> +      "profile": "container"
updated.

2023-08-25 17:32 UTC, rroupski approved these changes

2023-08-28 16:42 UTC, Aniak5 commented on objects/resource_details.json
> +      "description": "The namespace is useful when similar entities exists that you need to keep separate.",
I think that "exists" should be "exist".

2023-08-28 16:51 UTC, mr-splunk submitted a review, later dismissed

2023-08-28 17:08 UTC, Aniak5 approved these changes
LGTM

2023-08-28 17:22 UTC, mr-splunk approved these changes

2023-08-28 17:36 UTC, irakledibm approved these changes

2023-08-28 17:37 UTC, rroupski approved these changes

2023-08-28 17:37 UTC, merged