Cleanup ip_t and subnet_t types
ocsf/ocsf-schema pull request #745
Opened 2023-08-25 18:34 UTC by rroupski

Fix #683 Define regexp flavor issue
Fix #744 Need a new/better description for subnet_t type

2023-08-25 20:23 UTC, jp-harvey commented on dictionary.json
> +      "description": "The subnet mask represented in CIDR notation, using the format IP_address/prefix_length. The IP_address can be in either IPv4 or IPv6 format. The prefix length indicates the num
References to "The subnet mask" should just be "The subnet". The subnet mask is specifically the mask bits only, ie `/24` or `255.255.255.0`. The subnet / network / IP block in CIDR notation is what we're representing here, which includes both the network address of the subnet and the subnet mask together. 

TL;DR iIt's confusing to reference the subnet mask as the whole subnet (network+mask) in CIDR notation.

We're also not representing an IP address here we're representing a network, so references to `IP_address` are not accurately describing the field.

So the updated new description would be:
```
The subnet represented in CIDR notation, using the format network_address/prefix_length. The network_address can be in either IPv4 or IPv6 format. The prefix length indicates the number of bits used for the network portion, and the remaining bits are available for host addresses within that subnet.<div>For example, using the IPv4 CIDR subnet <code>192.168.200.0/24</code>, the <code>/24</code> indicates that the first 24 bits are the network address, and the remaining 8 bits are used for host addresses within that subnet. Another example, if you have an IPv6 CIDR subnet <code>2001:0db8:85a3:0000::/64</code>, then the <code>/64</code> indicates that the first 64 bits are the network portion, and the remaining 64 bits are available for host addresses within that subnet.</div>
```
That said, if we're precise enough in the description with examples we don't need all the explanation of what CIDR is and how it works. CIDR notation is well known and well documented elsewhere. I'd suggest simplifying to be very similar to what we had originally, but with more precise terms to remove ambiguity and an IPv6 example as well:
```
A network address and subnet mask expressed in CIDR notation, eg:
<code>192.168.1.0/24</code>
<code>2001:0db8:85a3:0000::/64</code>
```

2023-08-29 17:57 UTC, jp-harvey commented on dictionary.json
> +      "description": "The subnet mask represented in CIDR notation, using the format IP_address/prefix_length. The IP_address can be in either IPv4 or IPv6 format. The prefix length indicates the num
@JasonKeirstead yes by requiring CIDR notation we're requiring a that the 1s to the left are contiguous, even though a mask can be any combination of bits - definitely not as common as a CIDR implementation.

If we need to represent the atypical mask cases in OCSF then we need to determine how we do that. I'd suggest that's out of scope of this PR though, as it will either be a breaking change or adding other attributes, and this is just a description update.

2023-08-29 17:59 UTC, jp-harvey reviewed
This change looks good, I prefer this more concise description though, interested in feedback from others:

> A network address and mask expressed in CIDR notation, eg:
<code>192.168.1.0/24</code>
<code>2001:0db8:85a3:0000::/64</code>

2023-08-30 21:25 UTC, rroupski commented
> This change looks good, I prefer this more concise description though, interested in feedback from others:
> 
> > A network address and mask expressed in CIDR notation, eg:
> > `192.168.1.0/24`
> > `2001:0db8:85a3:0000::/64`

The new, shorter, description looks like this:

<img width="647" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/2128145/0ceaafca-f5ba-45e2-a726-acfe0a664f75">

2023-08-31 00:11 UTC, jp-harvey commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
@rroupski sorry I missed this before, just curious here about the regex permitting leading and trailing whitespace. I don't think we should consider that a valid format if it has whitespace?

2023-08-31 16:27 UTC, rroupski commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
I found it on the internet as a recommended regex for validating IP addresses. It has validation tests and it works well.

2023-08-31 17:07 UTC, irakledibm approved these changes
makes sense

2023-09-01 21:48 UTC, pagbabian-splunk approved these changes

2023-09-06 16:03 UTC, Aniak5 approved these changes

2023-09-06 16:49 UTC, mr-splunk commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
I am in a similar camp here, I have some doubts about permitting leading and trailing whitespace. I played around in a regex tester, and something like this would pass as an IP:

<img width="287" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/76fbff4d-6a3e-4c92-be9d-6b86c1ae0459">

Couldn't that present problems and stray from standardization?

2023-09-06 17:39 UTC, zschmerber requested changes
https://ihateregex.io/expr/ip/
This link has s good regex for both ipv6 and ipv4 
the domain also makes me happy..

2023-09-06 17:39 UTC, zschmerber commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
"description" looks better now. I think we should not allowing leading and trailing whitespace.

2023-09-06 19:34 UTC, rroupski commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
So, you are saying is that `"1.2.3.4 "` is an invalid IP address? It seems too  restrictive.

2023-09-06 20:06 UTC, floydtree commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
tbh, I think that's a fair restriction.

2023-09-06 21:30 UTC, zschmerber approved these changes

2023-09-06 21:30 UTC, zschmerber commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
Well, I did some more research and I changed my mind. We want to know if someone it injecting whitespace into an address 
https://www.mozilla.org/en-US/security/advisories/mfsa2015-122/

2023-09-06 21:56 UTC, mr-splunk commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
@zschmerber brings up a valid use case. Retaining the whitespace in a value will be useful within the context of security logging & monitoring. In this case, looks good to me 👍

2023-09-06 21:56 UTC, mr-splunk approved these changes

2023-09-07 17:49 UTC, merged

2023-09-07 21:13 UTC, jp-harvey commented on dictionary.json
> +        "regex": "((^\\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]).){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\\s*$)|(^\\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-
I think the reasoning for allowing whitespace in the regex by @zschmerber logical.

Extrapolating based on that reasoning, that certain invalid formats will surface bugs in certain systems and so downstream systems should be able to detect those invalid formats, it's feasible that other systems will have bugs if an invalid IP string is sent that is not related to whitespace - eg. unicode chars, letters, null etc. Here are two from 30s of Googling:

https://access.redhat.com/security/cve/cve-2022-43548
https://nvd.nist.gov/vuln/detail/CVE-2005-0581

If we're allowing whitespace on the basis of it surfacing a bug in a browser, we should allow those invalid formats as well, and _any_ character that knowingly causes a bug in a system. We will have a hard time finding all of those known bugs, and practically speaking will never know them all, so the most logical conclusion is to just allow all strings and let downstream systems do the validation instead. 

I vote for the opposite - valid format according to RFCs or relevant authoritative bodies, and producers / consumers choose how to handle an invalid format based on the OCSF validation - that's what the validation is there for. Otherwise let's just remove validation from OCSF completely. (note that the original string will still be in `raw_data` if needed)

Whatever the approach decided upon should be adopted across OCSF too, not just for IP addresses.