The new finding_info object
ocsf/ocsf-schema pull request #763
Opened 2023-09-05 14:54 UTC by floydtree

#### Related Issue: https://github.com/ocsf/ocsf-schema/issues/762

#### Description of changes:

1. Adding a new attribute of the finding object in the dict - finding_info
2. Adding new attributes in the finding object
3. Adding deprecation tags as applicable
4. Removing analytics from the new vuln class, as it is being replaced by the attributes present in finding_info.
5. Adding finding_info to the base finding class.
6. Aligning analytic desc in dictionary with the the one in the object.

2023-09-05 15:33 UTC, irakledibm reviewed
Probably it is not necessary to have in a finding.json and analytic attribute and related_analytics array. We could have just an analytics array instead.

2023-09-05 16:56 UTC, irakledibm submitted a review, later dismissed
After discussing related_analytics in a meeting, I have no more questions.

2023-09-05 20:52 UTC, rroupski requested changes

2023-09-05 20:52 UTC, rroupski commented on objects/finding.json
>    "attributes": {
Compare to v1.0.0, the `supporting_data` attribute is missing, thus this is a braking change. I'd recommend keeping the existing `finding` object and create a new `finding_info` object.

2023-09-05 20:52 UTC, rroupski commented on objects/analytic.json
> +        "message": "Related Analytics has been decoupled from this object, can now be used independently.",
Rewrite it to recommend the new attribute, for example:
Related Analytics has been decoupled from this object, instead of use <code>finding.related_analytics</code>.

2023-09-05 20:52 UTC, rroupski commented on events/findings/finding.json
> +  "constraints": {
Having 2 `finding` objects is confusing. Given that `security_finding` class will be deprecated and the `vulnerability_finding` is a new class in v1.1.0, consider using only the new `finding_info` attribute.

2023-09-05 20:52 UTC, rroupski commented on dictionary.json
> +        "message": "Refer to the new Finding Information object.",
Rewrite the description to recommend the new attribute, for example:
Use the new `finding_info` attribute, which is defined as Finding Information object.

2023-09-06 14:06 UTC, floydtree commented on objects/finding.json
>    "attributes": {
This is a part of https://github.com/ocsf/ocsf-schema/issues/759, and will follow in a separate PR.

2023-09-06 17:20 UTC, rroupski requested changes

2023-09-06 17:20 UTC, rroupski commented on events/findings/finding.json
> +  "constraints": {
It is still confusing to have 2 findings attributes, so let's have a discussion to find a clean solution.

2023-09-08 13:37 UTC, floydtree commented
Closing in favor of https://github.com/ocsf/ocsf-schema/pull/769

2023-09-08 13:37 UTC, closed without merging