Refactor the finding object and base class
ocsf/ocsf-schema pull request #769
Opened 2023-09-07 21:27 UTC by rroupski

This PR is based on 09/07/2023 meeting discussions

Roughly based on PR #763 **The new `finding_info` object**, and it is meant to replace the PR #763.
Related issue: #762 **New `finding_info` attribute as a successor to the current finding attribute.**

The original `security_finding` class has been restored (to keep backwards compatibility).
The existing `finding` object has been deprecated.
New `finding_info` object to replace the deprecated finding object.
Rename the kill chain object.

2023-09-07 22:04 UTC, pagbabian-splunk commented
Aside from my two comments, it looks good to me.

2023-09-07 22:12 UTC, irakledibm approved these changes
Based on our group discussion, LGTM

2023-09-07 23:57 UTC, maxhotta approved these changes

2023-09-08 13:36 UTC, floydtree requested changes

2023-09-08 13:36 UTC, floydtree commented on events/findings/finding.json
> +  "description": "The Finding event is a generic event that defines a set of attributes available in the Findings category.",
We should add this line in the description - "These attributes will be inherited by all the classes defined in the Findings category." 
Many have asked what's the use-case of this "hidden" class and having a self-evident description helps alleviate those questions.

2023-09-08 13:36 UTC, floydtree commented on events/findings/vulnerability_finding.json
> -    "analytic": {
Why remove analytics from this object? Let's not make arbitrary changes please!

Considering each vulnerability findings class, has an array of vulnerabilities, each vulnerability can have a distinct analytic method used to assess the vulnerability in question. That's why we have it here.

2023-09-12 14:01 UTC, merged