Issue 750: Add `device` and `log_device` to metadata
ocsf/ocsf-schema pull request #770
Opened 2023-09-07 22:26 UTC by Aniak5

#### Related Issue: #750 

#### Description of changes:

- Add `log_device` attribute to dictionary
- Add `device` and `log_device` to metadata

<img width="1377" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/6465263/92e7ffa9-fce5-4f4f-a1c6-23a6c6e18c5c">

2023-09-07 23:46 UTC, rroupski requested changes

2023-09-07 23:46 UTC, rroupski commented on dictionary.json
> +      "description": "The device that sent the log.",
Consider this description:
The logging device responsible for recording the event or the device from which the event was initially retrieved. Note that in some instances, this might be the same as the device where the event was generated.

2023-09-07 23:46 UTC, rroupski commented on objects/metadata.json
> +    "device": {
Consider this description:
The device where the event was generated.

2023-09-07 23:46 UTC, rroupski commented on objects/metadata.json
> +      "description": "The device that transmitted the log. Note that in some instances, this might be the same as the device that logged the event.",
We should use the description from the dictionary.

2023-09-08 12:37 UTC, Aniak5 commented on dictionary.json
> +      "description": "The device that sent the log.",
Thanks, that sounds much nicer!

2023-09-08 16:32 UTC, rroupski approved these changes

2023-09-08 16:43 UTC, jp-harvey reviewed
We've been handling this by using the `host` profile so far, treating that as `the device where the event was generated`, but this is a much better solution.

Do we also need to review the `device` description as well to distinguish it? At the moment it's very generic:

> An addressable device, computer system or host.

What about:

> An addressable device, computer system or host that is the subject of the event.

2023-09-08 22:54 UTC, pagbabian-splunk requested changes
For `device` we should say 'where the event occurred' rather than where it was generated.

2023-09-08 22:54 UTC, pagbabian-splunk commented on objects/metadata.json
>        "requirement": "recommended"
I think we really mean the device where the event occurred, rather than where it was generated.  E.g. a scanner will record the target device but it generates the event on the scanner device, not the target device.

2023-09-11 16:50 UTC, mr-splunk commented
> We've been handling this by using the `host` profile so far, treating that as `the device where the event was generated`, but this is a much better solution.
> 
> Do we also need to review the `device` description as well to distinguish it? At the moment it's very generic:
> 
> > An addressable device, computer system or host.
> 
> What about:
> 
> > An addressable device, computer system or host that is the subject of the event.

We've been doing the same, since our translations are still using rc2.

2023-09-11 17:29 UTC, rroupski commented on objects/metadata.json
>        "requirement": "recommended"
@jp-harvey, a very good catch! I think we should rethink this PR. It seems there is some overlap between `host/device` and the `metadata.device`.

2023-09-11 17:38 UTC, rroupski commented
The main issue with the host/device is that the host profile is not used in all events. Also, if the host profile is used, then often the host/device means the device where the event occurred -- for example, the windows events that we have translated.

Perhaps, we can add the `device` attribute to the event itself (not in the metadata), so that we have backward compatibility with the current host/device usage?

2023-09-11 18:07 UTC, pagbabian-splunk commented
Please see my comments.  `device` should not be described as the logging device.  It should be where the event occurred.

2023-09-11 19:18 UTC, Aniak5 commented on dictionary.json
> +      "description": "The device that sent the log.",
That sounds better, thanks!

2023-09-13 19:59 UTC, mr-splunk commented
**Summary from Tuesday's (09/13/2023) call:**

- In the dictionary, `device` is generic (just an object)
- In the context of the `Host` profile, `device` represents the host where the event occurred.
- In the context of `metadata`, `device` corresponds to the `Product`.
- Sometimes, `metadata.device` and `Host` `device` are of the same value, since the `Product` resides at the `Host`. In other cases, they can be different.

**Takeaway:** this PR can be closed out and we can address **Issue #750** in a new PR with an illustrated diagram.

2023-09-13 19:59 UTC, closed without merging