Adding Exploit Availability field to the vulnerability object
ocsf/ocsf-schema pull request #777
Opened 2023-09-13 17:20 UTC by floydtree

#### Description of changes:

Adding a new field to indicate availability of an exploit for a given vulnerability finding.  
Reference for a source that provides this info - [AWS Inspector](https://docs.aws.amazon.com/inspector/latest/user/eventbridge-integration.html#event-finding)

![Screenshot 2023-09-13 at 1 17 58 PM](https://github.com/ocsf/ocsf-schema/assets/89877409/c14b38e7-b110-47e3-9ba6-52df5d7e0a03)

2023-09-13 17:49 UTC, rroupski requested changes

2023-09-13 17:49 UTC, rroupski commented on dictionary.json
> +    "exploit_available":{
Most of the boolean attributes are is_xyz, so for consistency’s sake, I'd recommend to use `is_exploitable`.

The description should be updated too:
`An exploitable vulnerability is a vulnerability with at least one known, working attack vector.`

2023-09-13 17:49 UTC, rroupski commented on dictionary.json
> +      "caption": "Exploit Availability",
Exploitable

2023-09-13 18:01 UTC, floydtree commented on dictionary.json
> +    "exploit_available":{
About name - It is named as such to be consistent with the fix_available field that we already have in vuln.

About description - I think there's a difference of perspective in both the approaches. I am not trying to define what an exploitable vulnerability is, I am trying to describe what exploit_available field means in the context of its usage.

2023-09-13 19:06 UTC, awhite456 submitted a review, later dismissed

2023-09-13 19:06 UTC, awhite456 commented on dictionary.json
> +    "exploit_available":{
If the naming convention is to keep consistency with the existing object fields, then I think this works ok.

2023-09-13 21:18 UTC, rroupski commented on dictionary.json
> +    "exploit_available":{
Currently, the v1 has only 3 exceptions, so rather than continuing the path adding more inconsistency, at least we should try to use more consistent naming.

<img width="1022" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/2128145/dcbe6d78-c315-4839-b454-34676ef5f310">

2023-09-14 12:58 UTC, floydtree commented on dictionary.json
> +    "exploit_available":{
I disagree, I wouldn't want to name field something only to ensure consistency, the meaning of is_exploitable is different from exploit_available. Having said that, I would be okay with is_exploit_available. Pushing a commit to update the name.

2023-09-14 14:34 UTC, jasonbreimer approved these changes

2023-09-14 14:40 UTC, awhite456 approved these changes

2023-09-14 18:52 UTC, merged