Additions to the Session object, minor requirement adjustment to the user object
ocsf/ocsf-schema pull request #796
Opened 2023-09-27 17:17 UTC by floydtree

#### Related Issue: https://github.com/ocsf/ocsf-schema/issues/795

#### Description of changes: (non-breaking)
1. Adding uid_alt, is_mfa to the session object
2. Expanding constraints for the user object -> {account, name, uid)
3. Reducing requirement of user.type_id to recommended from required.

2023-09-27 17:48 UTC, dkolbly submitted a review, later dismissed
Looks good to me.

Does **uid_alt** have a well-understood meaning, or would some additional description be helpful?

2023-09-27 20:10 UTC, mr-splunk commented
Looks like we're on the same page with some things here, Rajas. FYSA - I am planning a PR to add an optional `terminal` attribute to the session object based on takeaways from our System and Network Activity syncs. For now i'll keep it a separate PR since this PR is addressing other finds.

2023-09-27 20:13 UTC, mr-splunk requested changes

2023-09-27 20:13 UTC, mr-splunk commented on objects/session.json
> +    "uid_alt": {
I might have missed the whole use case for this one? What is a strong example of a `uid_alt` in practice. And could an example be added to the description?

2023-09-27 20:25 UTC, mr-splunk commented
> Should it be called session_id or session_token? I may not be familiar with it, but what uid_alt would be representing?

Good question Irakle. I was wondering the same. I am interested to see the use case/application of `uid_alt`.

2023-09-27 21:03 UTC, floydtree commented on objects/session.json
> +    "uid_alt": {
Yes, I'll update the description with an example.
But, here's the usecase of uid_alt in brief @irakledibm @dkolbly @mr-splunk 

 In aws eks audit logs, the underlying IAM user's session information is provided as follows - 

```
"extra":
        {
            "accessKeyId":
            [
                "EXAMPLE"
            ],
            "arn":
            [
                "arn:aws:sts::123344444444:assumed-role/Admin/EXAMPLE"
            ],
            "canonicalArn":
            [
                "arn:aws:iam::123344444444:role/Admin"
            ],
            "sessionName":
            [
                "EXAMPLE"
            ]
        }
```

In here there are 2 key identifiers of the session, sessionName and arn. arn value is the one that will utilize the `uid_alt` field in the session object. A general note, aws arn is semantically a universally unique identifier of the entity, but not in the rfc defined uuid format and therefore not of type uuid_t in OCSF. To address this, `uid_alt` was added to OCSF. This was already added in the `user` object, but we missed to add it in the `session` object. Here's how it will be mapped - 

`sessionName` -> `uid` (not sure if `name` will be generally useful in the session object for other use-cases hence we chose to use uid as it is indeed a unique identifier for a particular IAM entity's session. However, if `name` is generally useful, we can add `name` to the object and not add `uid_alt`)
`arn`-> `uid_alt`

2023-09-28 20:16 UTC, Aniak5 submitted a review, later dismissed
LGTM

2023-09-28 20:47 UTC, dkolbly commented on objects/session.json
> +      "description": "The alternate unique identifier of the session. e.g. AWS ARN. <code> arn:aws:sts::123344444444:assumed-role/Admin/example-session. </code> ",
The `<code>...</code>` tag should probably enclose just the thing.  As written contains both a space and a trailing period and space.

2023-09-28 20:54 UTC, irakledibm submitted a review, later dismissed

2023-09-28 21:46 UTC, Aniak5 approved these changes

2023-09-28 22:17 UTC, dkolbly approved these changes
Looks good!

2023-09-29 16:15 UTC, mikeradka approved these changes
LGTM

2023-09-29 16:17 UTC, merged

2023-10-03 11:23 UTC, irakledibm reviewed
lgfm