Issue #799 add a terminal object for tty/pts and other pseudo terminals
ocsf/ocsf-schema pull request #802
Opened 2023-09-29 16:24 UTC by mikeradka

#### Related Issue: #799 

#### Description of changes:
- This PR adds an attribute to the `session` object for logging the pseudo-terminal, a valuable piece of information for detection engineering. For more info see Issue #799.

<img width="1166" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/694ebea5-67f3-4cee-afb5-e06d02e1eb57">

2023-09-29 16:56 UTC, floydtree requested changes

2023-09-29 16:56 UTC, floydtree commented on objects/session.json
> +      "description": "The Pseudo Terminal assicoated with the session. Ex: the tty or pts value.",
nit - spelling error in associated

2023-09-29 16:58 UTC, mikeradka commented on objects/session.json
> +      "description": "The Pseudo Terminal assicoated with the session. Ex: the tty or pts value.",
Nice catch, thanks Rajas.

2023-09-29 17:28 UTC, floydtree approved these changes

2023-10-02 14:17 UTC, Aniak5 approved these changes
LGTM!

2023-10-02 14:48 UTC, zschmerber approved these changes
Looks good to me.

2023-10-02 14:49 UTC, merged