Updating containers object
ocsf/ocsf-schema pull request #803
Opened 2023-09-29 18:16 UTC by adplotzk

Updating containers object so that UID is not a required attribute to account to for additional use cases, and is moved to an atleast 1 of clause with name.

2023-09-29 21:02 UTC, mikeradka requested changes

2023-09-29 21:02 UTC, mikeradka commented on objects/container.json
> +	"caption": "Container",
It looks like the indenting changed. Could this be changed back so it is uniform with the standard indenting we have across our json files?

2023-10-02 16:07 UTC, floydtree requested changes
This will not solve the problem you are looking to address, because uid is still a required attribute in the containers object. To make the constraints useful, you would need to change the requirement of `uid` to recommended or optional.

2023-10-03 16:52 UTC, Aniak5 approved these changes
LGTM!

2023-10-03 17:25 UTC, merged