Issue 794: Add authentication type to the ssh event class
ocsf/ocsf-schema pull request #806
Opened 2023-10-02 15:33 UTC by Aniak5

#### Related Issue: #794 

#### Description of changes:

- Add `auth_type_id` and `auth_type` to ssh event class to provide context about the authentication method.

<img width="1377" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/6465263/8a5c53cb-fd6c-4d24-a6f1-23c72b1dbfba">

2023-10-02 15:36 UTC, mikeradka approved these changes
Looks good

2023-10-02 15:37 UTC, mikeradka requested changes

2023-10-02 16:00 UTC, mikeradka approved these changes

2023-10-02 16:15 UTC, floydtree approved these changes

2023-10-09 22:44 UTC, pagbabian-splunk approved these changes

2023-10-09 22:44 UTC, merged