Adding percentile attribute to the EPSS object
ocsf/ocsf-schema pull request #831
Opened 2023-10-24 17:48 UTC by floydtree

#### Related PR: https://github.com/ocsf/ocsf-schema/pull/805

#### Description of changes:
1. Refactoring https://github.com/ocsf/ocsf-schema/pull/805
2. Adding EPSS percentile attribute to dictionary and the epss object
https://www.first.org/epss/articles/prob_percentile_bins
3. Sorting attributes in the epss object.
![Screenshot 2023-10-24 at 1 48 04 PM](https://github.com/ocsf/ocsf-schema/assets/89877409/3d3b6f0d-0468-48de-8418-b4b54395a892)

2023-10-26 02:17 UTC, dkolbly requested changes
Consider using a more constrained type if possible.

2023-10-26 02:17 UTC, dkolbly commented on dictionary.json
> +      "type": "string_t"
Is there a better type constraint we can use besides `string_t`?  I assume a `float_t` would be more appropriate, since this represents a numeric quantity...

2023-10-26 14:15 UTC, jcburgo commented on dictionary.json
> +      "type": "string_t"
+1

2023-10-26 15:49 UTC, floydtree commented on dictionary.json
> +      "type": "string_t"
Agreed

2023-10-26 22:37 UTC, jcburgo approved these changes

2023-10-27 20:36 UTC, irakledibm approved these changes

2023-10-30 17:19 UTC, mikeradka approved these changes

2023-10-31 15:21 UTC, merged