#816 Boolean-Type Consistency
ocsf/ocsf-schema pull request #841
Opened 2023-11-02 22:07 UTC by mikeradka

#### Related Issue: #816 

#### Description of changes:

This PR establishes a consistent convention of prepending `is_` to our naming of boolean-type fields. 

To ensure this is non-breaking, the following `v1.0.0` fields were deprecated:

- `http_only` - now use `is_http_only`
-  `secure` - now use `is_secure`

In addition, the `1.1.0-dev` field `superseded` has become `is_superseded`.

All field references were updated to reflect the change:

<img width="782" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/ab3bdfb6-e1df-45a4-8f63-3d347f7170c8">

<img width="751" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/0b9e178f-4a99-4a90-9140-be14cce49b20">

<img width="801" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/806c26ac-8aed-45f0-beb2-aaf284b9dc54">

2023-11-03 13:52 UTC, floydtree approved these changes
Looks good. Thanks for getting this out!

2023-11-06 15:03 UTC, mikeradka commented on dictionary.json
> +      "description": "The cookie attribute to only send cookies to the server with an encrypted request over the HTTPS protocol.",
Sure, done.

2023-11-06 15:03 UTC, mikeradka commented on dictionary.json
> +      "description": "A cookie attribute to make it inaccessible via JavaScript",
Sure. This is in. If you and @floydtree could please re-review

2023-11-06 15:05 UTC, Aniak5 approved these changes
LGTM, thanks for making making the boolean types consistent!

2023-11-06 16:03 UTC, floydtree requested changes

2023-11-06 16:03 UTC, floydtree commented on dictionary.json
> +      "description": "The cookie attribute to only send cookies to the server with an encrypted request over the HTTPS protocol.",
Looks like you updated the description of the deprecated `secure` attribute instead of the new `is_secure` attribute

2023-11-06 16:06 UTC, Aniak5 commented on dictionary.json
> +      "description": "The cookie attribute to only send cookies to the server with an encrypted request over the HTTPS protocol.",
Nice catch Rajas

2023-11-06 16:09 UTC, Aniak5 approved these changes

2023-11-06 16:10 UTC, mikeradka commented on dictionary.json
> +      "description": "The cookie attribute to only send cookies to the server with an encrypted request over the HTTPS protocol.",
Nice catch @floydtree. I updated the `is_secure` desc and reverted the `secure` desc for keeping field history precise.

2023-11-06 16:11 UTC, Aniak5 approved these changes

2023-11-06 16:20 UTC, floydtree approved these changes

2023-11-08 16:07 UTC, mikeradka commented
Per Paul regarding `is_superseded` description: 

We need to be careful with the dictionary descriptions, especially when they are known to be overridden like this one. E.g. in the kb_article.json we apply it to KB articles, not to vendor patches. This comment may apply to all of the booleans here (separate from the name consistency). E.g. is_http_only doesn't immediately make me think of anything having to do with a cookie or JavaScript. In this case, http_cookie.json doesn't override the description so a future class might wonder if it should be used for a protocol related use case, e.g. a mode of a server API or something.

2023-11-08 16:16 UTC, Aniak5 commented
> Per @pagbabian-splunk regarding `is_superseded` description & others:
> 
> > We need to be careful with the dictionary descriptions, especially when they are known to be overridden like this one. E.g. in the kb_article.json we apply it to KB articles, not to vendor patches. This comment may apply to all of the booleans here (separate from the name consistency). E.g. is_http_only doesn't immediately make me think of anything having to do with a cookie or JavaScript. In this case, http_cookie.json doesn't override the description so a future class might wonder if it should be used for a protocol related use case, e.g. a mode of a server API or something.
> 
> Therefore, these descriptions should be more general, and then say 'see specific usage'. For specific usage, the classes using these attributes can always provide further clarification where needed
> 
> @Aniak5 , question from your side:
> 
> `is_secure` and `is_http_only` - which classes are you looking at those from? Maybe instead of the specific descriptions here, we can update the descriptions in the particular classes you need them for.

I agree, we should keep the refined/specific descriptions in the specific class and have a general description in the dictionary.

2023-11-08 16:53 UTC, mikeradka commented
Opened #845 to dive deeper into boolean attribute descriptions.

2023-11-09 20:53 UTC, pagbabian-splunk approved these changes
Given we will fix up the descriptions in a future PR...

2023-11-09 20:54 UTC, merged