Update the security_control profile to include access control check semantics, and firewall profile semantics.
ocsf/ocsf-schema pull request #851
Opened 2023-11-14 23:58 UTC by pagbabian-splunk

#### Related Issue: 
Firewall profile can be removed from 1.1-dev in lieu of this updated profile.
Authorization Information should be deprecated from the Actor object in lieu of this updated profile.
The Web Resource Access Activity class can be deprecated and this profile should be registered with Web Resource Activity to include the access control semantics.

#### Description of changes:
Per weekly call 11/14/2023 Updated the dictionary descriptions of disposition_id, firewall_rule, attacks, malware to include usage with security_control as well as finding.

Updated security_control profile to combine the disposition list with the firewall profile list, and for use with access control checks.  Added the firewall_rule attribute.  Added the Authorization Information attribute.

2023-11-15 17:20 UTC, zschmerber commented
The change looks like a good start, I was under the impression firewall rules would live under an optional `firewall` object inside the profile. Then we can have an object for each of different tools in that profile: firewall, DLP, IDS/IPS,Proxy, compliance etc?

2023-11-15 17:21 UTC, zschmerber commented
As we make this change do we want to remove/deprecate the `Authorization Result` object ?

2023-11-15 18:41 UTC, pagbabian-splunk commented
Yes, we will deprecate `Authorization Result` from `Actor` and point to this profile.
As for adding other control specific policies, I had done that in my previous PR that I pulled (sec_ctrl) but I think it is better to add them when we have those objects fleshed out and have use cases behind them.  There is a Policy object already, also within `Authorization Result` and `Account Change` but not sure if it covers the other areas sufficiently.

2023-11-15 22:13 UTC, zschmerber commented
After composing up this schema server I see that the `security_control` profile only apply across 2 categories. `Network Activity` and `System Activity`. Do we want to expand that to include more classes and categories?

2023-11-16 18:31 UTC, floydtree requested changes

2023-11-16 18:31 UTC, floydtree commented on dictionary.json
>        "enum": {
regarding the 0, 99 enum. Should we remove the definition form the dictionary? considering it's being defined in the profile later? 

If not, we can add the descriptions to the enum values and not define 0,99 in the profile. Just looking to simplify the definition.

2023-11-16 18:31 UTC, floydtree commented on profiles/security_control.json
> +        "99": {
This is ties in to the comment about enums in the dictionary.json file

2023-11-16 18:31 UTC, floydtree commented on profiles/security_control.json
> +          "description": "Granted access or allowed the action to the protected resource. For firewalls or proxies, the request is forwarded and is a network terminating action."
`...is a network terminating action.` Not sure if this is accurate for an allowed action/disposition.

2023-11-22 18:57 UTC, pagbabian-splunk commented
> After composing up this schema server I see that the `security_control` profile only apply across 2 categories. `Network Activity` and `System Activity`. Do we want to expand that to include more classes and categories?

Yes, we need to do that, for example for the Web Resource Activity in Application Activity, in order to be able to deprecate Web Resource Access Activity.  There are a number of other changes after this PR is merged - I just wanted to keep things more focused.

2023-11-22 18:59 UTC, pagbabian-splunk commented on profiles/security_control.json
> +          "description": "Granted access or allowed the action to the protected resource. For firewalls or proxies, the request is forwarded and is a network terminating action."
This comes over from Adam's `disposition_id` from his `firewall_profile` - I wanted to capture it.

2023-11-23 21:15 UTC, pagbabian-splunk commented on dictionary.json
>        "enum": {
Updated the descriptions for this attribute as well as many others that had no descriptions.

2023-11-23 21:15 UTC, pagbabian-splunk commented on profiles/security_control.json
> +        "99": {
Updated the descriptions for this attribute as well as many others that had no descriptions.

2023-11-23 21:15 UTC, pagbabian-splunk commented on profiles/security_control.json
> +          "description": "Granted access or allowed the action to the protected resource. For firewalls or proxies, the request is forwarded and is a network terminating action."
I will let Adam comment, but for now resolving this.

2023-11-24 14:17 UTC, floydtree commented on profiles/security_control.json
> +          "description": "Granted access or allowed the action to the protected resource. For firewalls or proxies, the request is forwarded and is a network terminating action."
I see, leaving it unresolved, otherwise we risk losing track of it. @adplotzk can you take a look at this description and confirm it's accurate? The thing I am trying to understand is - why would an allowed connection be a network termination action?

2023-11-29 01:48 UTC, zschmerber commented
We need to solve for a question like this:
boss: _"hi, security analyst. Tell me how the attacker got into our network and make it snappy."_
analyst: _"ok boss."_

 `index=* ip = 1.1.1.1 OR actor.user=zzzz OR hostname = xxxx disposition_action = success`

If we have to write: `index=* ip = 1.1.1.1 OR actor.user=zzzz OR hostname = xxxx disposition= (Logged OR Allowed OR Tagged OR .....)`  to answer this question it is not efficient.

A new field in the profile like disposition_action were the result is allowed or blocked would allow us to fit all of those dispostion_id's into a simple binary result. 

The other option is to slim down the dispostion_id into 3-6 fields(allowed, blocked, other...) .  Place the dispotion_id attributes into the connected object in the profile like "firewall_rule" and get the disposition action detail from that object.

2023-12-01 20:53 UTC, pladam commented on profiles/security_control.json
> +          "description": "Granted access or allowed the action to the protected resource. For firewalls or proxies, the request is forwarded and is a network terminating action."
```
{
  "description": "The attributes that identify firewall events such as firewall_rule.",
  "meta": "profile",
  "caption": "Firewall",
  "name": "firewall",
  "annotations": {
    "group": "primary"
  },
  "attributes": {
    "firewall_rule": {
      "requirement": "required"
    },
    "disposition": {
      "requirement": "optional"
    },
    "disposition_id": {
      "requirement": "required",
      "enum": {
        "1": {
          "caption": "Allowed",
          "description": "Allows the request."
        },
        "2": {
          "caption": "Blocked",
          "description": "Blocks the request."
        },
        "3": {
          "caption": "Dropped",
          "description": "Request detected as a threat and resulted in the connection being dropped."
        },
        "4": {
          "caption": "Alert",
          "description": "Request detected as a threat and resulted in a nonfiction but request was not blocked."
        },
        "5": {
          "caption": "Count",
          "description": "Counts the request but does not determine whether to allow it or block it."
        },
        "6": {
          "caption": "Reset",
          "description": "Request detected as a threat and resulted in the connection being reset."
        },
        "7": {
          "caption": "Captcha",
          "description": "Requires the end user to solve a CAPTCHA puzzle to prove that a human being is sending the request."
        },
        "8": {
          "caption": "Challenge",
          "description": "Runs a silent challenge that requires the client session to verify that it's a browser, and not a bot."
        }
      }
    }
  }
}
```

2023-12-02 00:26 UTC, zschmerber approved these changes
Changes look good to just need @pagbabian-splunk to incorporate @pladam descriptions. we can add the "disposition_action" field later.

2023-12-06 23:36 UTC, mikeradka approved these changes
Looks great.

2023-12-06 23:55 UTC, maxhotta approved these changes

2023-12-07 14:58 UTC, floydtree requested changes
Looks great, the only thing that appears to be pending is the comment on the `Allowed` dispostion_id's description.

2023-12-07 21:20 UTC, pagbabian-splunk commented on profiles/security_control.json
> +          "description": "Granted access or allowed the action to the protected resource. For firewalls or proxies, the request is forwarded and is a network terminating action."
Fixed the Allow and Block descriptions to remove the terminating connection wording.

2023-12-07 21:25 UTC, adplotzk approved these changes
addition of firewall_rule in this context is in line with our previous outline, approved.

2023-12-07 21:28 UTC, merged