Additional metaschemas
ocsf/ocsf-schema pull request #867
Opened 2023-11-22 13:54 UTC by alanisaac

#### Related Issue: 
Part of #736

These metaschemas have been tested against a version of the `ocsf-validator` based on this PR: https://github.com/query-ai/ocsf-validator/pull/3.  As a result, the following issues were found:

* https://github.com/ocsf/ocsf-schema/pull/864
* https://github.com/ocsf/ocsf-schema/pull/859

These should be resolved before merging this PR.

#### Description of changes:
This PR implements additional metaschemas for:

* `dictionary`
* `extension`
* `profile`

It also adds the following attributes:

* `@deprecated`
* `sibling`

And refactors the `$include` attribute to be more reusable.

Finally, it adds a `description` to the existing `object` and `event` types (and all new metaschemas).

2023-11-27 16:23 UTC, floydtree requested changes

2023-11-27 16:23 UTC, floydtree commented on metaschema/semver.schema.json
> +    "pattern": "^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-
referring to the conversation [here](https://opencybersecu-lz97379.slack.com/archives/C05V6MPAEMS/p1700677723123009), I think it's best to stick to the actual semver format, consequently not have a `v` in the regex.

2023-11-27 16:23 UTC, floydtree commented on metaschema/extension.schema.json
> +    "required": [
Probably good to make description a required property

2023-11-27 16:23 UTC, floydtree commented on metaschema/attribute.schema.json
Adding a required property in this subschema to ensure `requirement` key is always added would be great. This is something that OCSF is currently inconsistent about.

2023-11-28 00:57 UTC, alanisaac commented on metaschema/extension.schema.json
> +    "required": [
Fixed in 891d147

2023-11-28 01:09 UTC, alanisaac commented on metaschema/attribute.schema.json
It's slightly more complicated, though probably worthwhile to do.  This subschema maps to attributes _generally_ which was also used for dictionary `attributes`.  

I think I need to split those out, as they have their own set of features -- they don't have `requirement` and do have `type`, e.g.  

I can work on fixing this.

2023-12-02 02:10 UTC, alanisaac commented on metaschema/object.schema.json
> +                    "type": "array",
That's correct.  I linked it to #792 in the description (the PR) but should have also linked to #791 (the issue).  Fixed.

2023-12-02 02:14 UTC, alanisaac commented on metaschema/semver.schema.json
> +    "pattern": "^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-
Could this be a follow-up?  I can make an additional PR to specifically remove "v" from both the metaschema and schema definition files.

With the advent of the new `ocsf-validator` tool as a GitHub check, I'd want to make sure that any metaschema changes are in sync with schema definition changes, so that PRs like https://github.com/query-ai/ocsf-validator/pull/3 can be easily merged and the pinned version in this library updated.  Once that happens, a change like this won't be possible without doing both.

2023-12-04 15:07 UTC, floydtree commented on metaschema/semver.schema.json
> +    "pattern": "^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-
yeah sounds good

2023-12-05 02:49 UTC, alanisaac commented on metaschema/attribute.schema.json
I addressed this in part, so attributes and dictionary attributes are split out and are more restrictive in what fields they each allow.  Unfortunately there are a few violations of the `requirement` property today within the Windows extension.  

I can put up another PR to address these, but like the [regex discussion](https://github.com/ocsf/ocsf-schema/pull/867#discussion_r1406397331), might be worth getting this in first and addressing that as a follow-up?

2023-12-05 18:02 UTC, floydtree commented on metaschema/attribute.schema.json
Fair, we can bring it in as fast follow along with the semver correction change.

2023-12-05 20:14 UTC, alanisaac commented
@floydtree I think your comments are resolved, with the note that I have two follow-ups:

* the `v` for semver versions, and fixing existing usages
* making the `requirement` field required, and fixing existing gaps

2023-12-07 00:32 UTC, dkolbly approved these changes
Huge progress :rocket:

2023-12-07 20:38 UTC, mikeradka approved these changes

2023-12-07 20:39 UTC, merged