[DRAFT] Proposal to add Datastore Event Class 6005
ocsf/ocsf-schema pull request #874
Opened 2023-11-30 05:42 UTC by pladam

#### Related Issue:  [DRAFT] Proposal to add Datastore Event Class 6005

#### Description of changes: 

The following changes are required for this event class:

### New Objects
- database
- databucket
- table
- query_info

### New Attributes
database_type
database_type_id
databucket_type
databucket_type_id
last_updated_time
datastore_query

2023-12-01 13:22 UTC, floydtree commented
Hey @Aniak5 would like to get your review on this one since you had created a similar class a few months back.

2023-12-04 21:33 UTC, pladam commented on dictionary.json
> +    "databucket_type": {
Removed specific types and replaced with updated type util

2023-12-04 21:34 UTC, pladam commented on dictionary.json
> +    "databucket_type_id": {
Removed specific types and replaced with updated type util

2023-12-04 21:36 UTC, pladam commented on dictionary.json
> +    "datastore_query": {
updated to query_string

2023-12-04 21:38 UTC, pladam commented on dictionary.json
> +    "last_updated_time": {
updated to modified time

2023-12-04 21:40 UTC, pladam commented on dictionary.json
> +    "partition": {
remove, not needed within the schema at this time

2023-12-05 17:41 UTC, Aniak5 commented on events/application/datastore_activity.json
> +        },
Given that this is `datastore` activity, should we add an `at_least_one` constraint for `database`, `databucket`, or `table`?

2023-12-05 18:33 UTC, pladam commented on events/application/datastore_activity.json
> +        },
I think thats a good idea

2023-12-12 19:24 UTC, zschmerber submitted a review, later dismissed
looks good to me

2023-12-13 17:23 UTC, Aniak5 commented on dictionary.json
> +      "description": "The databucket object represents a databucket is a basic container that holds data, typically organized through the use of data partitions.",
We could make this a bit more clear by rewording to something like `The data bucket object encapsulates details about a container that stores data, typically organized using data partitions.`

2023-12-13 17:26 UTC, zschmerber commented on dictionary.json
> +    "databucket": {
If we need to change it it would be good to avoid "_" as they often are used in conventions. So databucket or bucket would be my vote. 
https://github.com/ocsf/ocsf-docs/blob/main/Understanding%20OCSF.md#conventions

2023-12-13 17:29 UTC, Aniak5 commented on objects/query_info.json
> +      "description": "A string representating the query code being run. For example: SELECT *</code>",
Misspelled `representating` should be `representing`

2023-12-13 17:30 UTC, Aniak5 commented on objects/query_info.json
> +      "requirement": "optional"
The `query_string` should probably be `required` within this object.

2023-12-13 17:36 UTC, Aniak5 commented on objects/query_info.json
> +      "description": "The size of the data returned from the query.",
I have mixed feelings about the `bytes_out` directionality. It makes sense from the perspective of the datastore because its the bytes leaving the data store but from the perspective of a query it could be thought of as `bytes_in`. What are your thoughts on just using `bytes` to make this object more generic?

2023-12-13 17:39 UTC, Aniak5 commented on dictionary.json
> +      "description": "The query info object contains data relating to accessing data within a datastore. If you need to access, manipulate, delete, or retrieve data from a datastore, you'll need a da
Maybe reword this a bit to something along the lines of: "The query info object holds information related to data access within a datastore. To access, manipulate, delete, or retrieve data from a datastore, a database query must be written using a specific syntax."

2023-12-13 17:44 UTC, Aniak5 commented on objects/database.json
> +      "description": "The most recent detection time of the activity or object. See specific usage.",
The description needs to be updated, could be: `The most recent time when any changes, updates, or modifications were made within the database.`

2023-12-13 17:45 UTC, Aniak5 commented on objects/database.json
> +      "caption": "Description",
Don't need a caption here as it is identical to the dictionary. Unless we want to change it to `Database Description`

2023-12-13 17:49 UTC, Aniak5 commented on objects/database.json
> +    }
Something in this object should be required so that we don't wind up with an empty `database` struct. Maybe a `at_least_one` constraint with `name` and `uid`.

2023-12-13 17:52 UTC, Aniak5 commented on objects/databucket.json
> +      "description": "The most recent detection time of the activity or object. See specific usage.",
The description needs to be updated, could be: `The most recent time when any modifications were made to the databucket`.

2023-12-13 17:53 UTC, Aniak5 commented on objects/table.json
> +      "description": "The most recent detection time of the activity or object. See specific usage.",
The description needs to be updated, could be: `The most recent time when any modifications were made to the table`.

2023-12-15 15:53 UTC, adplotzk commented on objects/query_info.json
> +      "description": "A string representating the query code being run. For example: SELECT *</code>",
updated.

2023-12-15 15:53 UTC, adplotzk commented on objects/query_info.json
> +      "requirement": "optional"
updated.

2023-12-15 15:57 UTC, adplotzk commented on events/application/datastore_activity.json
> +        },
updated

2023-12-19 14:39 UTC, adplotzk submitted a review, later dismissed

2023-12-19 17:10 UTC, mikeradka submitted a review, later dismissed

2023-12-19 17:26 UTC, mikeradka approved these changes

2023-12-19 18:54 UTC, pagbabian-splunk submitted a review, later dismissed

2023-12-19 21:01 UTC, floydtree requested changes

2023-12-19 21:01 UTC, floydtree commented on objects/databucket.json
> +  "extends": "object",
`.. used for databuckets which are typically cloud-based containers..` This is a bit misleading, since containers are a thing by themselves. Good to keep it simple the way Paul suggested above.

2023-12-19 23:33 UTC, pladam commented on objects/databucket.json
> +  "extends": "object",
Updated based on specifications above

2023-12-19 23:35 UTC, pladam reviewed
Updated description. Please review

2023-12-20 14:55 UTC, floydtree commented on objects/databucket.json
> +  "extends": "object",
Thanks, but same applies to the description in the dictionary. You'll need to update that as well.

2023-12-20 15:14 UTC, floydtree requested changes
Good stuff! The class looks almost ready, however take a look at the specific comments for the changes that are still needed.

Also, please ensure the commit messages are self explanatory, the current commit messages do not convey what is being changed. This is crucial if we ever to have to go back and look for specific commits, or creating a release.

2023-12-20 15:14 UTC, floydtree commented on events/application/datastore_activity.json
> +            "requirement": "optional"
Better, to mark these - database, databucket as recommended, considering these are the key attributes in this class. Typically, all the primary attributes should be recommended.

2023-12-20 15:14 UTC, floydtree commented on events/application/datastore_activity.json
> +        "dst_endpoint": {
Good to act a specific description(considering you have added one for src_endpoint). It is particularly important in here since, there are quite a few similar objects (should a mapper populate dst_endpoint if they are populating databucket? for instance) A description clarifying these relationships will help.

2023-12-20 15:14 UTC, floydtree commented on objects/database.json
> +      "requirement": "required"
The string siblings should be recommended (current strategy used throughout OCSF). Unless there is a good reason to enforce people to populate both, but that would be a bigger discussion and not limited to this object.

2023-12-20 15:14 UTC, floydtree commented on objects/databucket.json
> +      "requirement": "required"
Same comment as in the database object - String siblings -recommended.

2023-12-20 15:14 UTC, floydtree commented on objects/table.json
> +  "extends": "object",
extend _entity instead, to inherit the constraints for uid, name.

2023-12-20 15:14 UTC, floydtree commented on objects/query_info.json
> +  "extends": "object",
extend _entity instead, to inherit the constraints for uid, name.

2023-12-20 15:14 UTC, floydtree commented on objects/databucket.json
> +  "extends": "object",
extend _entity instead, to inherit the constraints for uid, name.

2023-12-20 15:14 UTC, floydtree commented on objects/database.json
> +  "extends": "object",
extend _entity instead, to inherit the constraints for uid, name.

2023-12-20 15:36 UTC, adplotzk commented on events/application/datastore_activity.json
> +            "requirement": "optional"
changing to recommended, also I have these at "at least one" required

2023-12-20 15:44 UTC, adplotzk commented on events/application/datastore_activity.json
> +        "resources": {
I agree this is not needed in this context

2023-12-20 15:46 UTC, adplotzk commented on objects/databucket.json
> +  "extends": "object",
updated.

2023-12-20 15:47 UTC, adplotzk commented on objects/table.json
> +  "extends": "object",
updated

2023-12-20 15:55 UTC, adplotzk commented on objects/database.json
> +      "requirement": "required"
changing type to recommended

2023-12-20 15:56 UTC, adplotzk commented on objects/databucket.json
> +      "requirement": "required"
changing type to recommended

2023-12-20 15:56 UTC, adplotzk commented on dictionary.json
> +      "description": "The databucket object is used for databuckets which are typically cloud-based container services used for object storage. Databuckets are often organized in directory like struc
I've addressed all the comments here - please review

2023-12-20 22:14 UTC, zschmerber approved these changes
Thanks for all the hard work on this.

2023-12-20 22:33 UTC, pagbabian-splunk commented
Looks good now for DML activities (data manipulation).  Would there be events associated with DML activities (i.e. metadata create, update, delete; create table, update table, delete table)?

2023-12-21 13:58 UTC, Aniak5 commented on events/application/datastore_activity.json
> +    "description": "Datastore events describe general activities (Read, Update, Query, Delete, etc.) which affect datastores or data within those datastores, e.g. (AWS RDS, AWS S3)",
Nit: Can we add a `.` at the end of this description?

2023-12-21 14:03 UTC, Aniak5 commented on objects/database.json
> +      "description": "The size of database, in bytes.",
Nit: In its current form it feels like the sentence is incomplete, can we change it to `The size of the database in bytes.`

2023-12-21 14:06 UTC, Aniak5 commented on objects/databucket.json
> +      "description": "The size of data bucket, in bytes.",
Nit: Same comment as above and for consistency lets stick with `databucket` instead of `data bucket`. `The size of the the databucket in bytes.`.

2023-12-21 14:07 UTC, Aniak5 commented on objects/databucket.json
> +      "description": "The database type.",
This should be `The databucket type.`

2023-12-21 14:16 UTC, Aniak5 commented on objects/query_info.json
> +      "description": "A string representing the query code being run. For example: SELECT *</code>",
Missing the `<code>` before the `SELECT`. The example might be a little more clear if it is changed to `SELECT * FROM my_table` but i'm fine w/it as is too.

2023-12-21 14:43 UTC, adplotzk commented on events/application/datastore_activity.json
> +    "description": "Datastore events describe general activities (Read, Update, Query, Delete, etc.) which affect datastores or data within those datastores, e.g. (AWS RDS, AWS S3)",
updated

2023-12-21 14:43 UTC, adplotzk commented on objects/database.json
> +      "description": "The size of database, in bytes.",
updated

2023-12-21 14:44 UTC, adplotzk commented on objects/databucket.json
> +      "description": "The size of data bucket, in bytes.",
updates

2023-12-21 14:45 UTC, adplotzk commented on objects/databucket.json
> +      "description": "The database type.",
updated

2023-12-21 14:46 UTC, adplotzk commented on objects/query_info.json
> +      "description": "A string representing the query code being run. For example: SELECT *</code>",
updated

2023-12-21 14:54 UTC, Aniak5 submitted a review, later dismissed
Looks awesome @adplotzk, excited to finally have this event class!!

2023-12-21 14:57 UTC, Aniak5 commented on objects/table.json
> +      "description": "The size of data table, in bytes.",
One last change! `The size of the data table in bytes.`

2023-12-21 16:12 UTC, pladam commented on objects/table.json
> +      "description": "The size of data table, in bytes.",
updated

2023-12-21 16:41 UTC, Aniak5 approved these changes

2023-12-21 17:00 UTC, zschmerber approved these changes

2023-12-21 18:11 UTC, floydtree approved these changes

2023-12-21 18:12 UTC, merged