The new Detection Finding event class
ocsf/ocsf-schema pull request #877
Opened 2023-12-01 21:29 UTC by floydtree

#### Related Issue: https://github.com/ocsf/ocsf-schema/discussions/789

This class has been created based on a series of discussions in the Findings group. Relevant info can be found in the discussion linked above.

#### Description of changes:
1. Adding a new event class `detection_finding`
2. Adding a new object `evidences` to account for various evidence artifacts presented in a detection/alert type finding.
3. Updating description of the base finding class to make attributes specific to the findings category.

#### Follow-up-
1. Add Security Control profile once ready - https://github.com/ocsf/ocsf-schema/pull/851/
2. Add elaborate descriptions to impact, risk, confidence family of attributes and their enumerations. (fyi @irakledibm @zschmerber)

2023-12-01 21:48 UTC, irakledibm approved these changes
looks great

2023-12-04 16:04 UTC, acockburn requested changes

2023-12-04 16:04 UTC, acockburn commented on events/findings/detection_finding.json
> +    },
I'd appreciate a pointer or description on how to approach these risk fields since they seem similar. I am sure it was discussed but it would be good to have it explicitly mentioned or referenced her.

2023-12-04 18:26 UTC, acockburn approved these changes

2023-12-04 19:57 UTC, zschmerber approved these changes
looks good and worked in my test.

2023-12-07 18:05 UTC, pagbabian-splunk commented
One more small point: I assume a `finding` can be the result of analysis of other findings.  Not just activities.

In `finding_info` we have `related_events` described as: "Describes events related to a finding or detection as identified by the security product."

I think it would be good to call out that the events can be other findings.  E.g. the `related_analytics` could be used to aggregate other findings, say that shared the same MITRE techniques, or shared the same device, IP etc.

This would just be for instruction in docs.

2023-12-07 20:52 UTC, pagbabian-splunk approved these changes

2023-12-07 20:53 UTC, merged