Adding required attributes and configurations for network firewall events
ocsf/ocsf-schema pull request #904
Opened 2024-01-02 03:34 UTC by pladam

#### Related Issue: 

#### Description of changes:

Adding the following net new attributes:

    "chunks": {
      "caption": "Chunks",
      "description": "The total number of chunks (in and out).",
      "type": "long_t"
    },
    "chunks_in": {
      "caption": "Chunks In",
      "description": "The number of chunks sent from the destination to the source.",
      "type": "long_t"
    },
    "chunks_out": {
      "caption": "Chunks Out",
      "description": "The number of chunks sent from the source to the destination.",
      "type": "long_t"
    },
    "expiration_reason": {
      "caption": "Expiration Reason",
      "description": "The expiration reason. See specific usage.",
      "type": "string_t"
    },
    "nat_ip": {
      "caption": "NAT IP",
      "description": "If NAT was performed, the post-NAT IP address.",
      "type": "ip_t"
    },
    "nat_port": {
      "caption": "NAT Port",
      "description": "If NAT was performed, the post-NAT network port.",
      "type": "integer_t"
    },

#### Adding container profile availability to network event base 
    "container"
  ],
  "attributes": {
    "$include": [
      "profiles/container.json"

#### Adding following to network_activity.json
    },
    "http_request": {
      "group": "primary",
      "requirement": "optional"
    },

#### adding following to endpoint.json

    },
    "zone": {
      "requirement": "optional"
    }

#### adding following to network_connection_infio.json
    "session": {
      "requirement": "optional"
    },

#### adding following to network_endpoint.json
    "hostname": {
      "description": "The endpoint hostname.",
      "requirement": "optional"
    },
    "hw_info": {
      "requirement": "optional"
    },
    "mac": {
      "description": "The device Media Access Control (MAC) address.",
      "requirement": "optional"
    },
    "nat_ip": {
      "description": "If NAT was performed, the post-NAT IP address.",
      "requirement": "optional"
    },
    "nat_port": {
      "description": "If NAT was performed, the post-NAT network port.",
      "requirement": "optional"
    },
    "os": {
      "description": "The endpoint device operating system.",
      "requirement": "optional"
    },

#### adding following to network_traffic.json
    "chunks": {},
    "chunks_in": {},
    "chunks_out": {}

#### adding following to session.json
    "count": {
      "description": "The number of identical sessions spawned from the same source IP, destination IP, application, and content/threat type seen over a period of time.",
      "requirement": "optional"
    },
    "expiration_reason": {
      "description": "The reason which triggered the session expiration.",
      "requirement": "optional"
    },

2024-01-03 17:46 UTC, Aniak5 commented on dictionary.json
> +      "description": "The total number of chunks (in and out).",
What is the unit within a chunk, is it bytes? We should probably specify that within the description and mention whether a chunk size is variable or not. Maybe we should add "See specific usage." here in the dictionary and add use case specifics where the attribute is used.

2024-01-03 17:59 UTC, Aniak5 commented on objects/network_endpoint.json
> +    },
These additions (hostname, hw_info, mac, os) to `network_endpoint` are all available within the `device` object that also extends `endpoint`. We have had a few discussions about potentially consolidating these, seems like they are slowly converging to the same object 😃

2024-01-03 18:37 UTC, ablyler commented on dictionary.json
> +      "description": "The total number of chunks (in and out).",
What about using the packets from the `network_traffic` object? Are there chunks different than packets?

2024-01-04 05:31 UTC, pladam commented on objects/network_endpoint.json
> +    },
Keeping this change as discussed on the network call

2024-01-04 05:32 UTC, pladam commented on dictionary.json
> +      "description": "The total number of chunks (in and out).",
Added "see specific usage" to each.

2024-01-04 14:52 UTC, floydtree requested changes
This PR seems to include already merged commits from an older PR. I would recommend, closing this one and create a new PR with an up-to-date base branch.

Also, as mentioned in the previous PR, please ensure your commit messages are descriptive instead of Update X, Update Y. Clearer commit messages would help in the cases if we have go back and check a specific commit.

2024-01-04 14:59 UTC, floydtree commented on events/application/datastore_activity.json
Better to separate out this change in a separate PR. One thing to always keep in mind is - we need to create release notes when we release a version, to that specific, targeted PRs would help massively.

2024-01-04 15:02 UTC, floydtree requested changes

2024-01-04 15:02 UTC, floydtree commented on events/application/datastore_activity.json
Better to separate out this change in a separate PR. One thing to always keep in mind is - we need to create release notes when we release a version, to that specific, targeted PRs would help massively.

2024-01-04 15:02 UTC, floydtree commented on events/application/datastore_activity.json
> +          "caption": "Type ID",
Type ID caption is already in use for the base type_uid field. A caption like "Datastore Type ID" would help distinguish.

2024-01-04 15:51 UTC, pladam commented on events/application/datastore_activity.json
> +          "caption": "Type ID",
updated

2024-01-04 16:10 UTC, closed without merging