Making required updated to support network firewalls - Palo Alto
ocsf/ocsf-schema pull request #910
Opened 2024-01-04 16:16 UTC by pladam

#### Related Issue: 

#### Description of changes:

Adding the following net new attributes to dictionary:

    "chunks": {
      "caption": "Chunks",
      "description": "The total number of chunks (in and out).",
      "type": "long_t"
    },
    "chunks_in": {
      "caption": "Chunks In",
      "description": "The number of chunks sent from the destination to the source.",
      "type": "long_t"
    },
    "chunks_out": {
      "caption": "Chunks Out",
      "description": "The number of chunks sent from the source to the destination.",
      "type": "long_t"
    },
    "expiration_reason": {
      "caption": "Expiration Reason",
      "description": "The expiration reason. See specific usage.",
      "type": "string_t"
    },

#### Adding container profile availability to network event base 
    }   
     "container"
      ],
      "attributes": {
        "$include": [
          "profiles/container.json"
    }

#### adding following to endpoint.json
    },
    "zone": {
      "requirement": "optional"
    }

#### adding following to network_connection_infio.json
    "session": {
      "requirement": "optional"
    },

#### adding following to network_endpoint.json
    "hostname": {
      "description": "The endpoint hostname.",
      "requirement": "optional"
    },
    "hw_info": {
      "requirement": "optional"
    },
    "mac": {
      "description": "The device Media Access Control (MAC) address.",
      "requirement": "optional"
    },
    "os": {
      "description": "The endpoint device operating system.",
      "requirement": "optional"
    },
    "proxy_endpoint": {
      "description": "The network proxy endpoint object describes a proxy server, which acts as an intermediary between a client requesting a resource and the server providing that resource.",
      "requirement": "optional"
    },

#### adding following to network_traffic.json
    "chunks": {
      "description": "The total number of chunks (in and out)."
    },
    "chunks_in": {
      "description": "The number of chunks sent from the destination to the source."
    },
    "chunks_out": {
      "description": "The number of chunks sent from the source to the destination."
    }

#### adding following to session.json
    "count": {
      "description": "The number of identical sessions spawned from the same source IP, destination IP, application, and content/threat type seen over a period of time.",
      "requirement": "optional"
    },
    "expiration_reason": {
      "description": "The reason which triggered the session expiration.",
      "requirement": "optional"
    },

#### adding type/type_id to datastore.json event class
        "type": {
          "caption": "Type",
          "description": "The datastore resource type (e.g. database, datastore, or table).",
          "requirement": "optional"
        },
        "type_id": {
          "caption": "Type ID",
          "description": "The normalized datastore resource type identifier.",
          "enum": {
            "99": {
              "caption": "Other",
              "description": "The datastore resource type is not mapped."
            },
            "0": {
              "caption": "Unknown",
              "description": "The datastore resource type is unknown."
            },
            "1": {
              "caption": "Database"
            },
            "2": {
              "caption": "Databucket"
            },
            "3": {
              "caption": "Table"
            }
          },
          "requirement": "recommended"
        },

2024-01-08 21:01 UTC, pagbabian-splunk commented
Generally looks good.  `endpoint` already has the attribute `hostname` so no need to add it to `network_endpoint`.  You've changed it from Recommended to Optional - if that is important, I suppose that is why you added it?  Should it be optional at the `endpoint` level?  (need to understand any side effects of that for other extended classes).

2024-01-09 17:06 UTC, pladam commented
> Generally looks good. `endpoint` already has the attribute `hostname` so no need to add it to `network_endpoint`. You've changed it from Recommended to Optional - if that is important, I suppose that is why you added it? Should it be optional at the `endpoint` level? (need to understand any side effects of that for other extended classes).

Hostname has been removed from this change

2024-01-09 22:52 UTC, Aniak5 commented on objects/network_endpoint.json
> +      "requirement": "optional"
lets add this to the `endpoint` object instead since both `device` and `network_endpoint` are using this now and extending the `endpoint`. And remove from the `device object`.

2024-01-09 22:53 UTC, Aniak5 commented on objects/network_endpoint.json
> +    "mac": {
Same comment here: lets add this to the endpoint object instead since both device and network_endpoint are using this now and extending the endpoint. And remove from the device object.

2024-01-09 22:54 UTC, Aniak5 commented on objects/network_endpoint.json
> +      "description": "The endpoint device operating system.",
Same comment here: lets add this to the `endpoint` object instead since both `device` and `network_endpoint` are using this now and extending the `endpoint`. And remove from the `device object`.

2024-01-09 22:55 UTC, Aniak5 commented on objects/network_traffic.json
> +      "description": "The total number of chunks (in and out)."
All these chunks attributes are defined in the dictionary already with the same description. Don't need the description here

2024-01-09 22:55 UTC, Aniak5 commented on objects/network_traffic.json
> +      "description": "The number of chunks sent from the destination to the source."
All these chunks attributes are defined in the dictionary already with the same description. Don't need the description here

2024-01-09 22:55 UTC, Aniak5 commented on objects/network_traffic.json
> +      "description": "The number of chunks sent from the source to the destination."
All these chunks attributes are defined in the dictionary already with the same description. Don't need the description here

2024-01-09 22:56 UTC, Aniak5 commented on objects/network_traffic.json
> +      "description": "The total number of chunks (in and out)."
Lets add `requirement` here.

2024-01-09 22:56 UTC, Aniak5 commented on objects/network_traffic.json
> +      "description": "The number of chunks sent from the destination to the source."
Lets add `requirement` here.

2024-01-09 22:56 UTC, Aniak5 commented on objects/network_traffic.json
> +      "description": "The number of chunks sent from the source to the destination."
Lets add `requirement` here.

2024-01-11 22:35 UTC, pladam commented on objects/network_endpoint.json
> +      "requirement": "optional"
Updated

2024-01-11 22:35 UTC, pladam commented on objects/network_endpoint.json
> +      "description": "The endpoint device operating system.",
Updated

2024-01-11 22:35 UTC, pladam commented on objects/network_endpoint.json
> +    "mac": {
Updated

2024-01-11 22:37 UTC, pladam commented on objects/network_traffic.json
> +      "description": "The total number of chunks (in and out)."
updated

2024-01-11 22:37 UTC, pladam commented on objects/network_traffic.json
> +      "description": "The number of chunks sent from the destination to the source."
updated

2024-01-11 22:38 UTC, pladam commented on objects/network_traffic.json
> +      "description": "The number of chunks sent from the source to the destination."
updated

2024-01-12 19:57 UTC, floydtree requested changes

2024-01-12 19:57 UTC, floydtree commented on objects/network_endpoint.json
> +    "proxy_endpoint": {
A question, how does this fit/work with Network Proxy profile? If all the network _endpoint attributes have proxy_endpoint attribute, how does it contextually fit with other attributes added via Network Proxy Profile in network classes?

2024-01-12 19:57 UTC, floydtree commented on dictionary.json
> +      "description": "The total number of chunks (in and out). See specific usage.",
Probably good to explicitly define chunks. Is there an IETF definition of chunks that we can add?

2024-01-12 19:57 UTC, floydtree commented on dictionary.json
> +    "chunks_in": {
Same as `chunks`

2024-01-12 19:57 UTC, floydtree commented on dictionary.json
> +    "chunks_out": {
Same as `chunks`

2024-01-12 19:57 UTC, floydtree commented on objects/endpoint.json
> +    "hw_info": {
If you are adding hw_info, os to endpoint, you should clean these up from device object definition (which inherits from endpoint)

2024-01-12 19:57 UTC, floydtree commented on objects/endpoint.json
> +    "os": {
If you are adding hw_info, os to endpoint, you should clean these up from device object definition (which inherits from endpoint)

2024-01-12 20:55 UTC, pladam commented on objects/network_endpoint.json
> +    "proxy_endpoint": {
On the network call it was discussed that a single proxy endpoint was not sufficient to encompass the logs which would be generated from doing multiple hops. For example, a source endpoint might hop to a proxy, before going to a proxy and being routed to a dest proxy. This led us to the conclusion that all endpoints could be viable for proxy.

2024-01-12 21:00 UTC, pladam commented on dictionary.json
> +      "description": "The total number of chunks (in and out). See specific usage.",
There is not. Anya and I looked but couldn't find a consistent definitions for chunks

2024-01-12 21:00 UTC, pladam commented on dictionary.json
> +    "chunks_in": {
There is not. Anya and I looked but couldn't find a consistent definitions for chunks

2024-01-12 21:00 UTC, pladam commented on dictionary.json
> +    "chunks_out": {
There is not. Anya and I looked but couldn't find a consistent definitions for chunks

2024-01-12 21:00 UTC, pladam commented on objects/endpoint.json
> +    "hw_info": {
Will update soon

2024-01-12 21:00 UTC, pladam commented on objects/endpoint.json
> +    "os": {
will update soon

2024-01-12 21:51 UTC, pladam commented on objects/endpoint.json
> +    "hw_info": {
implemented

2024-01-12 22:56 UTC, pladam commented on dictionary.json
> +      "description": "The total number of chunks (in and out). See specific usage.",
Updated

2024-01-12 22:57 UTC, pladam commented on dictionary.json
> +    "chunks_in": {
Updated

2024-01-12 23:38 UTC, pagbabian-splunk approved these changes

2024-01-14 20:05 UTC, Aniak5 approved these changes
LGTM!

2024-01-16 15:42 UTC, floydtree approved these changes
Looks good!

2024-01-16 15:43 UTC, merged