Entity Change event class:
ocsf/ocsf-schema pull request #914
Opened 2024-01-04 21:48 UTC by maxhotta

Used to report security state changes for managed entities.
This class was ported from the entity change event class that was part of the security category in the ICD schema.

2024-01-08 21:31 UTC, rmouritzen-splunk submitted a review, later dismissed

2024-01-08 22:26 UTC, pagbabian-splunk commented
A few questions: We have an Entity Management class in the IAM category, and this will be an Entity Change class but in the Application category.  It has activities more akin to the Discovery category (i.e. `Logged`), rather than any actual update activities (so I guess, just logging the change?).  

That's ok, as long as it is explainable - e.g. Discovery classes are proactive (e.g. scans for changes, vulns etc.) while other categories are what would be asynchronously received events for the most part.

This class logs security related changes to a `Managed Entity` - why is it in the Application category?  What is the application, or is it an application layer service (e.g. Web, Email, Systems Management)?  Could it live in the IAM category where the `Entity Management` class resides?

Three possible category choices: IAM, Discovery (only if proactive), and Application.

2024-01-09 01:21 UTC, maxhotta commented
@pagbabian-splunk It's been a little while since we'd discussed this last, but the purpose for this class is to capture security related opstates like changes in the compliance or infected status of applications on devices. It was originally in the Security category of the ICD schema, but in the absence of that category, we'd thought that the application category made the most sense.

2024-01-09 17:25 UTC, floydtree commented on events/application/entity_change.json
> +  "caption": "Entity Change",
Perhaps `Entity State Change` could be better at conveying the intention of this class

2024-01-12 20:17 UTC, maxhotta commented
@pagbabian-splunk Is the consensus that we move this class into the Discovery category?

2024-01-12 20:33 UTC, pagbabian-splunk commented
Yes that was my opinion and with the name change it is close to Device
Config State already in Discovery. The question is do we have/need Device?

Paul (from my mobile device)


On Fri, Jan 12, 2024 at 12:18 PM maxhotta ***@***.***> wrote:

> [ External sender. Exercise caution. ]
>
> @pagbabian-splunk <https://github.com/pagbabian-splunk> Is the consensus
> that we move this class into the Discovery category?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ocsf/ocsf-schema/pull/914#issuecomment-1889898020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS5LBZVAVWRGYFOOL7TMO4DYOGLABAVCNFSM6AAAAABBNRZH4SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBZHA4TQMBSGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-17 02:03 UTC, pagbabian-splunk commented on dictionary.json
> +      },
Minor point, but there are no descriptions for the items. It may be self-evident for some, but not all:  E.g. OTA updated disabled, or SafetyNet failure.  Even 'Rooted' could use more description.  I know it can be a pain for the obvious ones.

2024-01-19 15:41 UTC, floydtree requested changes

2024-01-19 15:41 UTC, floydtree commented on objects/security_state.json
> +    "security_state": {
Since you are creating `security_state` object, you don't really need to create new attributes like `security_state_id` and `security_state` (also note, security_state has a conflict of being an object and a string type)

I would recommend using state, state_id as attributes in the objects and override their desc, enums etc. The two major benefits here are, attribute re-use and non-redundant query paths - (security_state.security_state_id vs security_state.state_id)

2024-01-19 17:43 UTC, pagbabian-splunk requested changes
We have a `risk_level` and `risk_level_id`, and a `log_level`.  Can we not say `current_security_level` and just say `security_level`?  It would imply current.  Then we only need to call out `prev_security_level` to distinguish it.  We have this convention for Registry: `reg_key` and `prev_reg_key`, `reg_value` and `prev_reg_value`.

2024-01-19 17:43 UTC, pagbabian-splunk commented on events/discovery/device_config_state_change.json
> +  }
We have a `risk_level` and `risk_level_id`, and a `log_level`.  Can we not say `current_security_level` and just say `security_level`?  It would imply current.  Then we only need to call out `prev_security_level` to distinguish it.  We have this convention for Registry: `reg_key` and `prev_reg_key`, `reg_value` and `prev_reg_value`.

2024-01-19 23:52 UTC, pagbabian-splunk commented
Very minor: our convention so far is to use `prev_` not `previous_` as with the `Registry Key` and `Registry Value` attributes.  It's also shorter but still quite clear.

2024-01-20 17:33 UTC, floydtree approved these changes
Thanks Max!

2024-01-22 22:29 UTC, pagbabian-splunk approved these changes

2024-01-23 19:23 UTC, jasonbreimer approved these changes
No issues.

2024-01-23 19:42 UTC, merged