adding verdict, verdict_id, verdict_type, and verdict_type_id to Incident_findings class.
ocsf/ocsf-schema pull request #930
Opened 2024-01-11 01:00 UTC by zschmerber

#### Related Issue: 
https://github.com/ocsf/ocsf-schema/issues/902
#### Description of changes:  In this PR I am adding verdict, verdict_id, vedict_type, and verdict_type_id. these will all be used in the incident finding and should be the last PR entered in V1.1

2024-01-11 01:06 UTC, zschmerber commented
Thoughts on adding` Duplicate` to the verdict_id?

2024-01-11 19:26 UTC, pagbabian-splunk commented
> Thoughts on adding` Duplicate` to the verdict_id?

Good idea.  I just looked at the merged PR for Incident, and there is a `resolution_id` which seems to overlap a bit with `verdict_id` - but it doesn't have a True Positive.

2024-01-11 19:49 UTC, zschmerber commented
> > Thoughts on adding` Duplicate` to the verdict_id?
> 
> Good idea. I just looked at the merged PR for Incident, and there is a `resolution_id` which seems to overlap a bit with `verdict_id` - but it doesn't have a True Positive.

That is a pretty big overlap. I think we need to choose one or the other to add that values too.

2024-01-11 19:58 UTC, pagbabian-splunk commented
Yes it is - I would just add to the `resolution_id` True Positive and Duplicate.  I'm not so sure about having a Resolved for `status_id` though, see my comment above.

2024-01-11 20:05 UTC, zschmerber commented
> Yes it is - I would just add to the `resolution_id` True Positive and Duplicate. I'm not so sure about having a Resolved for `status_id` though, see my comment above. Does Resolved also imply Closed? Also, would Duplicate be for a Detection Finding or other Finding, but not Incident Finding?

Ok I can do that, do we want to have a resolution_type_id field that works in parallel that contains analyst , provider ect...?

2024-01-11 20:11 UTC, floydtree requested changes

2024-01-11 20:11 UTC, floydtree commented on events/findings/incident_finding.json
> +      "description": "The normalized verdict type of the Incident normalized to the caption of the verdict_type_id value. In the case of 'Other', it is defined by the source.",
You don't need to re-define descriptions and enums at the class level since you are not overriding any values.

Just adding the group and requirement values would suffice

2024-01-11 20:11 UTC, floydtree commented on events/findings/incident_finding.json
> +      "requirement": "optional"
Should verdict_type_id be `recommended` instead?

2024-01-11 20:11 UTC, floydtree commented on events/findings/incident_finding.json
> +      "requirement": "required"
If we make verdict_id `required`, what are we expecting producers to populate it as when the incident record is first created? I think it should recommended

2024-01-11 20:13 UTC, floydtree commented
@zschmerber @pagbabian-splunk let's chat on slack for resolution vs verdict, easier and quicker to arrive at a consensus.

2024-01-11 20:54 UTC, zschmerber commented
<img width="1627" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/13574947/5bf17dca-73c3-4ca5-a882-ff666bcd74b7">
resolution_id and resolution and added the fields into verdict_id and verdict

2024-01-12 17:56 UTC, pagbabian-splunk commented
Looks good.  A few nits on the `verdict_id` labels in the dictionary.

The language isn't quite right for: 'The incident verdict can be disregarded' and related.  i.e. it's the incident that can be disregarded, not the incident verdict.  Similar to others in the list: the incident is a True Positive, or the incident verdict is True Positive (not incident verdict is a True Positive). I know these things are small.

Also, although we haven't been perfectly consistent, and it won't matter in the browser, we usually have `0 - Unknown` at the top of the list, and `99 - Other` at the bottom, but if not in that order, we have `99 - Other` and then `0 - Unknown` as the first two in the list followed by the actual values.

2024-01-12 18:12 UTC, floydtree requested changes

2024-01-12 18:12 UTC, floydtree commented on events/findings/incident_finding.json
> +      "description": "The normalized verdict type of the Incident normalized to the caption of the verdict_type_id value. In the case of 'Other', it is defined by the source.",
There's no need to define an extra description at the event level. Simpler to add this description in the dictionary and not override here.

2024-01-12 18:12 UTC, floydtree commented on events/findings/incident_finding.json
> +      "description": "The normalized verdict of the Incident normalized to the caption of the verdict_id value. In the case of 'Other', it is defined by the source.",
There's no need to define an extra description at the event level. Simpler to add this description in the dictionary and not override here.

2024-01-12 18:12 UTC, floydtree commented on dictionary.json
> +          "description": "The incident verdict can be disregarded."
Unclear what this item means

2024-01-12 18:23 UTC, zschmerber commented on dictionary.json
> +          "description": "The incident verdict can be disregarded."
changed it to say `"The incident verdict can be disregarded as it was unimportant and error or accident."`

2024-01-12 18:50 UTC, zschmerber commented
> Looks good. A few nits on the `verdict_id` labels in the dictionary.
> 
> The language isn't quite right for: 'The incident verdict can be disregarded' and related. i.e. it's the incident that can be disregarded, not the incident verdict. Similar to others in the list: the incident is a True Positive, or the incident verdict is True Positive (not incident verdict is a True Positive). I know these things are small.
> 
> Also, although we haven't been perfectly consistent, and it won't matter in the browser, we usually have `0 - Unknown` at the top of the list, and `99 - Other` at the bottom, but if not in that order, we have `99 - Other` and then `0 - Unknown` as the first two in the list followed by the actual values.

fixed this, also thoughts on verdict_type_id fields:
internal and external vs analyst verdict  and  provider?

2024-01-12 18:50 UTC, zschmerber commented on dictionary.json
> +          "description": "The incident verdict can be disregarded."
added new description for review

2024-01-12 23:16 UTC, pagbabian-splunk commented
Not that I want to copy, but UDM says 'Analyst Verdict' and 'Provider Verdict' - if we were to map those events, it would be straightforward.  Hard to say how I would decide whether Analyst Verdict was internal or external.

2024-01-16 18:01 UTC, floydtree approved these changes
Looks good!

2024-01-16 18:16 UTC, Aniak5 approved these changes
LGTM

2024-01-16 18:17 UTC, mikeradka approved these changes

2024-01-16 18:17 UTC, merged