New auth_factor Object to be used in Authentication Class
ocsf/ocsf-schema pull request #949
Opened 2024-01-29 16:32 UTC by brandikuritz

#### Description of changes:
This PR creates a new object, `auth_factor`, and adds an array of `auth_factor`s to the authentication class, `auth_factors`. The new fields for this object are added to dictionary.json. 

Currently, there is not a good way to represent different MFA factors in the authentication class. `auth_factors` describes the factor(s) used in an authentication attempt, as well as the device used to complete the authentication attempt. This information is important for maintaining security and incident responses, especially for MFA centric companies like Duo Security. 

Authentication Factor object on the Authentication Class (locally): 
![image](https://github.com/brandikuritz/ocsf-schema/assets/141661954/eb4dfe6b-1a82-4ef0-9332-32435e21a468)

Authentication Factor object defined (locally): 
<img width="799" alt="Screenshot 2024-01-08 at 7 22 13 PM" src="https://github.com/brandikuritz/ocsf-schema/assets/141661954/f6844f63-b2a5-4c44-928b-ebcbdebdf4a6">

2024-02-07 16:23 UTC, pagbabian-splunk submitted a review, later dismissed
LGTM

2024-02-07 16:24 UTC, pagbabian-splunk commented
On comment: I think we would want to add an item to the Unreleased section in CHANGE.OG.md once merged.

2024-02-07 16:34 UTC, mikeradka commented
Overall looks good. It serves a useful purpose. 
A couple of minor questions here:

- Is there a hard need to have `factor_` prepended to the attributes? The `auth_factor` object sort of implies that these attributes pertain to a factor. If these are just regular `email`, `device`, etc attributes than maybe there might not be need for prepending.
- `factor_telephony_number` - is there possibly a way to make this attribute name more concise? `no` instead of `number`? Removing `factor_`? Or simply making it `telephony`? Just some quick food for thought.
- `factor_question` - is the scenario always one question? Or is there a scenario where there would be multiple questions? If such a scenario exists, would we need a `questions` array?

2024-02-07 21:36 UTC, pagbabian-splunk commented
> * Is there a hard need to have `factor_` prepended to the attributes? The `auth_factor` object sort of implies that these attributes pertain to a factor. If these are just regular `email`, `device`, etc attributes than maybe there might not be need for prepending. The attributes' descriptions could always be overridden within this object to specify that these attributes pertain to the auth_factor.
> * `factor_telephony_number` - is there possibly a way to make this attribute name more concise? `no` instead of `number`? Removing `factor_`? Or simply making it `telephony`? Just some quick food for thought.
> * `factor_question` - is the scenario always one question? Or is there a scenario where there would be multiple questions? If such a scenario exists, would we need a `questions` array?
> 
Good point @mikeradka : if the attributes are otherwise the same as the standalone `device` `email` etc. then no need to create new ones with a prefix, and the specific descriptions can be overridden within the class/object definition. On the other hand, if one of these `factor_` attributes is different than the `_xx` attribute, we would need the prefix.

2024-02-07 22:40 UTC, Aniak5 commented
I also agree with @mikeradka, we probably don't need to have the `factor_` prefix for the added attributes. As @pagbabian-splunk said, we can overwrite their descriptions and captions within the authentication factor object.

2024-02-07 22:42 UTC, Aniak5 commented on dictionary.json
> +      "description": "The phone number used for a telephony-based authentication request.",
Is `telephony` a common term used for this? Why not just `phone_number` or `telephone_number`?

2024-02-08 15:07 UTC, floydtree requested changes
Overall, a great addition. Definitely something that was needed for the Authentication class. But I agree with the points regarding the `factor` prefix raised above, the main reason being, we want to avoid redundancy in attribute naming, in this case, going from` auth_factor.factor_*` to `auth_factor.*`. Basically, letting the object add the context and reduce the number of new attributes needed.

Additionally, it would be great if you can add an entry in the `Unreleased` section in CHANGELOG.md file. Feel free to refer to the previous entries.

2024-02-20 15:00 UTC, floydtree approved these changes
Looks good! Thank you.

2024-02-20 15:56 UTC, Aniak5 approved these changes
LGTM! Thanks!

2024-02-20 16:27 UTC, mikeradka approved these changes

2024-02-20 16:56 UTC, pagbabian-splunk approved these changes

2024-02-20 16:58 UTC, merged

2024-02-20 16:58 UTC, pagbabian-splunk commented on dictionary.json
> +      "description": "The phone number used for a telephony-based authentication request.",
Telephony, odd sounding as it sounds, is the actual name I believe.  "Telephony is the field of technology involving the development, application, and deployment of telecommunication services for the purpose of electronic transmission of voice, fax, or data, between distant parties. The history of telephony is intimately linked to the invention and development of the telephone"