Correct type for priority field
ocsf/ocsf-schema pull request #959
Opened 2024-02-07 20:53 UTC by jbertman

#### Description of changes:
Other normalized string fields that map to an enum are strings, not integers. The sample data API generates a string for the `priority` field, which fails the JSON schema validation. This corrects the type to reflect the paradigm in the rest of the schema.

### Delete once you have confirmed the following: 
4. Have you assigned appropriate labels to the PR?

2024-02-07 21:04 UTC, mikeradka submitted a review, later dismissed
Great catch, and thanks for adding the note to CHANGELOG. Only small request, we might want to tag this PR with "bug" if it's not already tagged with it. Imo it is a legitimate bug, though there could be something I'm missing.

2024-02-07 21:09 UTC, floydtree commented
This is definitely a bug, thanks for fixing it!

2024-02-07 21:11 UTC, floydtree requested changes

2024-02-07 21:11 UTC, floydtree commented on CHANGELOG.md
> +### Misc
Just a minor change, can you add the PR number in the end?

->
> Changed datatype of `priority` from `integer_t` to `string_t` #959

2024-02-07 21:38 UTC, jbertman commented on CHANGELOG.md
> +### Misc
done 👍

2024-02-08 14:58 UTC, floydtree approved these changes

2024-02-08 15:26 UTC, mikeradka approved these changes
Lgtm

2024-02-08 16:00 UTC, Aniak5 approved these changes
Good catch!

2024-02-08 16:00 UTC, merged