feat: add autonomous_system object to network_endpoint
ocsf/ocsf-schema pull request #980
Opened 2024-03-08 03:28 UTC by shellcromancer

#### Related Issue: 

Closes #978

#### Description of changes:

feat: add autonomous_system object to network_endpoint. 

Additionally formats `dictionary.json` for whitespace inconsistencies.

2024-03-11 23:44 UTC, pagbabian-splunk approved these changes

2024-03-12 12:34 UTC, floydtree requested changes

2024-03-12 12:34 UTC, floydtree commented on objects/autonomous_system.json
> +      "org_name"
Looks like a name error, should this be `name`?

2024-03-12 13:12 UTC, shellcromancer commented on objects/autonomous_system.json
> +      "org_name"
Yep, great catch. Just pushed a fix. I didn't notice any errors when loading the `ocsf-server` for this in case that should validate constraints.

2024-03-12 14:14 UTC, Aniak5 commented on dictionary.json
> +      "description": "The Autonomous System num associated with an IP address.",
Nit: Since we this object contains more than just the AS number, can we change this to something like `"The Autonomous System details associated with an IP address."`

2024-03-12 14:35 UTC, Aniak5 approved these changes
LGTM! Thanks for adding this, it's super useful!

2024-03-12 16:32 UTC, floydtree approved these changes

2024-03-13 16:01 UTC, pagbabian-splunk approved these changes

2024-03-13 16:29 UTC, floydtree approved these changes

2024-03-13 16:29 UTC, pagbabian-splunk approved these changes

2024-03-13 16:40 UTC, Aniak5 approved these changes

2024-03-13 16:40 UTC, merged