Create `agent` Object, add `agent` and `owner` to `device`
ocsf/ocsf-schema pull request #987
Opened 2024-03-15 18:43 UTC by jonrau-at-queryai

#### Related Issue: 

#986 

#### Description of changes:

- Adds `owner` to `device`, `endpoint`, and `network_endpoint`.
- Adds a new `agent` object that defines various sensors and agent.
- Adds the new `agent` object to `device`, `resource`, and `endpoint`.
- Adds `is_applied` Boolean to `policy`.

2024-03-18 18:18 UTC, mlmitch commented on dictionary.json
> +    "manufacturer": {
Could [`vendor_name`](https://github.com/ocsf/ocsf-schema/blob/f5b260cdddc1dfaefd2f0ce2dbc5001d54a903f5/dictionary.json#L4126) be used instead of introducing this attribute?

2024-03-18 21:22 UTC, jonrau-at-queryai commented on dictionary.json
> +    "manufacturer": {
Oh duh, good point.

2024-03-19 13:14 UTC, floydtree requested changes

2024-03-19 13:14 UTC, floydtree commented on objects/network_endpoint.json
> +    "owner": {
nit: same as the comment for `agent_list` in device. (redundant definition)

2024-03-19 13:36 UTC, jonrau-at-queryai commented on objects/device.json
> +    "agent_list": {
Good point, fixed it

2024-03-19 14:33 UTC, floydtree approved these changes
Looks good, thank you!

2024-03-19 15:16 UTC, mikeradka approved these changes
Looks good to me

2024-03-19 15:49 UTC, pagbabian-splunk commented on objects/agent.json
> +          "requirement": "recommended"
Do you mean for the name of the agent to be the "Organization name for the Autonomous System."  Seems like a cut and paste issue?

2024-03-19 15:51 UTC, jonrau-at-queryai commented on objects/agent.json
> +          "requirement": "recommended"
Fixed. Good catch, that's what happens when you work on 2 PRs at once.

2024-03-19 16:02 UTC, pagbabian-splunk commented
Please check the description of `name` : "Organization name for the Autonomous System."

2024-03-19 16:45 UTC, floydtree submitted a review, later dismissed

2024-03-19 17:01 UTC, zschmerber approved these changes

2024-03-20 15:09 UTC, mlmitch reviewed
LGTM.

This is a great addition for being able to natively use OCSF in an EDR.
Having homes for the agent identifier and the customer organization identifier is crucial.

2024-03-24 17:23 UTC, zschmerber submitted a review, later dismissed

2024-03-25 19:06 UTC, mikeradka approved these changes

2024-03-25 19:08 UTC, mikeradka commented
@jonrau-at-queryai Looks good to me, just approved, but there is a small merge conflict with the CHANGELOG. Could you update that so we can merge?

2024-03-25 19:11 UTC, jonrau-at-queryai commented
> @jonrau-at-queryai Looks good to me, just approved, but there is a small merge conflict with the CHANGELOG. Could you update that so we can merge?

Looks like it's fixed, but it bumped all of the approvals again.

2024-03-25 19:12 UTC, mikeradka submitted a review, later dismissed

2024-03-26 13:20 UTC, floydtree submitted a review, later dismissed

2024-03-28 13:59 UTC, Aniak5 commented on dictionary.json
> +      "description": "A list of <code>agent</code> objects associated with a device, endpoint, or resource",
Nit: Can we please add a `.` at the end of this description?

2024-03-28 14:31 UTC, jonrau-at-queryai commented on dictionary.json
> +      "description": "A list of <code>agent</code> objects associated with a device, endpoint, or resource",
@Aniak5 will do!

2024-03-28 14:43 UTC, Aniak5 commented
Looks great! Thanks for this addition, its super useful!

2024-03-28 14:43 UTC, Aniak5 approved these changes
LGTM

2024-03-28 14:44 UTC, mikeradka approved these changes

2024-03-28 15:00 UTC, floydtree approved these changes

2024-03-28 16:00 UTC, merged