Create `threat_intelligence` Profile, add STIX 2.1 SDOs to OCSF
ocsf/ocsf-schema pull request #992
Opened 2024-03-19 23:47 UTC by jonrau-at-queryai

#### Related Issue: 

#988 

#### Description of changes:

- Added `threat_intelligence` object.
- Added `threat_intelligence` Profile based on `threat_intelligence` object.
- Added `signatures` object, an array of `signature` objects.
- Added `subdomains` object, an array of `subdomain` used to enumerate DGA-generated domains.
- Added `whois` object.
- Added `contact` and array-typed `contacts` object for use with `whois` object.
- Added `stix_object` object to serve as a base STIX Object that contains mandatory and optional common properties.
- Added several STIX 2.1 SDO-based objects: `stix_campaign`, `stix_malware`, `stix_malware_analysis`, `stix_intrusion_set`, `stix_threat_actor`, and `stix_tool` corresponding to the following SDOs, respectively: Campaign, Malware, Malware Analysis, Intrusion Set, Threat Actor, and Tool.
- Added `is_self_signed` Boolean attribute to `certificate` object.

Several dozen attributes were added to `dictionary` to support `whois`, `contact` and the various `stix_` objects. Attributes were re-used as much as possible where they made sense.

2024-04-16 16:33 UTC, mikeradka commented on objects/contact.json
> +	"name": "contact",
Question here - is there a particular reason this is `contact` instead of `domain_contact`? I'm wondering if there is a possibility that `contact` might get confused or otherwise mixed up with a user's contact info.

2024-04-19 21:29 UTC, pagbabian-splunk commented on objects/contact.json
> +	"name": "contact",
I agree - `contact` could in the future be used elsewhere, and given this object is very specific to Domain Contact, it's name should be `domain_contact` matching its Caption.

2024-04-19 21:49 UTC, pagbabian-splunk commented
Aside from this being really well worked out, it is also quite a substantial amount of STIX / TI specific information, with some naming questions here (some attributes are `stix_` prefixed, a few are not but in their definitions they cite STIX.

I also feel there is enough to merit a "platform" of sorts where it can be package up within a core extension.  I know that our core extensions today are "OS platform" extensions and STIX isn't exactly the same thing, but we can have OCSF extensions just like we can have vendor extensions.  External standards can be modeled this way, keeping attributes in their own dictionary.  The notation would already scope by extension name (e.g. stix/xx).  Same can be done for d3fend, which we are considering for a Remediation category.  Otherwise, the core dictionary will get very large and there will be a lot of external standards specific naming mixed in.

2024-04-22 14:33 UTC, jonrau-at-queryai commented
> Aside from this being really well worked out, it is also quite a substantial amount of STIX / TI specific information, with some naming questions here (some attributes are `stix_` prefixed, a few are not but in their definitions they cite STIX).
> 
> I also feel there is enough to merit a "platform" of sorts where it can be package up within a core extension. I know that our core extensions today are "OS platform" extensions and STIX isn't exactly the same thing, but we can have OCSF extensions just like we can have vendor extensions. External standards can be modeled this way, keeping attributes in their own dictionary. The notation would already scope by extension name (e.g. stix/xx). Same can be done for d3fend, which we are considering for a Remediation category. Otherwise, the core dictionary will get very large and there will be a lot of external standards specific naming mixed in.

@pagbabian-splunk I agree on the overall approach. I feel we should go ahead and remove the `stix_` related information from this and instead rework this object to be `open_source_intelligent` (or `osint`) as it'll pertain to only technical factors instead and be much simpler without STIX in scope.

2024-05-02 20:45 UTC, mikeradka commented
What are folks' thoughts on shortening the name to `OSINT`, at least where it would show up on the schema server?checkboxes?

2024-05-02 20:46 UTC, jonrau-at-queryai commented
> What are folks' thoughts on shortening the name to `OSINT`, at least where it would show up on the schema server checkboxes?

I was thinking of making it `osint` but not sure how we felt about acronyms, or even `iocs` which could work

2024-05-07 04:48 UTC, mavam commented
Why do we need "open source" as part of name? To me, the visibility of this type of information is orthogonal to its content. Have you considered make the visibility an attribute instead?
In my mental model, I have "threat intelligence" and that can be private, open source, etc.

On a related note, I suggest adding a [TLP](https://www.first.org/tlp/) field.

2024-05-07 04:54 UTC, mavam commented on objects/open_source_intelligence.json
> +			"enum": {
I would align those with STIX SCOs for better composability of the two standards.

2024-05-07 16:05 UTC, jonrau-at-queryai commented on objects/open_source_intelligence.json
> +			"enum": {
I'm taking all of the STIX mentions out. Didn't seem to be a lot of support.

And on the naming, OSINT more closely matches this, this isn't exactly an intelligence product and I am loathe to use that name especially if SCOs or SDOs eventually do make their way back in with another mechanism

2024-05-07 18:02 UTC, jonrau-at-queryai commented
> On a related note, I suggest adding a [TLP](https://www.first.org/tlp/) field.

Just added that, good call. It's a string-based enum which are a little weird

2024-05-21 16:11 UTC, floydtree commented on objects/domain_contact.json
> +			"description": "The normalized domain contract type ID.",
nit: typo for contact in the desc

2024-05-21 16:21 UTC, floydtree requested changes

2024-05-21 16:21 UTC, floydtree commented on objects/domain_contact.json
> +			"description": "The normalized domain contract type ID.",
nit: typo for contact in the desc

2024-05-21 16:21 UTC, floydtree commented on objects/domain_contact.json
> +			"description": "The name of the normalized entry for Type ID.",
nit: minor change in desc to be consistent with other string siblings, something like - 

`The Domain Contact type, normalized to the caption of the type_id value. In the case of 'Other', it is defined by the source`

2024-05-21 16:21 UTC, floydtree commented on CHANGELOG.md
Probably good to rebase and only add the new items?

2024-05-21 17:01 UTC, floydtree requested changes

2024-05-21 17:01 UTC, floydtree commented on profiles/osint.json
In which classes are we planning to apply this profile?

2024-05-23 21:02 UTC, jonrau-at-queryai commented on dictionary.json
> +    "osint": {
I think should be one our perma-array types, so to speak

2024-05-23 21:11 UTC, jonrau-at-queryai commented on profiles/osint.json
All of them, this is a source of enrichment that's possible to accomodate any of our events, at least moderately.

2024-05-28 16:07 UTC, zschmerber submitted a review, later dismissed

2024-05-28 16:08 UTC, query-jeremy submitted a review, later dismissed

2024-05-28 16:11 UTC, irakledibm approved these changes

2024-05-29 14:18 UTC, floydtree requested changes
Thanks for getting in all the feedback! I think we are almost there. I have added a few line specific comments, but in general, if we want this profile to be usable by event classes in the framework we need to add it to those classes. Currently, if you run the server locally, you'll notice the profile won't even be visible in the profiles page, since it's not registered with any class.

Having said that, I would expect this profile to be available for **all the classes.** If that's your intention as well, then you'll need to add it to the `base_event` definition - similar to how cloud, datetime are added. Happy to discuss further.

2024-05-29 14:18 UTC, floydtree commented on profiles/osint.json
> +  "description": "The OSINT (Open Source Intelligence) object contains details related to an indicator such as the indicator itself, related indicators, geolocation, registrar information, subdomains
Minor: Would be good if you can shape the description to be about the profile, instead of an object

2024-05-29 14:18 UTC, floydtree commented on objects/osint.json
> +		"autonomous_system": {
To confirm, is it intentional to have `autonomous_system` in 2 levels within this object? 1 is defined here at the top, and the other is coming as nested attr within the `whois` object.

2024-05-29 14:18 UTC, floydtree commented on dictionary.json
> +    "aliases": {
this is not used anywhere is the schema, intentional?

2024-05-29 14:18 UTC, floydtree commented on objects/whois.json
> +		"last_seen_time": {
missing requirement key

2024-05-29 14:18 UTC, floydtree commented on objects/osint.json
> +    "tlp": {
missing requirement key

2024-05-29 16:41 UTC, jonrau-at-queryai commented on objects/osint.json
> +		"autonomous_system": {
Yeah, that one is intentional. There may be a top-level indicator such as an IP address that has AS information tied to it on its own. It's part of WHOIS so it can be used separately in the future, or if AS information is tracked as the registrar level too.

I wouldn't see both used at the same time per se.

2024-05-29 17:41 UTC, jonrau-at-queryai commented on dictionary.json
> +    "aliases": {
removed

2024-05-30 19:09 UTC, floydtree requested changes

2024-05-30 19:09 UTC, floydtree commented on events/base_event.json
>      "$include": [
You would need to add the profile in the `$include` key. Check the screen shot below for reference.
![Screenshot 2024-05-30 at 15 09 00](https://github.com/ocsf/ocsf-schema/assets/89877409/8896c292-ed76-49f8-a457-df71c41c6aff)

I would highly recommend running the ocsf server locally to help catch such issues.

2024-05-30 20:18 UTC, jonrau-at-queryai commented on events/base_event.json
>      "$include": [
I've been trying to avoid that 😆

2024-05-31 12:49 UTC, floydtree approved these changes
Awesome, looks perfect now. Thanks.

2024-05-31 15:59 UTC, zschmerber approved these changes
Great work on this!

2024-05-31 17:49 UTC, mikeradka approved these changes

2024-05-31 17:49 UTC, merged